### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by bazyrush** [MTrab/landroid_cloud#109]
## Environment:
- Home Assistant version: 2022.4.6
- Landroid_cloud version: 1.8.6
- Operation system: HA Supervised (Ubuntu 20.10 on NUC 10 i3)

## Configuration

```yaml
landroid_cloud:
  - email: xxx@gmail.com
    password: xxx
```

## Describe the bug
This was set up and working fine for >a yr. Recently it does not load properly on startup with a "integration could not be set up" error. Frustratingly I can' t remember exactly when this started, or what might have changed, but it has been within the past 2 wks. 

I have tried changing my account password in the app and on https://account.worxlandroid.com . I have used a simple password (lower case letters only, no special chars). I have removed and reinstalled the integration through HACS. I have commented the config out, rebooted, and readded the config as per the readme. I have also removed my landroid from the account and re-linked it using the app, as per the readme. None of this has worked.

In the debug log it looks like it might be connecting to the account (it shows the new device name, and I changed this when I removed and re-linked the landroid from the account) but I still get the errors and no entities working in HA.

## Debug log
```
2022-04-24 10:26:25 DEBUG (MainThread) [custom_components.landroid_cloud] Connecting to device ID 0 (xxx@gmail.com)
2022-04-24 10:26:29 DEBUG (MainThread) [custom_components.landroid_cloud] Forcing update for Daisy
2022-04-24 10:26:29 DEBUG (MainThread) [custom_components.landroid_cloud] Partymode available: True
2022-04-24 10:26:29 DEBUG (MainThread) [custom_components.landroid_cloud] OTS enabled: True
2022-04-24 10:26:30 WARNING (MainThread) [custom_components.landroid_cloud] Error in authentication!
```

**Comment by MTrab** [comment]
Strange - just tried setting up a new HA and installing landroid_cloud
I see no errors on using my old S500.
Not sure if this could be something with newer models.

If possible, would you temporarily let me login to your Landroid account to test it from my side?
If so - account info can be sent to github_2022@trab.dk

**Comment by bazyrush** [comment]
> Strange - just tried setting up a new HA and installing landroid_cloud I see no errors on using my old S500. Not sure if this could be something with newer models.
> 
> If possible, would you temporarily let me login to your Landroid account to test it from my side? If so - account info can be sent to [github_2022@trab.dk](mailto:github_2022@trab.dk)

Hi, thanks for the offer, more than happy for you to take a look. I get a bounceback from that email addy though?

**Comment by MTrab** [comment]
Sorry - there was a misconfiguration on the server.
Should be fixed now thou

**Comment by MTrab** [comment]
![image](https://user-images.githubusercontent.com/14296463/165797860-c5303005-0009-4827-a0b7-dfe66c755334.png)
No problem in a clean Home Assistant instance.
So if you still have problems, I guess you have made a local error.
