### ISSUE TITLE
Landroid 'blocked' from App+Landroid Cloud - unable to unblock?

### ISSUE THREAD

**Issue by Trashmee** [MTrab/landroid_cloud#110]
I was able to setup Landroid Cloud & HomeAssistant configuration on the weekend - since Sunday late night I can't reach my landroid via App or HomeAssistant. Is there a way to verify that I've been banned / blocked?

I found the instructions on how to handle 'beeing banned' at https://github.com/MTrab/landroid_cloud
- Go to "My Landroids -> Unlink your Landroid(s)"

I used "My Landroid -> Ownershop -> Disconnect Landroid form your account" as I did not see an unlink option.

However, for 52hours I'm unable to connect to my Landroid, despite:
 - Disableing landroid cloud yesterday
 - Disconnecting via above process & re-adding my Landroid via App twice
 - Trying to connect via the App via 5G network (different IP)
 - Reconnecting my DSL (different IP)
 
There are (at least) two questions:
 - What am I doing wrong here?
 - Is there a way to use landroid_cloud and avoid this, e.g. I did not find a parameter to decrease the connections to worx cloud in landroid_cloud?

I'm using:
 - WR142E with latest firmware, upgraded in Q1 2022.
 - Landroid_cloud from "git pull" on 25th

Very happy to provide more details, but as I was able to see & control my Landroid via HomeAssistant on Sunday I'm assuming its not related to the actual configuration, but the 'tampering around to get it done'.

**Comment by MTrab** [comment]
It sounds like a ban, yes - so unlinking/disconnecting is the correct solution.
But if you can't reconnect the Landroid to your account, you need to reach out to Worx support - that I can't help with.

As for avoiding this issue?! Don't change the interval for refresh in the code and avoid using excessive calls to the update function, as the integration handles this automatically.

**Comment by Trashmee** [comment]
worx support didn't come back yet - but they won't have to, entirly my fault. It seems somewhen in the process i moved my Landroid in the 'no internet' IP range of my home network. 

5 minutes after that though came up this morning all is fine again. I'll try to close the ticket - if I can't - don't hesitate to do so, please.

Sorry to bother - thanks a lot of your amazing work & super quick response above!
