### ISSUE TITLE
No edgecut service

### ISSUE THREAD

**Issue by ErwinKnapen83** [MTrab/landroid_cloud#113]
Hi thanks for this cool integration,
I have a wr105si running firmware 3.52 ( latest ) to the workx documentation it supports edgecut.

but I don’t see the edgecut service availible
Any thoughts on why this is? 

Thanks in advance!

**Comment by ErwinKnapen83** [comment]
Landroid S 2017/2018 
WR101SI, WR102SI, WR104SI, WR105SI, WR106SI, WR110MI, WR100SI, WR101SI.1, WR102SI.1, WR103SI, WR104SI.1, WR105SI.1, WR106SI.1, WR110MI.1, WR115MI.
If you want to change this pre-set, you can modify it via your smartphone through the app:
1. Enter into the app menu
2. Go to “Schedule” , then to “Manual Schedule”
3. Select the day and enable (or disable) “edge cut”
( source: https://wiki.worx.com/en/cut-to-edge-border-management )

**Comment by ErwinKnapen83** [comment]
![Uploading 37823EA1-C077-4B5E-B526-8F6AA060CC9B.png…]()

**Comment by MTrab** [comment]
Do you see the Edgecut possibility in the app (aside from the schedule settings)?

**Comment by ErwinKnapen83** [comment]
I see it in the schedule and activity log. I don’t see a option for it anywhere else in the app.

**Comment by MTrab** [comment]
There you have the answer - then your mower is, like mine, not compatible with "edgecut-ondemand"

Only the newer mowers have this option in the app and in the integration.

**Comment by MTrab** [comment]
![fk5v3xjf42j51](https://user-images.githubusercontent.com/14296463/166673915-ff3a6084-a61b-47a8-9fdd-1336b5b83bbd.png)

**Comment by ErwinKnapen83** [comment]
Thanks, I’ll look into it to see if I can adjust the schedule somehow to trigger it “semi” on demand.
