### ISSUE TITLE
Status id and error id attributes removed in 2.x

### ISSUE THREAD

**Issue by dbochicchio** [MTrab/landroid_cloud#122]
Hi @MTrab and thanks for this component.

I was previously using status id and error id attributes because they're always consistent, in a couple of automations.

Could you please bring them back, since they're missing from the current release? Thanks.

**Comment by MTrab** [comment]
As the integration have moved to vacuum domain, new states are used to be as compliant with this as possible. Therefore the status_id no longer makes any sense to use - the states are 100% consistent when using the vacuum domain.

I'll add the error_id to the attributes thou.

**Comment by dbochicchio** [comment]
Thanks. As you're reporting special states (like edgecut) not being in the vacuum domani, I still think the status id is relevant, but I'll try to map them again, hoping they'll be stable for the future. Thanks again for the quick response.

**Comment by MTrab** [comment]
They'll follow the official vacuum states, with exception of a few specific for this integration.
But they'll stay as now, at least until an official mower platform is released
