### ISSUE TITLE
HACS install 'Entity not available'

### ISSUE THREAD

**Issue by markdswan926** [MTrab/landroid_cloud#127]
Hi,

thanks for providing this package, just what I need!

I have followed to install process https://github.com/MTrab/landroid_cloud.

My install appears to be working and a can see sensors, but no entity's have been created. What have I done wrong?

Thanks in advance

**Comment by markdswan926** [comment]
![image](https://user-images.githubusercontent.com/60292148/170885012-8c976a69-4c74-48aa-a8d2-612d82e53107.png)

**Comment by markdswan926** [comment]
One line in the install process that confused me was:

**Comment by MTrab** [comment]
Apparently not read the release notes for the v2.0 pre-release ;)

There are NO sensors anymore, only a vacuum entity.

**Comment by markdswan926** [comment]
thanks, except I am running 1.8.10, not V2....

**Comment by MTrab** [comment]
And you don't have sensor.your_mower_name_* sensors?

**Comment by MTrab** [comment]
If not, then please provide logs

**Comment by markdswan926** [comment]
I have sensors yes:

**Comment by markdswan926** [comment]
![image](https://user-images.githubusercontent.com/60292148/170885393-d4919f48-a089-4e97-9169-b98ed418613c.png)

**Comment by MTrab** [comment]
Perfect - then the integration works as intended.
Go follow barma-lej's instructions to the frontend you are using.
