### ISSUE TITLE
Cant find the integration after download of the repo

### ISSUE THREAD

**Issue by Lundte** [MTrab/landroid_cloud#129]
**Description:**
I have downloaded the repo using HACS. After download I want to add it as an integration, but it doesnt appear.

**The error from the log:**
2022-05-30 14:19:46 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration landroid_cloud which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with 

**Additional info:**
I use the Unraid GUi which also means that my Home assistant is installed as docker. 
When I try to open the configuration.yaml file it is empy. Properly because there is a default config. But I cant seems to find it

Home Assistant version: 2022.5.5
Landroid_cloud version: 1.8.1
Operation system: Unraid

I hope it was enough information for you to start the troubleshoot.

**Comment by MTrab** [comment]
You need to add the integration using YAML config in the configuration.yaml file.
Integration flow is for version 2 which is in beta testing right now.
