### ISSUE TITLE
Missing Services for Mower Control

### ISSUE THREAD

**Issue by Subbilein** [MTrab/landroid_cloud#133]
I installed the new 2.01 release. First of all, thanks a lot for this great work!

unfortunatly i‘m missing the services for
Start, Pause, and Home Coming in this integration. 

Is that right, or have i only to open my eyes ?

thanks in advance  

Subba

**Comment by MTrab** [comment]
In version 2 we have moved to vacuum platform. So the start, pause and stop are vacuum services.

**Comment by Subbilein** [comment]
Thanks for the quick reply. Now i got it. 

Many thanks for your great work at all  !!
