### ISSUE TITLE
Can not restart Home Assistant since yesterday

### ISSUE THREAD

**Issue by miktin** [MTrab/landroid_cloud#137]
Since Yesterday i habe a Problem für update Landroid_cloud. 
Also if i delete landroid_cloud i have the same Massage.
„ The system cannot restart because the configuration is not valid: Package landroid setup failed. Component landroid_cloud cannot be merged. Expected a dict.„
I do Not change anything. Only Update.

**Comment by miktin** [comment]
Version | core-2022.6.0
-- | --
Installationstyp | Home Assistant OS
Entwicklung | false
Supervisor | true
Docker | true
Benutzer | root
Virtuelle Umgebung | false
Python-Version | 3.9.12
Betriebssystemfamilie | Linux
Betriebssystem-Version | 5.15.41
CPU-Architektur | x86_64
Zeitzone | Europe/Berlin

<div class="card-header" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; justify-content: space-between; display: flex; align-items: center; caret-color: rgb(225, 225, 225); color: rgb(225, 225, 225); font-family: Roboto, Noto, sans-serif; font-size: 14px; -webkit-tap-highlight-color: rgba(0, 0, 0, 0.1);"><h3>Home Assistant Supervisor</h3></div>

Host-Betriebssystem | Home Assistant OS 8.1
-- | --
Update-Channel | stable
Supervisor-Version | supervisor-2022.05.3
Agent-Version | 1.2.1
Docker-Version | 20.10.14
Speicherplatz gesamt | 457.7 GB
Speicherplatz genutzt | 9.2 GB
Gesund | true
Unterstützt | true
Board | generic-x86-64
Supervisor-API | ok
Versions-API | ok
Installierte Add-ons | ESPHome (2022.3.1), File editor (5.3.3), SSH & Web Terminal (10.1.3), Samba share (9.6.1), InfluxDB (4.4.1), Mosquitto broker (6.1.2), Frigate NVR (Full Access) (3.1), evcc (0.94), Home Panel (2.4.0)

Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/__init__.py:684 
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22)) 
First occurred: 20:45:16 (1 occurrences) 
Last logged: 20:45:16

[140335954000768] The system cannot restart because the configuration is not valid: Package landroid setup failed. Component landroid_cloud cannot be merged. Expected a dict.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1704, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1741, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 684, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Package landroid setup failed. Component landroid_cloud cannot be merged. Expected a dict.

**Comment by MTrab** [comment]
And your configuration?

**Comment by miktin** [comment]
landroid_cloud:
  - email: !secret mower_mail
    password: !secret mower_pass

**Comment by miktin** [comment]
Ves v2.02
I delete in configuration.yaml 
Gut i have Allahs same Error if i warnt to restart. I delete landroid cloud, same error

**Comment by miktin** [comment]
No. The Problem was # https://github.com/Barma-lej/halandroid if you Installateur it then you got the error again.

**Comment by MTrab** [comment]
Yes - version 2 is NOT compatible with the barma-lej package yet. That is also mentioned in the first few lines of the release notes.
