### ISSUE TITLE
[FR]: split out the different attributes as entities

### ISSUE THREAD

**Issue by larronni** [MTrab/landroid_cloud#144]
**Describe the solution you'd like**
It would be nice to have the attributes of the device as separate entities. 

Example;  battery, error, error ID, rain delay, etc

**Comment by MTrab** [comment]
Right now I'm following the vacuum design, where this is attributes.

**Comment by larronni** [comment]
ok - but the vacuum design also has entities. 
Eg Roomba integration has binary sensor as entities....
![image](https://user-images.githubusercontent.com/49139069/171615998-9df5a5d8-5bb7-4e22-b28a-2be19d73ccb0.png)
![image](https://user-images.githubusercontent.com/49139069/171616021-a2aa7a16-563b-458b-ac6c-3ece8d88f8aa.png)

**Comment by MTrab** [comment]
I've followed the Tuya vacuum design that frenck have made, to make sure it was along the design guides.
Can't say for Roomba if that is up to date with the current design guide.
