### ISSUE TITLE
Second Landroid missing after upgrade

### ISSUE THREAD

**Issue by spiralfive** [MTrab/landroid_cloud#146]
I upgraded to the 2.x version yesterday of the integration and noticed today that only one of my Landroids (of two) is present. I tried setting up the integration a second time, but that did not work as it says my account is already present. I also tried deleting the integration and re-adding it, but again only one was added (the same one). 

I do not see any errors in the system log related to this integration, if there is a log file elsewhere, I can look at/share I will check there. I can control both Landroids in the app without any issue, and prior to upgrading could using the integration as well. 

![image](https://user-images.githubusercontent.com/26095643/171654820-1125685f-9029-4562-bdc9-10737eb5ada6.png)

![image](https://user-images.githubusercontent.com/26095643/171654966-47ab18d5-ab47-408c-9b0b-77ad1c1b6189.png)

**Comment by MTrab** [comment]
Don't think I need to send commands to it - if it loads it'll work ;)

**Comment by jcustenborder** [comment]
If you need another with multiple I can help as well. I have 5. 2x WR150s 2x WR155s. 1x that was stolen that is just sitting in the account. They all are in random states at the moment as well. One with a broken wire that I'm gonna fix soon.

**Comment by MTrab** [comment]
@jcustenborder could be great - think I have it working in my development, but all devices are in docked state right now.
So just for the sake of testing before release, you are more than welcome to send credentials on github_2022 (at) trab.dk

**Comment by arcano81** [comment]
Same issue also here.
I have 2 landroids WR130e and WR167e but only one is showing in the app. Both robots are at home mowing the garden!!
@MTrab Let me know if you need access to account for testing.

**Comment by jcustenborder** [comment]
@MTrab I just sent you the credentials! Thanks for taking a look! Right now I have via the app. 

* Back Left - Outside wire
* Back Right - Starting but hasn't updated. Acts like it's offline
* Front Right - Wire missing
* Front Left - Trapped 
* Stolen - has not updated in more than a year. Was stolen and Worx told me to keep it in the account. They will notify me if it comes online.

I'm still working through all the obstacles in the yard and placements of radio links.

**Comment by MTrab** [comment]
> I have 2 landroids WR130e and WR167e but only one is showing in the app.

Your devices are newer than the other I have test access to right now - could be nice to confirm checks and functions of newer devices is working as well, before releasing the next version.
Please send me the credentials at github_2022 (at) trab.dk if you are still willing to help out 🙂

**Comment by lucrom61** [comment]
Hello.
I have three Landroids.
WR104SI
WR102SI.1
WR142E

After the update I only see the WR142E

**Comment by lazyjonez** [comment]
> Don't think I need to send commands to it - if it loads it'll work ;)

i got the same error as Spiralfive and also the Integration was renamed in the UI to config yaml as you can see in one of the photos.

Thanks for your efforts and let us know how it goes.

![D75DB710-9C3B-4639-83A4-F06113A55623](https://user-images.githubusercontent.com/6539001/173220979-446718ae-bf18-4ebb-9058-d7183ea8c6e9.jpeg)
![09FEA740-7DA4-453A-9209-7E6F53995263](https://user-images.githubusercontent.com/6539001/173220980-52961344-c0c8-4872-9afe-d652fed4fe8c.jpeg)

**Comment by MTrab** [comment]
@lazyjonez the reason for the rename is because it was imported from your configuration.yaml, so that is as expected.

As for the missing device - that's the same for everyone.
That part I have fixed in my dev-environment, but I'm having a battle with mapping the services correct, so rewriting the whole service-add-function from scratch, to comply with the current guidelines.

**Comment by MTrab** [comment]
FINALLY think I got it sorted with matching service calls to the correct device 😄 
Now I just need to test it thoroughly and fix the last small known bug 🙂

**Comment by HKUser1** [comment]
Ok as i understand that right I only have to patiened and if you has fixed the last bugs,my second Landroid will work too.
If i can do something to help you,  let me know I Have one Landroid 2019 and one 2021 Size L

**Comment by MTrab** [comment]
Correct - it will be fixed in the next release. Have had a sh*t load of bugs with mapping the services correct.
But I'm getting close to the target now.

**Comment by MTrab** [comment]
Just a small update, so you don't think nothing is happening.
Got the discovery of multiple mowers in an account sorted 🎊 
Then I noticed some strange thing happen in the mapping from service <-> device, forcing me to rewrite the whole service registration section.
Now I see some excessive spamming of the MQTT endpoint resulting in temporary bans, which I'm currently tracking down.

A version 2.1.0 will be released as soon as I got this MQTT issue sorted.

Sorry about the long wait - my day-job takes up way too much of my sparetime for being a neard and coding HA integrations 😁

**Comment by MTrab** [comment]
FINALLY everything seems sorted.
Unfortunately the new release, which is coming up shortly, **_WILL_** bring new breaking changes.
Had to rewrite huge chunks of the code, to fix these issues and keep compatibility between the different brands.

@Barma-lej need to do some work again (sorry), for the HALandroid package to function with version 2.1.0

**Comment by arcano81** [comment]
Credentials sent to your email!
Waiting for bug fixes 😀😀

Thankyou!
----------------------------------------------------------

Alessandro Rondelli



Il giorno mar 7 giu 2022 alle ore 09:31 Malene Trab <
***@***.***> ha scritto:

**Comment by MTrab** [comment]
This is an old, closed issue.
This have been resolved months ago.

Other than that, nothing received.
