### ISSUE TITLE
Cannot add second mower

### ISSUE THREAD

**Issue by InvertedMinor** [MTrab/landroid_cloud#147]
### Environment:
- Home Assistant version: 2023.6.1
- Landroid_cloud version: 2.0.3
- Operation system: OS 8.1

## Describe the bug
I have two landroids, now only one is recognised by you wonderful piece of software: WR141E but the other WG796E.1 is not visible. Both mowers have the latest firmware. Both were visible in the previous version

## Debug log

There is no info on this  WG796E.1 in the logs

```

**Comment by MTrab** [comment]
Same as #146
