### ISSUE TITLE
Multiple integrations...?

### ISSUE THREAD

**Issue by larronni** [MTrab/landroid_cloud#148]
Environment:

- Home Assistant version: 2022.6.1
- Landroid_cloud version: 2.0.3

## Describe the bug

It looks like the integration has "multiple integrations" in device overview. It seems that both (for my part) TP-link Deco and Landroid Cloud integration is using this device.
![image](https://user-images.githubusercontent.com/49139069/171836750-b73465bb-d5c1-4f5f-b33a-b9b1f6c6b6a6.png)

When checking the device, it also comes up with the "wrong" integration Icon. It looks like the integrations comes from TP-link...
![image](https://user-images.githubusercontent.com/49139069/171836854-608ca87d-8823-4512-a5ee-48e25f988f4e.png)

.....

Could this be the solution for this issue? : https://developers.home-assistant.io/docs/creating_component_generic_discovery/

**Comment by MTrab** [comment]
A wild guess would be that you have TP-Link wifi integrated, so it matches the MAC address.
This isn't a bug in landroid_cloud - I have no idea to what priorities Home Assistant have for integrations.

And the link you provided refers to multiple platforms (vacuum, button, sensor ...) and not multiple integrations.

**Comment by larronni** [comment]
So this is how HA handles multiple devices with the exact same identification (serial number, mac address, etc)? Therefore, the "bug" is in the HA Core, not an integration issue?

**Comment by MTrab** [comment]
Wouldn't put my head out to say it's definetely not an issue with this integration - BUT ..... have seen this issue between several of the integrations used in my own Home Assistant.
Ie. Unifi and Shelly does the same.
