### ISSUE TITLE
Translate API to use in Postman

### ISSUE THREAD

**Issue by Hickori** [MTrab/landroid_cloud#149]
Hi!

I have an ASP.NET home controller that Ive made myself, and I would like to integrate this API in my project. But as a first step I want to test and use it in Postman, I am trying to get the authentication token but I cannot seem to authenticate, I get the response 401. Ive tested about everything I can find, but maybe you know how the authecntication is build? Heres my Postman setup:
![image](https://user-images.githubusercontent.com/63020318/172071793-3e698185-111e-446b-a393-2d41eb4020ab.png)

**Comment by Hickori** [comment]
I also have this but I need my authorization bearer token from the post above from what Ive read:
![image](https://user-images.githubusercontent.com/63020318/172071813-ee498bd3-c8be-48c0-ae30-f0f40798afc9.png)

**Comment by MTrab** [comment]
You should rather take a look at https://github.com/mtrab/pyworxcloud, as that's where all the magic is happening - it's not in this integration ;)

**Comment by Hickori** [comment]
Holy moly, thank you so much!!!
