### ISSUE TITLE
[FR]: Add Poll command

### ISSUE THREAD

**Issue by S-E-B-123** [MTrab/landroid_cloud#152]
Would it be possible to add the "poll" command again?
I used it with the 1.xx version with great success. 
My landroid was not able to reach its charging station in some cases, because the battery was too low for the entire distance. I found the following solution:
With Home assistant  and Node Red I was able to monitor the battery level with normal API updates. if the level was under a defined threshold I sent the poll command every minute and could send the landroid home if a second battery threshold was reached. With this construct the battery problem was fixed and my landroid was able to reach its charging station every time. The rate limit reliably prevented a ban from the worx cloud api.

**Comment by MTrab** [comment]
Poll is no longer nessecary, as we now subscribe to the API events of Landroid Cloud.
So states are available in the integration as soon as there is a new state at the API.

**Comment by S-E-B-123** [comment]
Yes, but i think this is the problem. 
Not every change of battery level will send a API event. It seems that such events will be send after a defined time, or if a special event will occur.
If i send the poll manually from Eisha's DeskApp, the current battery level will be updated within the API.
This is the reason, why it would be nice to add the "poll"-command again.

**Comment by MTrab** [comment]
The device will return when battery state is low, this shouldn't be handled by Home Assistant in the first place.
Again - we have no use of the poll anymore, as the data is updated when the device is pushing updates.
And excessive use of the poll method will put you in risk of being banned.
