### ISSUE TITLE
Multi Zone Debugging on v2.x

### ISSUE THREAD

**Issue by Johnson145** [MTrab/landroid_cloud#161]
### Environment:
- Home Assistant version: 2022.6.5
- Landroid_cloud version: 2.0.3
- Operation system: HAOS

## Describe the bug
As a follow up of #112, I upgraded your package to the new major version to test multi zone configuration. It's somewhat working, but still quite buggy. I spent some time debugging on what is working and what not. Most testing was done by using the latest version of the [halandroid Lovelace card](https://github.com/Barma-lej/halandroid) and not triggering the services directly. I mainly want to share my findings to hopefully save other folks some time. In case my input is actually good enough to help you fixing things, great! In case this is too broad (don't got a specific config or logs), feel free to close the issue.

- setting the next zone from the UI somewhat works after the major update
- setting the zone starting points from the UI does NOT work in the first place (not tested via service yet). Values are saved in the UI, but the mower still uses the ones previously configured in the app.
- at least after the initial setup, the next zone setting is ignored from the UI. it started working after explicitly toggling the "enable multi zone" switch in the UI. may sound obvious, but I didn't pay attention to this toggle, as multi zones have been enabled in the app already
- app and home assistant ui don't seem to sync the zone starting points or probabilities (neither the enable/disable, see previous bullet point). as of now, it does not seem to work in either or direction, i.e. neither when making changes in the app nor when making changes in home assistant. I think you mentioned this somewhere in the Home Assistant forum already, but for one direction only.
- zones which have a probability of 0% will get ignored when manually set as the next zone (probably desired behavior, but I thought it may allow to temporarily override the general probability distribution)

**Comment by MTrab** [comment]
Most of what you write here are not related to the integration, but the halandroid package not reading the attributes provided.

As for this:
`zones which have a probability of 0% will get ignored when manually set as the next zone (probably desired behavior, but I thought it may allow to temporarily override the general probability distribution)`
That is pr. design. Zones with 0% probability are ignored.
