### ISSUE TITLE
Status refresh

### ISSUE THREAD

**Issue by Farfar** [MTrab/landroid_cloud#164]
In the official landroid app you can refresh data from mower with a "pull-down" action.
Is there a way to implement this refresh in the integration?

**Comment by MTrab** [comment]
At the moment - no. Users got banned for excessive use of the function, so I removed the possibility.
And it shouldn't be of any issue, as version 2 of the integration subscribes to events, so as soon as the robot sends a new state, then Home Assistant reflects this.

**Comment by Farfar** [comment]
> At the moment - no. Users got banned for excessive use of the function, so I removed the possibility. And it shouldn't be of any issue, as version 2 of the integration subscribes to events, so as soon as the robot sends a new state, then Home Assistant reflects this.

Thanks, suspected that there might be a reason for it not being present since the integration is so full of features!
Thanks for prompt reply and a great integration 👌🏻
