### ISSUE TITLE
Error in Authentication

### ISSUE THREAD

**Issue by dac21** [MTrab/landroid_cloud#17]
Since the latest upgrade v1.3.4, I am getting the below error.  I checked the password in Landroid and it is correct.  I also uninstalled and reinstalled and still am getting the same issue.

![image](https://user-images.githubusercontent.com/35934973/80367806-b5b18b80-8859-11ea-8127-52ec2b269b5c.png)

**Comment by MTrab** [comment]
Please check you have specified same email and password as used in the Landroid App

**Comment by dac21** [comment]
Verified it is the same password and email address.  I just rebooted my PI in addition to HA and it is now working. Thanks Dennis Sent from Mail for Windows 10 From: Morten TrabSent: Monday, April 27, 2020 4:26 PMTo: MTrab/landroid_cloudCc: dac21; AuthorSubject: Re: [MTrab/landroid_cloud] Error in Authentication (#17) Please check you have specified same email and password as used in the Landroid App—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
