### ISSUE TITLE
No GPS Location available after Update 

### ISSUE THREAD

**Issue by Subbilein** [MTrab/landroid_cloud#174]
After updating the Integration, my landroid is not availabe for Geo location. 
Before updating to v2.1.0, the vacuum entity was shown on the map card of HA.

**Comment by MTrab** [comment]
Hmmm - code looks okay. Unfortunately my own mower doesn't support GPS location.

Would it be possible to lend access to your account, to see whats going on?
You can send the credentials to github_2022(at)trab.dk

**Comment by Subbilein** [comment]
I think I found the problem.
The format of the attributes of the vacuum entity has changed:
Before it was:

latitude: x.xxxxxx
longitude:  x.xxxxxx

now it is:

location:
   latitude: x.xxxxxx
   longitude:  x.xxxxxx

same with the error attribute.
It also changed its format into more then one row:

error:
  id: 0
  descriptopn: no error

I hope these infos can help.

**Comment by MTrab** [comment]
Okay - that is expected behavior, as huge parts of the code have been rewritten.

**Comment by Subbilein** [comment]
okay, then the map card seems to need these two seperate attributes (latitude and longitude) to identify the entity as an entity with geo location.
but the two attributes are indented in the code, so they are probably not recognized.

**Comment by MTrab** [comment]
Guess you are right.
Will consider moving them back to the "root" of the attributes for the next release

**Comment by Subbilein** [comment]
Many thanks!
Will these changes come with the next Update?

**Comment by MTrab** [comment]
Yes it will
