### ISSUE TITLE
Sensors stuck in "Initializing"

### ISSUE THREAD

**Issue by thedoginthewok** [MTrab/landroid_cloud#18]
![grafik](https://user-images.githubusercontent.com/6908247/80383930-85430f00-88a4-11ea-8869-6d719633a5d2.png)

After updating to 1.3.4 the sensors for my mower continously show "Initializing" as value.

Weirdly enough, after trying to downgrade back to 1.3 and 1.2 I could not get it to work again. 
With 1.3.0 to 1.3.3 my hassio installation wouldn't boot.

log:
`2020-04-27 17:11:41 WARNING (SyncWorker_15) [custom_components.landroid_cloud.sensor] No data received for sensor.landroid_alfons_error
2020-04-27 17:11:41 WARNING (SyncWorker_8) [custom_components.landroid_cloud.sensor] No data received for sensor.landroid_alfons_status
2020-04-27 17:11:52 WARNING (SyncWorker_6) [custom_components.landroid_cloud.sensor] No data received for sensor.landroid_alfons_battery
2020-04-27 17:11:52 WARNING (SyncWorker_5) [custom_components.landroid_cloud.sensor] No data received for sensor.landroid_alfons_error
2020-04-27 17:11:52 WARNING (SyncWorker_12) [custom_components.landroid_cloud.sensor] No data received for sensor.landroid_alfons_status`

I can still communicate with the mower with the app. Maybe this has nothing to do with this custom component.

**Comment by MTrab** [comment]
I think it's cloud issue - my app doesn't work either, and a program I have for a PC doesn't work either.

**Comment by thedoginthewok** [comment]
That seems likely

**Comment by parisiantony** [comment]
Same problem here.
Sensors stuck initializing and can't manage the mower from the app.
Also, the information is refreshed slowly in the app.
Can you solve or have more info about this problem?
Thanks.

**Comment by MTrab** [comment]
As this is cloud, it's out of my hands. We need Worx to solve this issue.
That said, I might have found an alternate way to get sensor data when this happens (same data as app shows when mower is out of coverage)
Working on that right now - unfortunately this method does NOT provide any means to control the mower, for that we need the cloud to be accessible and working.

**Comment by MTrab** [comment]
Should be fixed in v1.4

But please note this does NOT fix the issue where mowers can't be started/stopped by the service calls, when the cloud is offline or acting up.

And do please note the breaking change!
