### ISSUE TITLE
Patrymode service not working

### ISSUE THREAD

**Issue by yolani** [MTrab/landroid_cloud#183]
### Environment:

- Home Assistant version: 2022.6.7
- Landroid_cloud version: 2.1.3
- Operation system: Docker

## Configuration

...

## Describe the bug
I have a landroid WR165E / M500+, since the last updates to 2.x, calls to the service  landroid_cloud.partymode fail, in the logs I get

```text

(Rasi, Service Call) The called service, partymode, is not supported by this device!

```

This is wrong, my landroid supports party mode, also the service used to work before 2.x.

**Comment by MTrab** [comment]
Same as https://github.com/MTrab/pyworxcloud/issues/50
