### ISSUE TITLE
No GPS data available

### ISSUE THREAD

**Issue by Subbilein** [MTrab/landroid_cloud#187]
After Update to 2.1.4. there are no attributes for latitude and longitude in the vacuum entity.

**Comment by MTrab** [comment]
More info please, and perhaps a screenshot of all attributes, as this issue should be fixed with the release of 2.1.4

**Comment by Subbilein** [comment]
battery_level: 100
battery_icon: mdi:battery-charging-100
accessories:
  cellular: true
  ultrasonic: true
battery:
  cycles:
    total: 110
    current: 0
    reset_at: null
    reset_time: null
  temperature: 28.4
  voltage: 19.59
  percent: 100
  charging: false
blades:
  total_on: 14910
  reset_at: 0
  reset_time: null
  current_on: 14910
error:
  id: 0
  description: no error
firmware:
  auto_upgrade: true
  version: 3.26
locked: false
mac_address: 98D86344XXXX
model: Landroid M500
online: true
orientation:
  pitch: 1.2
  roll: -0.5
  yaw: 276.6
rain_sensor:
  delay: 180
  triggered: false
  remaining: 0
schedule:
  time_extension: 0
  active: false
  auto_schedule:
    settings: {}
    enabled: null
  primary:
    monday:
      start: '09:00'
      end: '11:00'
      duration: 120
      boundary: true
    tuesday:
      start: '09:00'
      end: '11:00'
      duration: 120
      boundary: false
    wednesday:
      start: '09:00'
      end: '11:00'
      duration: 120
      boundary: false
    thursday:
      start: '09:00'
      end: '11:00'
      duration: 120
      boundary: false
    friday:
      start: '09:00'
      end: '11:00'
      duration: 120
      boundary: true
    saturday:
      start: '09:00'
      end: '11:00'
      duration: 120
      boundary: false
    sunday:
      start: '09:00'
      end: '11:00'
      duration: 120
      boundary: false
  secondary:
    monday:
      start: '00:00'
      end: '00:00'
      duration: 0
      boundary: false
    tuesday:
      start: '00:00'
      end: '00:00'
      duration: 0
      boundary: false
    wednesday:
      start: '00:00'
      end: '00:00'
      duration: 0
      boundary: false
    thursday:
      start: '00:00'
      end: '00:00'
      duration: 0
      boundary: false
    friday:
      start: '00:00'
      end: '00:00'
      duration: 0
      boundary: false
    saturday:
      start: '21:00'
      end: '22:00'
      duration: 60
      boundary: false
    sunday:
      start: '00:00'
      end: '00:00'
      duration: 0
      boundary: false
serial_number: 20193019XXXXXXXXXXXX
status_info:
  id: 1
  description: home
time_zone: Europe/Berlin
zone:
  current: 0
  index: 0
  indicies:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
  starting_point:
    - 0
    - 0
    - 0
    - 0
capabilities:
  - Edge Cut
  - One-Time-Schedule
  - Party Mode
  - Motor Torque
mqtt_connected: true
supported_landroid_features: 7167
party_mode_enabled: true
rssi: -80
statistics:
  worktime_blades_on: 15095
  distance: 256846
  worktime_total: 15932
torque: 0
state_updated_at: '2022-07-03T20:21:43+02:00'
device_class: landroid_cloud__state
friendly_name: Lanny
supported_features: 12500
icon: mdi:robot-mower

**Comment by MTrab** [comment]
Strange - just moved the attribs back to the root level.
Will take revisit this today thou, to see where it goes wrong.
