### ISSUE TITLE
edgecut does not work after update to v2.1.3

### ISSUE THREAD

**Issue by sashgithub** [MTrab/landroid_cloud#194]
- Home Assistant version: 2022.6.6
- Landroid_cloud version: 2.1.3
- Operation system: Home Assistant Container 

## Configuration

Configuration about Add Integration - landroid cloud 

## Describe the bug

Logger: custom_components.landroid_cloud.services
Source: custom_components/landroid_cloud/utils/logger.py:126
Integration: Landroid Cloud ([documentation](https://github.com/MTrab/landroid_cloud/blob/master/README.md), [issues](https://github.com/MTrab/landroid_cloud/issues))
First occurred: 21:09:29 (2 occurrences)
Last logged: 21:09:56
(S, Service Call) The called service, edgecut, is not supported by this device!

I have landroid WR130E

Bevor update to version 2.1.3 the service edgcut working without any issue. 
(I have the edgecut and party mode in my landroid app.)
I had deinstall, uplink landroid and install integration new, linked the landroid new, but no changes. The issue still the same.

I hope the issue can be solved, because i use this service by my automations.
Thank You for any help. I love this integration.

**Comment by MTrab** [comment]
Please update to 2.1.4 and see if that doesn't fix the issue

**Comment by sashgithub** [comment]
I updated to 2.1.5 and the issue is fixed. edgecutting ist still working again.
Thank you.
