### ISSUE TITLE
landroid_cloud.torque service does not seem to have any effect

### ISSUE THREAD

**Issue by prof7bit** [MTrab/landroid_cloud#203]
### Environment:
- Home Assistant version: 2022.7.3
- Landroid_cloud version: 2.2.0
- Operation system: HAOS
- Landroid Mower: M700 Plus, V3.26

### Description

I can see in the device status the torque attribute that my torque is currently set to -20. I did this a few weeks ago with the DeskApp, this is correct and it also means My Landroid M700-Plus, V3.26 supports this feature. 

Today I decided I want to try -25 and because I have seen there is a torque adjustment service I tried to use the home assistant integration instead of the DeskApp to adjust the torque.

- I went to developer tools | services
- I search for and select landroid_cloud.torque
- I select my landroid as device (did also try with entity, makes no difference)
- I check the box and move the slider to -25 
  (did also try zero, just in case there is a problem with negative numbers, didn't work either)
- I click "execute service"
- I see a green checkmark (indicating success?)

Now I go back to the developer tools | states and refresh the display, I see that the torque attribute is still unchanged at -20. I wait 10 minutes until the next state update, still nothing. I also used the new "refresh" service to force state update, I repeated this procedure multiple times to make sure I am looking at an updated state *after* my service call, I even reloaded the integration itself to get a completely fresh state, but the torque did not change. I also tried other services like toggle party mode, just to make sure my general approach to calling these services and examining their effect is correct:

Changing the party mode is working, I see the state update immediately, reflecting the new setting. 
Torque adjustment has no effect, I also see no state update after calling this service.

**Comment by MTrab** [comment]
This relates to #201

**Comment by patrickse** [comment]
I’ve tried the torque service and it seems like it still has no effect for me. 

- call torque service using dev tools and set torque to 20% (positive value)
- Check the attributes of my robot entity
- Torque is still 0

I haven’t modified the torque parameter in anyway up to now. Can anyone confirm that it’s working now?

**Comment by mdkeil** [comment]
Don't work for me too. Changing the torque parameter with the windows desktool works like a charm.

**Comment by MTrab** [comment]
Okay - need to see if any of the mowers I have access to supports setting torque, so I can test this.

**Comment by MTrab** [comment]
Do you see any errors in the log?

**Comment by patrickse** [comment]
Nope.. checked the logs after calling the service.. and there´s no hint.

**Comment by prof7bit** [comment]
2.2.2 update today fixed the torque problem.

**Comment by MTrab** [comment]
As expected ;)
