### ISSUE TITLE
Zone mapping not matching when selecting new zone

### ISSUE THREAD

**Issue by MTrab** [MTrab/landroid_cloud#208]
![image](https://user-images.githubusercontent.com/14296463/179460715-a9f958f0-2d52-48f7-b064-1705555f9ec9.png)
![image](https://user-images.githubusercontent.com/14296463/179460810-03d49787-948d-4aa6-ac26-48fdc48b35f4.png)

your attributes
![image](https://user-images.githubusercontent.com/14296463/179460837-a57daf99-29ea-467f-9cd6-d8b7f4b0122e.png)
 
Now we have  actual „1“ ≙ Worx landroid app Zone 2:
![image](https://user-images.githubusercontent.com/14296463/179460862-f750d2e8-1422-400d-8b33-a85937037e2c.png)

Now i have called service: zone 0 ≙ Worx landroid app Zone 1  = OK
![image](https://user-images.githubusercontent.com/14296463/179460883-f56c01dd-f43a-4267-8ddc-9a58932f3075.png)

Now i have called service: zone 1 ≙ Worx landroid app Zone 2  = nok
![image](https://user-images.githubusercontent.com/14296463/179460910-21524a11-21ba-4a0f-b55f-0465d641235b.png)

Now i have called service: zone 2 ≙ Worx landroid app Zone 3  = nok
![image](https://user-images.githubusercontent.com/14296463/179460980-a32447e4-e44e-4696-ad66-40828dc24e33.png)
![image](https://user-images.githubusercontent.com/14296463/179460987-94bcfabc-4b12-45fd-b3d1-d549d33c67e8.png)

But if I change here, inside this app,then it‘s working too:
![image](https://user-images.githubusercontent.com/14296463/179461017-9871b384-e4ae-455a-88cd-3265a02cdc0c.png)

Use: The set series of start point numbers is displayed in the Zone_Sequence field.
The Ruler field contains a kind of ruler that saves you from counting the elements of this row.
The current pointer to the starting point for the next mowing action is visualized in the Current_Zone_Pointer field.
The starting point number can now be selected in the New_Zone_Index field
to be pushed "under the pointer" by the plugin. This process is started by pressing the DoIt button.

I hope ist help you too

**Comment by infohannes** [comment]
Hello Malene,
I've now tested your new version 2.2.2 but it didn't really fix this problem.
the zone index is not set correctly. You know my configuration above.
I have this configuration:
Zone 0 = 70%
Zone 1 = 20%
Zone 2 = 10%
This created mzv: [0,1,2,0,1,0,0,0,0,0] = Zone_sequence is now static and can't be changed.
What I have understand, that we have only the possibility, to put this sequence under the next index.
In the example is the index 4 and will be start mowing normally at zone 1.
e.g. But now I will cut at zone "0":
here we have 7 posibilities to set to zone "0"

![grafik](https://user-images.githubusercontent.com/69587436/179822758-a1de50a7-cb1e-428f-85ff-f8e429d04c17.png)
You can send the rule from actual index (new_zone _Index) = "0":
![grafik](https://user-images.githubusercontent.com/69587436/179823322-8b504019-ffbd-41ef-9aa6-fd073b3f648a.png)

**Comment by MTrab** [comment]
Sorry, I don't see the problem. 
In my tests on your account, the fix works exactly as intended, setting the next index (index+1) to the requested zone?!

**Comment by MTrab** [comment]
Can you try to describe exactly what you do, what the outcomes is and what the expected outcome would be?

And if you feel it's too hard to do in English, the please do it in German (which I expect would be your native language)

**Comment by infohannes** [comment]
Hi,

The easiest way for me is, to show you it in a team viewer remote sec.

Today evening or when you have time?

**Comment by MTrab** [comment]
Just did a quick debug of the setzone code - and as far as I can see it's doing excactly what you want.

![image](https://user-images.githubusercontent.com/14296463/179905879-e131ee34-6d4e-4666-9cf6-cee91d5ee286.png)

**Comment by infohannes** [comment]
I test it today 🙋‍♂️

Mail from Dirk’s mobil
