### ISSUE TITLE
Documentation on adding to Lovelace (suggestion to create package similar to Halandroid)

### ISSUE THREAD

**Issue by rosscullen** [MTrab/landroid_cloud#21]
Great work so far @MTrab ... would you consider creating a package similar to this one? https://github.com/Barma-lej/halandroid

At present, I'm finding it challenging to differentiate the entities from my previous Hanlandroid install and the entities create by landroid_cloud. Please could you add lovelace documentation to your readme please?

Thanks and keep up the good work!

**Comment by rosscullen** [comment]
Just submitted pull request for small addition to readme. Hope its of some use. Thanks

**Comment by MTrab** [comment]
Perfect - thank you 👍

**Comment by MTrab** [comment]
https://github.com/Barma-lej/halandroid have been adapted to use this integration.
