### ISSUE TITLE
Detected I/O inside the event loop

### ISSUE THREAD

**Issue by thedoginthewok** [MTrab/landroid_cloud#23]
Additional Info: [Release Notes 109](https://www.home-assistant.io/blog/2020/04/29/release-109/#detection-of-blocking-io-in-the-event-loop)

`2020-04-29 21:01:10 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for landroid_cloud doing I/O at custom_components/landroid_cloud/__init__.py, line 216: self._client.getStatus()`

**Comment by MTrab** [comment]
Been trying for a long time, to get some help for setting up async correctly for Home Assistant - but none of the devs are reacting unfortunately :( Never worked with async in Python before, so right now it trail'n'error (up until now only error).

So when this will be fixed I cannot say - but it's VERY high on my todo list.

**Comment by thedoginthewok** [comment]
You're doing a great job!

I would have helped, but I have no python experience.

**Comment by MTrab** [comment]
Thank you - doing my best, learning Python alon the way :D

.NET nerd myself ;)
