### ISSUE TITLE
Integration failed to initialize.

### ISSUE THREAD

**Issue by MadsALarsen** [MTrab/landroid_cloud#24]
i have a problem after reinstall off home assistant due to other issues I get this error 

"Logger: homeassistant.setup
Source: setup.py:191 
First occurred: 9.40.55 (1 occurrences) 
Last logged: 9.40.55

Setup failed for landroid_cloud: Integration failed to initialize."

"Invalid config
The following integrations and platforms could not be set up:

landroid_cloud
Please check your config.

"

tried to remove, reinstall & restart between everything 

🤷🏻‍♂️🤷🏻‍♂️🤷🏻‍♂️

**Comment by MTrab** [comment]
Please share your configuration for landroid_cloud

**Comment by MadsALarsen** [comment]
landroid_cloud:
  - email: !secret mail
    password: !secret worx
  - email: !secret sandet
    password: !secret butik
  

Det virkede på 0.109 igår inden jeg ominstallerede den men nu brokker den sig bare 🤷🏻‍♂️

**Comment by MTrab** [comment]
Tænker det er et lokalt problem - kan ikke genskabe det, heller ikke på en helt ren HA.

**Comment by MadsALarsen** [comment]
Ok jeg prøver igen senere med en konto af gangen 👍🏻 Så må vi se om jeg kan få det til st virke da jeg ikke har inhaleret noget nyt andet en 0.109.2

**Comment by Barma-lej** [comment]
i have the same problem

**Comment by johnhughbowen** [comment]
Did this ever get resolved, I have the same issue

**Comment by rosscullen** [comment]
The person didnt reply to say so its assumed they got sorted. This issue is closed so i would advise creating a new issue with details such as:
- Home Assistant version
- Hardware
- Landroid model
- Is it working ok on landroid native app
- Copy of your configuration.yaml
- Manual install or via HACS

all the best!

**Comment by johnhughbowen** [comment]
Hi Ross

Wow, thanks for replying so quickly.
I, will open up a conversation now

Kind Regards

John

*John Bowen | Managing Director - MediaConcepts Pte Ltd | T. +65 3138 3829
| M. +44 (0)7446760120 | ***@***.**** ***@***.***>

*Blk 2 Balestier Road, #04-661, Singapore 320002 This email message and any
accompanying attachments may contain information that is confidential and
is subject to legal privilege. If you are not the intended recipient, do
not read, use, disseminate, distribute or copy this message or attachments.
If you have received this message in error, please notify the sender
immediately and delete this message. Any views expressed in this message
are those of the individual sender, except where the sender expressly, and
with authority, states them to be the views of MediaConcepts. Before
opening any attachments, please check them for viruses and defects.*
