### ISSUE TITLE
error trying to configure

### ISSUE THREAD

**Issue by sscastor115** [MTrab/landroid_cloud#244]
States "Landroid Cloud is being setup" and then errors with "Config flow could not be loaded: undefined" and closes 

Home Assistant 2022.8.2
Supervisor 2022.07.0
Operating System 8.2
Frontend 20220802.0 - latest

**Comment by spiralfive** [comment]
![1BBB03C1-1F0C-42BB-96F1-2E4B871DB007](https://user-images.githubusercontent.com/26095643/183793395-6491f0de-9949-4a55-b44a-2ed6485b4b01.png)

I am seeing this behavior as well - though my error is slightly different. This may be a different issue.  I’m on my phone at the moment, but am attaching a screenshot of the error. I have been getting around this by restarting Home Assistant. This has been happening for at least a couple of days, I just thought something was wrong with the connection to the Worx Cloud.

**Comment by MTrab** [comment]
Are you on the latest version?

**Comment by spiralfive** [comment]
Disregard my comment - I haven’t had this happen since I posted that, though it happened several times before that. 

I think something else was wrong. I did recently update everything, HA and this integration, but my errors stopped before doing that.

**Comment by dave-prosee** [comment]
Slightly different configuration flow error.
When adding/configuring the Landroid cloud integration I get the following error after submit of my email and password:

_This error originated from a custom integration.

Logger: custom_components.landroid_cloud.config_flow
Source: custom_components/landroid_cloud/utils/logger.py:126 
Integration: Landroid Cloud (documentation, issues) 
First occurred: 21:44:27 (1 occurrences) 
Last logged: 21:44:27

(Config) Unexpected exception:_

My configuration information:
"installation_type": "Home Assistant OS",
    "version": "2022.8.6",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "armv7l",
    "timezone": "Europe/Amsterdam",
    "os_name": "Linux",
    "os_version": "5.15.32-v7l",
    "supervisor": "2022.08.3",
    "host_os": "Home Assistant OS 8.4",
    "docker_version": "20.10.14",
    "chassis": "embedded",
    "run_as_root": true

Landroid cloud version: v2.3.1

Hope this is enough info, else let me know. Thanks.

**Comment by MTrab** [comment]
Is that the actual error from the log?
Never seen an error expressed like that - no idea what that could be.

**Comment by MTrab** [comment]
Closing as there have been no further reports or reactions to this.
