### ISSUE TITLE
Incorrect error reported

### ISSUE THREAD

**Issue by fra87** [MTrab/landroid_cloud#254]
### Environment:
- Home Assistant version: 2022.8.7
- Landroid_cloud version: 2.3.1
- Operation system: Dietpi

## Configuration

Not available (configured through web interface, no lines in configuration.yaml)

## Describe the bug
The mower went to a no-wire area, so it reported the "Missing wire" error on the app.

In the logs this was reported correctly (in fact there is `'error': {'id': 3, 'description': 'wire missing'}`), but in the status the error was unknown (`error: id: -1, description: unknown`). Attached are the log (I noted the issue at about 11:05; the relevant log lines are the ones collected at 2022-09-03 11:01:09 - i.e. the second block) and the status as seen from the `developer-tools/state` webpage.

## Debug log

[log.txt - debug log](https://github.com/MTrab/landroid_cloud/files/9482298/log.txt)
[status.txt - status as seen from developer tools](https://github.com/MTrab/landroid_cloud/files/9482297/status.txt)

**Comment by MTrab** [comment]
Would rule this a local error. Running the same version in my prod HA and I'm not seeing this.

**Comment by fra87** [comment]
I retested it and I can't reproduce the issue; I'll try to monitor it, but for the moment the issue can be closed

Thank you
