### ISSUE TITLE
Some Infos missing

### ISSUE THREAD

**Issue by Marow** [MTrab/landroid_cloud#257]
- Home Assistant version: 2022.09.1
- Landroid_cloud version: 2.3.1

Any ideas why i have some infos unknown?
Like `sensor.mower_pitch` or `sensor.mower_roll ` or `sensor.mower_totaltime` 

But not all... 
My Lovelance card looks like that:
![image](https://user-images.githubusercontent.com/2269012/191911389-adcc7c4b-ae5a-4bad-9667-89be46d80e10.png)

**Comment by MTrab** [comment]
The mentioned sensors are not from this integration.
That said - what's the state of the related vacuum entity?

**Comment by Marow** [comment]
Oh yes, i see... thats from the Lovelance Card. Sorry!
