### ISSUE TITLE
Landxcape login is broken

### ISSUE THREAD

**Issue by MTrab** [MTrab/landroid_cloud#258]
Issue just for info and tracking of code-changes.

Landxcape login is as of now broken, need to investigate what have changed.
This is NOT related to the integration iitself rather the connector module: https://github.com/MTrab/pyworxcloud/issues/81

**Comment by nrpetonr** [comment]
same here

**Comment by MTrab** [comment]
Yeah - same.for all Landxcape users. Something in the API has changed

**Comment by spiralfive** [comment]
![image](https://user-images.githubusercontent.com/26095643/192408906-7cb61106-f744-4d0b-a8a3-6bc1ee11d7be.png)
I don't know if this is related, this is not Landxcape, but I just restarted my Home Assistant instance after updating to 2022.9.7 and am getting these errors now. I don't know if the upgrade or the restart/new login caused these issues.

**Comment by kepath** [comment]
> ![image](https://user-images.githubusercontent.com/26095643/192408906-7cb61106-f744-4d0b-a8a3-6bc1ee11d7be.png) I don't know if this is related, this is not Landxcape, but I just restarted my Home Assistant instance after updating to 2022.9.7 and am getting these errors now. I don't know if the upgrade or the restart/new login caused these issues.
> 
> edit: I just tried rolling back to 2022.9.6, the error persists.

I too have this problem. I will open a new github issue

**Comment by Marow** [comment]
Also for Worx login

**Comment by MTrab** [comment]
@Marow please keep the issues clean.
This is for Landxcape (but yes, they are all affected)
