### ISSUE TITLE
Worx Landroid login is broken

### ISSUE THREAD

**Issue by MTrab** [MTrab/landroid_cloud#259]
Issue just for info and tracking of code-changes.

Worx Landroid login is as of now broken, need to investigate what have changed.
This is NOT related to the integration iitself rather the connector module: https://github.com/MTrab/pyworxcloud/issues/83

**Comment by zsolti80** [comment]
unfortunately I can't log in either, I can't use the integration.

**Comment by MTrab** [comment]
Correct - EVERYONE on 2022.9.7 or later has this issue

**Comment by danielp370** [comment]
FYI - I was on 2022.8.7 and it also has the login issue (same behavior as 2022.9)

**Comment by Boeng01** [comment]
Hey Marlene, hope you can fix this soon. If there's anything one can do to support, just ask.

**Comment by MTrab** [comment]
Unfortunately my oldest son is graduating his education this week, so won't be able to find time to find the changes until at earliest in a week or so

**Comment by DocSpider** [comment]
Hey Marlene, another note if it helps: no more access via the desktop APP (Eisha DeskApp.).

**Comment by MTrab** [comment]
Has nothing to do with me, but as that program uses same URLS and auth methods, then yes 🤷🏼‍♀️

**Comment by anasiot** [comment]
same here unable to login for worx

**Comment by MTrab** [comment]
Same errorMed venlig hilsen / Regards,Malene Trab28. sep. 2022 12.42 skrev teshiburu2020 ***@***.***>:
Appreciate you are busy with Graduation things this week figured I would tag this on here, I'm having similar issues but with a different error code
This error originated from a custom integration.

Logger: custom_components.landroid_cloud
Source: custom_components/landroid_cloud/utils/logger.py:126
Integration: Landroid Cloud (documentation, issues)
First occurred: 11:30:04 (1 occurrences)
Last logged: 11:30:04

(API) Endpoint for ***@***.*** was not found.

**Comment by MTrab** [comment]
> Appreciate you are busy with Graduation things this week figured I would tag this on here, I'm having similar issues but with a different error code
> 
> ```
> This error originated from a custom integration.
> 
> Logger: custom_components.landroid_cloud
> Source: custom_components/landroid_cloud/utils/logger.py:126
> Integration: Landroid Cloud (documentation, issues)
> First occurred: 11:30:04 (1 occurrences)
> Last logged: 11:30:04
> 
> (API) Endpoint for XXXXX@gmail.com was not found.
> ```

Same error

**Comment by MTrab** [comment]
> same here unable to login for worx

As written in one of the first comments `Correct - EVERYONE has this issue`

**Comment by roofburner** [comment]
I'm able to log in at https://id.eu.worx.com/ to check my username/password.
I can not login at https://www.worx.com/customer/account/login/. This is the error I get: "The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later."
I tried resetting my password via https://www.worx.com/customer/account/forgotpassword/, but I never received an email.
Maybe there is a Worx auth server down?

**Comment by MTrab** [comment]
Nothing is down - they have moved to a new auth server

**Comment by RickieCZ** [comment]
> I'm able to log in at https://id.eu.worx.com/ to check my username/password. I can not login at https://www.worx.com/customer/account/login/. This is the error I get: "The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later." I tried resetting my password via https://www.worx.com/customer/account/forgotpassword/, but I never received an email. Maybe there is a Worx auth server down?

As i know ....
www.worx.com is dedicated for US users
eu.worx.com is for EU users

**Comment by MTrab** [comment]
Just need to sniff the changed parameters. The URL I have found already

**Comment by Makana80** [comment]
Same Issue

Logger: custom_components.landroid_cloud.config_flow
Source: custom_components/landroid_cloud/utils/logger.py:126
Integration: Landroid Cloud (documentation, issues)
First occurred: 10:30:36 (1 occurrences)
Last logged: 10:30:36

(Config) Unexpected exception:

**Comment by shawwellpete** [comment]
> Unfortunately my oldest son is graduating his education this week, so won't be able to find time to find the changes until at earliest in a week or so

Came on to see if there was an issue, found out there was. 

Congratulatiuons to your son! Mine is also graduating this year, good luck to yours in the next chapter of life.

**Comment by MTrab** [comment]
Did a little research and doesn't seem to be an easy fix, and I might need some help.
I have found that the ioBroker integrationg got fixed, unfortunately I don't speak JavaScript that well to be able to decipher what they are doing:

https://github.com/iobroker-community-adapters/ioBroker.worx/blob/master/main.js#L118

Anyone?

**Comment by ebolam** [comment]
Didn't dive too far into it, but it looks like it's sending a request to a url with a bunch of parameters (client ID and token). The response is a form. Looks the the code fills out the username/password on the form and sends it back with a header.  Then it's doing the final oauth to another url with the token from the form submittal's return.

**Comment by Zanoroy** [comment]
@MTrab I had a quick look, it doesnt appear to be too hard:

1. Create a "code_verifier" and "codeChallenge" (I'll use the names from oiBroker) by:
    - Creating an alpha numeric string of a random 64 characters
    - code_verify = base64 string of the new random string
    - codeChallenge = a SHA256 hash of **code_verify**
    
2. Make a web client request (https://id.eu.worx.com/oauth/authorize?) with the following query string variables
    - response_type=code
    - client_id=013132A8-DB34-4101-B993-3C8348EA0EBC **(this appears to be hard coded, but its possible that this is requested from worx? like an app_id)**
    - redirect_uri=com.worxlandroid.landroid://oauth-callback/ **(again: this appears to be hard coded)**
    - scope=user:manage%20data:products%20mower:pair%20mower:update%20mower:lawn%20mower:view%20user:certificate%20user:profile%20mower:unpair%20mobile:notifications%20mower:warranty%20mower:firmware%20mower:activity_log&state=-u8vt3mPPBuugVgUpr4CD53MkzsyTeKP-x528sQ8
    - code_challenge=**(The challenge code produced in step 1)**
    - code_challenge_method=S256
    - suggested_authentication_flow=login
    
The "scope" appears to be just url encoded data/value pairs in a json 'ish' format.

The above client request 'get' is sent using the headers:
accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "user-agent": this.userAgent,
            "accept-language": "de-de"
I would expect you could change the language but hey, if it works why play wth it.

The response is captured into a variable (**loginForm** in the oibroker code) and the 'form' data is extracted into json (so basically find all form objects and create a json string of all the name/values pairs). 

The form data object's email address and password fields are updated and a web client 'post' is sent to **https://id.eu.worx.com/login** with the post data is the updated 'form data'. 

The following headers are used for the POST:
            accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "content-type": "application/x-www-form-urlencoded",
            "accept-language": "de-de",
            "user-agent":  "ioBroker 1.6.7", **<- (I assume you will want to change this to something else)**

The response to the above post is captured to a variable named **codeResponse** (it shoudl be json data if not something went wrong) this is going to be used in the final step below.

The "token" is then requested by a 'post' request to **https://id.eu.worx.com/oauth/token?** with the following:
Post data (json):
              {
                client_id: "013132A8-DB34-4101-B993-3C8348EA0EBC",
                code: codeResponse.code, **<- (this is the data returned from the last post)**
                redirect_uri: "com.worxlandroid.landroid://oauth-callback/",
                code_verifier: code_verifier, **<- (created as part of step 1)**
                grant_type: "authorization_code",
              }

Sent with the following web client headers:
            accept: "application/json",
            "content-type": "application/json",
            "user-agent": "ioBroker 1.6.7", **<- (I assume you will want to change this to something else)**
            "accept-language": "de-de",

If no errors where returned, you now have the auth token. 

If you need a hand to get it into python let me know (I hate writing code in python) but I do love all the work you have put in, so I am happy to help if you need it. 

Cheers
**P.S.** All of the above steps can be manually tested using [postman ](https://learning.postman.com/) if you are so inclined.

**Comment by MTrab** [comment]
The unexpected has happend!!
I woke up to an invite from Positec (those who is behind the Landroid brand) to gain access to their private repo to see how to generate the login and how to do the communication with the backend.

I do feel a little special now - they have ALWAYS turned my requests down.

This will help me ALOT in repairing the integration. Already got the token generation sorted the right way (and not the hacky way that ioBroker uses)

**Comment by Fettkeewl** [comment]
> they have ALWAYS turned my requests down.

Haha! I bet you that the person responsible for turning you down before is a frequent user of your integration by now and is pulling their hair now that it does not work.

**Comment by MTrab** [comment]
Haha - perhaps :) But it is SO nice.

Think I'll post a quickfix for the current version and then during winter do another complete rebuild based on these new informations.

**Comment by fra87** [comment]
I'm glad they recognized the great work you are doing (and that they are supporting your efforts). After all, your work is then converted in a better user experience for their customers.

Keep up the great work 😊

**Comment by teocannata** [comment]
I updated and trying to add Landroid Cloud integration I get an error loading config flow, "undefined".
Am I the only one?

**Comment by MTrab** [comment]
Try reinstalling. Just went thru the full experience on the latest HA release without any issues

**Comment by stefxx** [comment]
Hi @MTrab, nice work! Are you willing to share what's changed? I have an integration (in dotnet) for HomeSeer and would love to learn. Thanks!

**Comment by teocannata** [comment]
> Try reinstalling. Just went thru the full experience on the latest HA release without any issues

Worked! Remove and install again. Thanks!

**Comment by MTrab** [comment]
@stefxx all changes are visible in the pyWorxCloud repo

**Comment by tomkruhlmann** [comment]
Works like a charm - U rock @MTrab

**Comment by MTrab** [comment]
As written - the code doesn't even use that one right now ;)
Just prepared the function

**Comment by roofburner** [comment]
What Lovelace card do you use? I had Landroid Cloud 2.0.3, because I used https://github.com/Barma-lej/halandroid. As I'm using 2.3.2 now, that card stopped working (as mentioned by the repo: does not work with Landroid Cloud > 2.0.3).
Do you use this https://github.com/Barma-lej/landroid-card?

**Comment by MTrab** [comment]
I use standard entity card. Nothing fancy

**Comment by moelloman** [comment]
> Do you use this https://github.com/Barma-lej/landroid-card?

@roofburner  I use the  card and it works fine.

**Comment by roofburner** [comment]
I'm trying to install the Barma-lej card, but I'm getting this error: "Custom element doesn’t exist: landroid-card."

I'm using Lovelace in YAML mode.

I have installed the custom repo of Barma-lej. It appears in my HACS - Frontend as "Landroid Cloud" (capitals, no dash, is that OK?)

I included this in my ui-lovelace.yaml (landroid-card.js is here: /usr/share/homeassistant/www/community/landroid-card/landroid-card.js)

```
resources:
  - url: /local/community/landroid-card/landroid-card.js
    type: module
```

My Landroid Cloud seems to work (@MTrab: Thx!), as the entity vacuum.mower appears in my Developer Tools

I ran a debug, but it doesn't seem to throw an error on the card setup/usage... What are my options?

**Comment by MTrab** [comment]
Go to the correct repo and ask ;) You are better off asking on Barma-Lej repo

**Comment by MTrab** [comment]
@stefxx could you please provide an email adress i can forward to Positec?

**Comment by roofburner** [comment]
@MTrab You're right! Thx again...

**Comment by moelloman** [comment]
> I'm trying to install the Barma-lej card, but I'm getting this error: "Custom element doesn’t exist: landroid-card."
> 
> I'm using Lovelace in YAML mode.
> 
> I have installed the custom repo of Barma-lej. It appears in my HACS - Frontend as "Landroid Cloud" (capitals, no dash, is that OK?)
> 
> I included this in my ui-lovelace.yaml (landroid-card.js is here: /usr/share/homeassistant/www/community/landroid-card/landroid-card.js)
> 
> ```
> resources:
>   - url: /local/community/landroid-card/landroid-card.js
>     type: module
> ```
> 
> My Landroid Cloud seems to work (@MTrab: Thx!), as the entity vacuum.mower appears in my Developer Tools
> 
> I ran a debug, but it doesn't seem to throw an error on the card setup/usage... What are my options?

I installed the new card via HACS wtihout problems. 
Have you removed the include for the old card in the configuration? 
```
homeassistant:
  packages: !include_dir_named packages
```

**Comment by roofburner** [comment]
Dear moelloman,

I have removed the old card and replaced it with the new one. To be sure, I removed "packages" line you mentioned, but it did not help. I've opened a ticket in the repo of Barma-lej...

Thx!

**Comment by danielp370** [comment]
Thanks for the fix - donated a couple of coffees :)

**Comment by zsolti80** [comment]
Thank you how he managed to solve the integration.
I am glad about him very much, the lawnmower works! I selected this type because of this mainly because it is possible to integrate.
I did not integrate the card yet,but the entity works.
Good luck in the future. Congratulations! :)
