### ISSUE TITLE
Kress login is broken

### ISSUE THREAD

**Issue by MTrab** [MTrab/landroid_cloud#260]
Issue just for info and tracking of code-changes.

Kress login is as of now broken, need to investigate what have changed.
This is NOT related to the integration itself rather the connector module: https://github.com/MTrab/pyworxcloud/issues/84

**Comment by Christian-PK** [comment]
I have had the integration for long time. Suddenly it stopped. I removed it and reinstalled. Now when i try to add the integration again i get an error. Is this the reason why? 

Denne fejl stammer fra en brugerdefineret integration.

Logger: custom_components.landroid_cloud.config_flow
Source: custom_components/landroid_cloud/utils/logger.py:126
Integration: Landroid Cloud (documentation, issues)
First occurred: 18.37.42 (1 occurrences)
Last logged: 18.37.42

(Config) Unexpected exception:

**Comment by MTrab** [comment]
Probably - Kress is currently not workingMed venlig hilsen / Regards,Malene Trab4. okt. 2022 18.41 skrev Christian-PK ***@***.***>:
I have had the integration for long time. Suddenly it stopped. I removed it and reinstalled. Now when i try to add the integration again i get an error. Is this the reason why?
Denne fejl stammer fra en brugerdefineret integration.
Logger: custom_components.landroid_cloud.config_flow
Source: custom_components/landroid_cloud/utils/logger.py:126
Integration: Landroid Cloud (documentation, issues)
First occurred: 18.37.42 (1 occurrences)
Last logged: 18.37.42
(Config) Unexpected exception:

**Comment by MTrab** [comment]
Probably - Kress is currently not working
