### ISSUE TITLE
Installation from HACS not working

### ISSUE THREAD

**Issue by gianlucaleuthen** [MTrab/landroid_cloud#265]
I tried to install Landroid Cloud from HACS Repositories. Installation itself worked and files are in the custom-component folder. After rebooting Home Assistant, the integration can't be found in "add integration list" and therefore not be configured:

<img width="219" alt="image" src="https://user-images.githubusercontent.com/72361357/193582214-3bb6f45c-b8d2-4747-984e-738f0708f8e3.png">

<img width="364" alt="image" src="https://user-images.githubusercontent.com/72361357/193582390-a1ecbfd8-1cff-4e37-bc33-8398d06eb136.png">

**Comment by MTrab** [comment]
Please confirm in HACS that it is installed (perhaps try reinstalling it) and then try another restart.

That being said - the integration is currently NOT working.

**Comment by gianlucaleuthen** [comment]
Reinstalled and restartet :

<img width="424" alt="image" src="https://user-images.githubusercontent.com/72361357/193705226-0eade154-6a0e-452e-a9a7-a0fc79969b86.png">

Still same behaviour.

Interesting is that "normally" after installing something from HACS, I'm (automatically) getting the message to restart HA. This doesn't happen with this intergration

**Comment by MTrab** [comment]
That text in the bottom - doesn't that mean download?
Then it's not installed.

You could try force refreshing your cache (CTRL+F5) when on the integrations page.

I've seen a few times where it was the solution for integrations not showing up.

**Comment by gianlucaleuthen** [comment]
Deleting cache and restart of HA solved the issue - thanks !
