### ISSUE TITLE
No updates

### ISSUE THREAD

**Issue by LGoober85** [MTrab/landroid_cloud#27]
Great work! THX
After starting HA all sensors are up to date (for both mowers), but next update is only after 30 minute. (no 5min sync)
After calling service start, pause, home or update is nothing happened. 
Service "start" was called without any error, but mower is still staying at home.
Do you have any idea where the problem may be?
HA ver 0.109.2
Thanks for help

**Comment by MTrab** [comment]
Not sure as I cannot use neither the app or this integration.

Awaiting response from Worx.

**Comment by MTrab** [comment]
Please see this issue, https://github.com/MTrab/landroid_cloud/issues/28#issuecomment-624278806 - I can confirm it's working.
