### ISSUE TITLE
Update 2.3.4

### ISSUE THREAD

**Issue by Gioway** [MTrab/landroid_cloud#273]
After updating to 2.3.4, I tried to restart homeassistant. i got this error, i am unable to restart.

Integration error: landroid_cloud - Requirements for landroid_cloud not found: ['pyworxcloud==2.1.23'].

Thank you

**Comment by copernicnic** [comment]
the same for me :-(

**Comment by Miicroo** [comment]
You probably have to update to homeassistant 2022.10, see issue #272 and this comment https://github.com/MTrab/landroid_cloud/issues/272#issuecomment-1273794888

**Comment by copernicnic** [comment]
it works. thank you

**Comment by MTrab** [comment]
Closed as this only occur when using a version of HA older than 2022.10
