### ISSUE TITLE
Refreshing issue

### ISSUE THREAD

**Issue by luzik** [MTrab/landroid_cloud#281]
My landroid app shows rain delay, but landroid_cloud shows status before rain delay - that mover is docked 
Landroid entity shows that last change, and last refresh was 15hours ago (home assistant restart). I did not found any logs corresponding landroid_cloud.
Running homeassistant.update_entity service do not refresh entity
Restarting home assistant is fixing this state ..entity is refreshed with correct status readings, and in logs I got:

```
Logger: custom_components.landroid_cloud.device_base
Source: custom_components/landroid_cloud/utils/logger.py:118 
Integration: Landroid Cloud ([documentation](https://github.com/MTrab/landroid_cloud/blob/master/README.md), [issues](https://github.com/MTrab/landroid_cloud/issues)) 
First occurred: 08:38:41 (1 occurrences) 
Last logged: 08:38:41

(Azor, Update signal) MQTT connection is offline, scheduling Web API refresh in 15 minutes. Device is in readonly mode!
```

And then it does not refresh again till home assistant restart

**Comment by MTrab** [comment]
Please supply ALL information from the issue template!

HA version, HAOS version, integration version and so on.

**Comment by luzik** [comment]
All up to date, using docker installation.
HA 10.2022, landroid_cloud 2.3.4

**Comment by MTrab** [comment]
Looks like you, for some reason, doesn't get MQTT events from the API.
The only time I've seen this is in some spooky partly banned situation, that was only solveable by removing the integration and deleting the device from the Worx app and then relinking the device again.

**Comment by MTrab** [comment]
https://github.com/MTrab/landroid_cloud#services-and-app-stopped-working
Same procedure as this

**Comment by luzik** [comment]
It did not help, `MQTT connection is offline, scheduling Web API refresh in 15 minutes ` again. And state now is 'initializing'

**Comment by MTrab** [comment]
Could you please check that you can ping the internet from your Home Assistant instance?

Something fishy is going on.

If you would be okay with it, you could share your credentials with me for further in-depth debugging - github_2022 (at) trab.dk

**Comment by luzik** [comment]
Yeah I've got multiple internet services that use internet ..all working fine. Can I provide you some access token ? Where to find it ?

**Comment by MTrab** [comment]
The token isn't of much use for getting the certificate, unfortunately.

**Comment by MTrab** [comment]
If one of you with this error would share your credentials with me on github_2022 (at) trab.dk I might be able to figure out why.
I have 2 robots running currently and haven't seen this error and cannot reproduce it neither.

**Comment by MTrab** [comment]
@oakedcorn and for you as well - please provide all information about versions and models.

**Comment by MTrab** [comment]
Initial findings is pointing towards issues with Plus models (and perhaps M500 models as well)

**Comment by oakedcorn** [comment]
@MTrab, thanks for looking into this. Here are my versions:
Raspbian GNU/Linux 11 (bullseye), kernel 5.15.30-v7l+
Home Assistant 2022.10.5 - running in docker
landroid_cloud 2.3.4
Landroid M1000 (WR143E) firmware v3.28

**Comment by luzik** [comment]
> Initial findings is pointing towards issues with Plus models (and perhaps M500 models as well)

Maybe in firmware ?
@MTrab what firmware do you have ?
WR143E is not plus version, but we share firmware version

**Comment by MTrab** [comment]
3.52 - but mine is an old S500

I have access to a new M500 which seems to have this same error, by initial looks. That one is version 3.28

**Comment by janez33** [comment]
The same issue happened to me also.
I'm on the latest Home Assistant version, my landroid is model WR155E (L2000). But everything seems to be working fine. 
![image](https://user-images.githubusercontent.com/4009092/199849372-70b64b73-c6b6-46bf-9f03-8267485c7a55.png)

**Comment by luzik** [comment]
@janez33  Please provide your firmware version, and check last entity update/refresh time (you can find it under entity details popup)

**Comment by MTrab** [comment]
This seems to be related to the recent API changes.
I'm currently working on version 3 of the pyWorxCloud connector, which is fully compliant to the API standards put out from the vendor.

**Comment by a-jey** [comment]
Got the same issue.
Sometimes it refreshes, sometimes not.
I found out that it refreshes on Home Assistant when I refresh the Landroid Android App (pulling down on main screen).

Got the M500 (Version 2019) and Firmware 3.28 beta.

**Comment by jackrats** [comment]
Version 3 please :)

**Comment by MTrab** [comment]
Version 3 will come - eventually. But all devices I can use for tests have been parked for the winter, so the development are slow mowing and have been down prioritized a bit.

**Comment by MTrab** [comment]
Will continue this in #282 as the issue is the same and will be solved when v3 is release ready shortly
