### ISSUE TITLE
Error while installing via HACS

### ISSUE THREAD

**Issue by casamontico51** [MTrab/landroid_cloud#283]
I get this error when trying to install:

Logger: homeassistant.util.package
Source: util/package.py:98
First occurred: 19:48:00 (3 occurrences)
Last logged: 19:48:23

Unable to install package pyworxcloud==2.1.23: ERROR: Cannot install pyworxcloud because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

 Home Assistant 2022.9.5 Supervisor 2022.10.0 Operating System 8.2 Frontend 20220907.2 - latest 

Thanks in advance

**Comment by MTrab** [comment]
Please update your Home Assistant to latest versions!
