### ISSUE TITLE
Component not updating 

### ISSUE THREAD

**Issue by Dielee** [MTrab/landroid_cloud#313]
### Describe the issue

First, thanks for this integration!

I have cloned your repo and installed awsiotsdk. 
Setup works well, robot info seems good, but the data isn't updating. Only "Reload component". updates the data. Also home assistant service "update entity" isn't working. 

Do you have any advice? 

### What version of Home Assistant Core has the issue?

2023.3.6

### What type of installation are you running?

Home Assistant Core

### Diagnostics information

D&D not possible on mobile, sorry. Will add this data if necessary.

### Additional information
Python 3.11

**Comment by MTrab** [comment]
Sorry - but you have to wait for the finished release. Somehow I might have messed something up in my dev environment giving false results.

**Comment by Dielee** [comment]
Yeah, no problem! Thanks for the fast response!

**Comment by Sandern88** [comment]
@MTrab is the integration currently out of service
I am getting error on initialisation of the integration 

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/api.py", line 226, in _call
    req.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.worxlandroid.com/api/v2/users/certificate

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/landroid_cloud/__init__.py", line 64, in async_setup_entry
    result = await _async_setup(hass, entry)
  File "/config/custom_components/landroid_cloud/__init__.py", line 208, in _async_setup
    await hass.async_add_executor_job(cloud.connect, False, False)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 269, in connect
    with self._get_cert() as cert:
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 324, in _get_cert
    certresp = self._api.get_cert()
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/api.py", line 135, in get_cert
    calldata = self._call("/users/certificate")
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/api.py", line 236, in _call
    raise NotFoundError()
pyworxcloud.exceptions.NotFoundError

**Comment by MTrab** [comment]
Please look at the front page

**Comment by MTrab** [comment]
Nope - currently battling HAOS not being compatible with the module needed for this to work again.

**Comment by Dielee** [comment]
I noticed that the component updates if I trigger the data update form the worx app or with 
`cloud = WorxCloud(settings.email, settings.password, "worx").update(serial_number=serial_number)`

I looked in device_base.py, but no luck...
Do you have an idea where the update command is missing in the HA integration component ?

**Comment by MTrab** [comment]
It's a complete rewrite, so just wait ;)

**Comment by MTrab** [comment]
A new pre-release has been made available

**Comment by Dielee** [comment]
Thanks for the new release. This seems to work better, but the updateintervall is a bit strange. 
When does the component update it's data ? My last data update ist more than two hours ago.

**Comment by MTrab** [comment]
Data is updated when the robot sends an update

**Comment by Dielee** [comment]
But when I'm using your `update` method, the data changes and is different from the data inside HA. So, what does the `update` do ?

**Comment by MTrab** [comment]
Send a force update request to the robot - same as forcing an update from the app.
And should not be used at all

**Comment by Dielee** [comment]
Maybe we could provide an service to force update the data from HA?

**Comment by MTrab** [comment]
That's exactly what the refresh service is for

**Comment by Dielee** [comment]
SORRY! My fault. Thank you very much. 
Do you know anything about the rate limit form the worx api ?

**Comment by roofburner** [comment]
Hi,

@Mtrab: first thanks for you effort and for bringing this integration back alive!

I can see this ticket has been closed, but I have the same issue as described.
I can see e.g. my battery level is getting updates for a while, but suddenly it stops.

![afbeelding](https://user-images.githubusercontent.com/360846/232334297-b2dbaba3-583a-4228-b88b-31ddd0b732e4.png)

I've called the "Landroid Cloud: refresh"-service on both Mower/vacuum.mower. No update.
Tcpdumping using filter "host api.worxlandroid.com" -> no packets.

Please advise...

**Comment by MTrab** [comment]
Create issue
