### ISSUE TITLE
GPS location

### ISSUE THREAD

**Issue by MuppetOwl** [MTrab/landroid_cloud#32]
I dont have the GPS module. So now my map view show the Landroid in the map, I now always have to scroll back to the correct location on the Map view. Is it possible to change so it does not add latitude and longitude option at all if it does not exist or maybe just add the Home location? :)

**Comment by MTrab** [comment]
Just noted that myself earlier today :D Will be fixed in next release.

**Comment by MTrab** [comment]
Fixed in v1.6.1
