### ISSUE TITLE
integration failed to set up

### ISSUE THREAD

**Issue by tomass0328** [MTrab/landroid_cloud#329]
### Describe the issue

integration was working fine half a year ago, but during winter season my mower was turned off. Now I have turned it on, but integration says "Failed to set up". Any advices? 

### What version of Home Assistant Core has the issue?

core-2023.4.5

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

Landroid M700

### Diagnostics information (NOT log entries!)

none

### Relevant log entries

```txt
2023-04-18 15:21:23.267 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Worx - {my@email.com} for landroid_cloud
File "/config/custom_components/landroid_cloud/__init__.py", line 64, in async_setup_entry
File "/config/custom_components/landroid_cloud/__init__.py", line 208, in _async_setup
```

**Comment by MTrab** [comment]
Which version of the integration?
Anything prior to version 3 does not work anymore (and version 3 is only available in a beta version with limited functionality)

**Comment by tomass0328** [comment]
mine is v2.3.4.
How can I get v3 beta? Or make it working in some other ways?

**Comment by MTrab** [comment]
Redownload from HACS, and mark that you want to download beta versions.
