### ISSUE TITLE
Wlan value is missing as soon as the robot drives

### ISSUE THREAD

**Issue by Cosmicbase** [MTrab/landroid_cloud#332]
### Describe the issue

Wlan value is missing as soon as the robot drive.

Look my pictures. 

### What version of Home Assistant Core has the issue?

Home Assistant 2023.4.5

### What version of the Landroid Cloud integration do you have installed

v3.0.0b4

### What type of installation are you running?

Home Assistant OS
Home Assistant 2023.4.5

### Which make and model is the mower used for this integration?

WR141E

### Diagnostics information (NOT log entries!)

![Screenshot_20230418_165933_Chrome](https://user-images.githubusercontent.com/31271212/232821953-6228d5de-985e-4a03-8d60-e688cd8b02cf.jpg)
![Screenshot_20230418_170242_Chrome](https://user-images.githubusercontent.com/31271212/232821965-4446ba65-027c-4373-ba8f-63d399a19b93.jpg)

### Relevant log entries

```txt
None
```

### Additional information

v3.0.0b4
[config_entry-landroid_cloud-e57877a56653a8711cd3d47cb9d8e633.zip](https://github.com/MTrab/landroid_cloud/files/11263556/config_entry-landroid_cloud-e57877a56653a8711cd3d47cb9d8e633.zip)

**Comment by Cosmicbase** [comment]
I have now added the diagnostic file.

**Comment by MTrab** [comment]
As far as I can see the RSSI value is present

Can you confirm it is visible in the attributes for the mower entity?

**Comment by Cosmicbase** [comment]
> As far as I can see the RSSI value is present
> 
> Can you confirm it is visible in the attributes for the mower entity?

Yes you are right, I can see the RSSI value is present in the attributes. Only in the map it is not visible.
And I saw that the RSSI value was first visible after docking and now it's not.
