### ISSUE TITLE
[FR]: blueprint for scheduling mower

### ISSUE THREAD

**Issue by cm86** [MTrab/landroid_cloud#335]
### Describe the feature you wish to make a request for

Hello
I think here is the right place for the question.
Does anyone have a working blueprint for scheduling the mower?!

### Describe alternatives you've considered

I have a huge automation running for scheduling the mower via home assistant. and of course some extra sensors/templates.

**Comment by MTrab** [comment]
Use HA community for blueprints - I do not do blueprints
