### ISSUE TITLE
Diagnostic info does not redact latitude/longitude

### ISSUE THREAD

**Issue by prof7bit** [MTrab/landroid_cloud#337]
### Describe the issue

When uploading the diagnostic info here (or elsewhere) it contains precise lat/lon and name of city. Although mine happen to be off by 20 km and I don't know when and where I entered them (I don't have GPS), someone else's might be precise and point right into their garden. I have seen some stuff is already redacted, but I feel this should be redacted too.

### What version of Home Assistant Core has the issue?

any

### What was the last working version of Home Assistant Core?

any

### What version of the Landroid Cloud integration do you have installed

v3.0.b4

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

any

### Diagnostics information (NOT log entries!)

none

### Relevant log entries

```txt
none
```

**Comment by MTrab** [comment]
Which section do you refer to?
If it's under the city information, then I think it might just be the city centre
