### ISSUE TITLE
refresh and diagnostic info button is not longer visible

### ISSUE THREAD

**Issue by Cosmicbase** [MTrab/landroid_cloud#339]
### Describe the issue

If I refresh the integration, the button for refresh and diagnostic info is no longer visible.
Please see the picture.

![Unbenannt](https://user-images.githubusercontent.com/31271212/233257209-f1e21554-12c3-41df-af3a-f773551963db.PNG)

### What version of Home Assistant Core has the issue?

Home Assistant 2023.4.5

### What version of the Landroid Cloud integration do you have installed

v3.0.0b4

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

WR141E

### Diagnostics information (NOT log entries!)

none

### Relevant log entries

```txt
none
```

**Comment by MTrab** [comment]
Please try reinstalling the integration or perhaps pressing CTRL+F5 - I still see this in both my installs.

**Comment by Cosmicbase** [comment]
I have reinstalled the integration several times. Because I have the same problem as Mower stopped updating #341 I restarted the integration. After that, the restart and diagnostic info button was gone.

**Comment by MTrab** [comment]
Is it only when seeing the issue from #341 you see these missing?

**Comment by Cosmicbase** [comment]
I think the error actually has nothing to do with #341. I only restarted the integration because error #341 was present. After restarting the integration, the button for the diagnostic info and restart was no longer visible. See the picture above.

**Comment by MTrab** [comment]
I cannot reproduce, might tend to say this is a local issue.

**Comment by Cosmicbase** [comment]
Could be. I'll watch it a little more.
