### ISSUE TITLE
Enable Border Cut - Enhancement Request

### ISSUE THREAD

**Issue by daconrad0** [MTrab/landroid_cloud#34]
I love what you have done so far. I was wondering if you had plans to enable border cut.  This would allow me to create my own schedule integrated with my sprinklers, my rain gauge and the local weather forecast.

Thanks in advance

**Comment by MTrab** [comment]
I would love to add that feature - unfortunately this is not available from the app and therefor I cannot make that available in the integration either :(

**Comment by MuppetOwl** [comment]
Send a support request to Worx, I have asked for that feature but have not heard anything back. If more people request it maybe they will add it in the future :)

**Comment by MTrab** [comment]
Way ahead of you there :D

**Comment by MTrab** [comment]
I'll close this issue as it is unfixable right now.
If by any chance, Worx is incorporating this in the app then I'll add the function.
