### ISSUE TITLE
Lost connection to Positec?

### ISSUE THREAD

**Issue by Cosmicbase** [MTrab/landroid_cloud#340]
### Describe the issue

If I want to start the mower via the card, the loading circle rotates. I have the feeling that the connection to Positic is not maintained or is interrupted after a while.
I started the mower via the app with no problems.

### What version of Home Assistant Core has the issue?

Home Assistant 2023.4.5

### What version of the Landroid Cloud integration do you have installed

v3.0.0b4

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

WR141E

### Diagnostics information (NOT log entries!)

none

### Relevant log entries

```txt
none
```

**Comment by MTrab** [comment]
Please try using the relevant service, just to rulemout another error in the card

**Comment by Cosmicbase** [comment]
The same as Mower stopped updating #341
