### ISSUE TITLE
Issues with translation

### ISSUE THREAD

**Issue by fra87** [MTrab/landroid_cloud#345]
### Describe the issue

The strings in the dashboard are not converted anymore; I'm not sure whether this is something still to be ported to the new integration or if it's just a problem I'm having

If necessary let me know which kind of logs are necessary.

As a side note, I tried to go to Lokalise to see if there were additional strings to add, but could not see the project. I performed the login, but even clicking on the link in the README.md opens the https://app.lokalise.com/projects page with the text

You have not been added to any projects yet

### What version of Home Assistant Core has the issue?

core-2023.4.5

### What version of the Landroid Cloud integration do you have installed

v3.0.0b4

### What type of installation are you running?

Home Assistant Core

### Which make and model is the mower used for this integration?

Landroid M500 WR141E

### Diagnostics information (NOT log entries!)

.

### Relevant log entries

```txt
.
```

**Comment by fra87** [comment]
You're too fast ;) now Lokalise works; I see there are no additional strings, so the old translation is still valid.

Let me know if you need something (logs, screenshots) for the dashboard translation, if there is anything that can be done

**Comment by MTrab** [comment]
I see the issue myself, but haven't gotten around to do debugging on why they are no longer applied. Probably just some simple oopsie, as they worked a week ago ;)

**Comment by fra87** [comment]
Great 😁 honestly I don't consider it a blocking problem, since even in English it is perfectly usable.

Thank you

**Comment by maartendamen** [comment]
I think it is related to this breaking change: https://developers.home-assistant.io/blog/2023/03/27/entity_name_translations/

And this issue: https://github.com/home-assistant/core/issues/90975

**Comment by MTrab** [comment]
Yeah - seems about right.
So translations need an overhaul then

**Comment by maartendamen** [comment]
I took the time this weekend to look into this issue. The impact is actually minimal, most of the work needs to be done in Lokalise. 
Here is what needs to be done:

1. Add translation_key to the base entity class. I created a pull request for that.
2. Remove the vacuum.[lang].json files.
3. Create a new entity key in the strings.json files ([lang].json), in the following format:

```json
  "entity": {
    "vacuum": {
      "landroid_cloud": {
        "state": {
          "initializing": "Initializing",
          "offline": "Offline",
          "rain_delay": "Rain delay",
          "mowing": "Mowing",
          "starting": "Starting",
          "zoning": "Zone training",
          "edgecut": "Cutting edge"
        }
      }
    }
  }
```

Here is an example of the complete new en.json file:

```json
{
  "config": {
    "abort": {
      "already_exists": "This user account have already been configured"
    },
    "error": {
      "cannot_connect": "Failed to connect",
      "invalid_auth": "Error in authentication",
      "unknown": "Unexpected error"
    },
    "step": {
      "user": {
        "data": {
          "email": "Email",
          "password": "Password",
          "type": "Make"
        },
        "title": "Connect to your Landroid Cloud account"
      }
    }
  },
  "entity": {
    "vacuum": {
      "landroid_cloud": {
        "state": {
          "initializing": "Initializing",
          "offline": "Offline",
          "rain_delay": "Rain delay",
          "mowing": "Mowing",
          "starting": "Starting",
          "zoning": "Zone training",
          "edgecut": "Cutting edge"
        }
      }
    }
  }
}
```

Most of the work was figuring out the new syntax (HA documentation is quite lacking on this topic).
Not sure if I can do the work in Lokalise, but it seems I am lacking the rights for that. Would be happy to help out though.
Hope this helps.

**Comment by MTrab** [comment]
That's right - only I can update the Lokalise base files for translation

**Comment by MTrab** [comment]
Lokalise should be up to date with the new structure now
