### ISSUE TITLE
battery state not refreshing while charging

### ISSUE THREAD

**Issue by michapr** [MTrab/landroid_cloud#346]
### Describe the issue

The battery state is not refreshing while charging - not the "%" and not the state "charging"
(while writing the report charging was over, so that I could not create the needed log, sorry)

In (Android) App I see the right state and value.

It's a very minor issue...

Thank you for your work! I'm very happy that you made it available again!

### What version of Home Assistant Core has the issue?

2023.4.4

### What version of the Landroid Cloud integration do you have installed

3.0.0b4

### What type of installation are you running?

Home Assistant Container

### Which make and model is the mower used for this integration?

L1000 (WR147E.1)

### Diagnostics information (NOT log entries!)

[config_entry-landroid_cloud-c04446e52f62cfc0edc9c404ac9f0ad6.json.txt](https://github.com/MTrab/landroid_cloud/files/11289147/config_entry-landroid_cloud-c04446e52f62cfc0edc9c404ac9f0ad6.json.txt)

### Relevant log entries

```txt
none
```

### Additional information

![beta_akku](https://user-images.githubusercontent.com/11854556/233449042-4cf35b12-e84f-4f92-a7b7-9b805efb2a90.jpg)

**Comment by MTrab** [comment]
Please check the vacuum entity directly, as I currently do not trust landroid card fully.
It works like a charm on the (now) 3 installations I have access to

**Comment by michapr** [comment]
![grafik](https://user-images.githubusercontent.com/11854556/233453872-572ca86e-624d-4eef-bc4e-9a03902095f6.png)

Not sure... battery_level: 100, but percent: 33 ?

This is MQTT from DeskApp:
![grafik](https://user-images.githubusercontent.com/11854556/233455397-4ffb56d2-c43d-44dd-a2d2-f1040062a972.png)

As I said... charging is over, will do the same while next charging tomorrow. Thanks!

**Comment by MTrab** [comment]
The percent isn't the battery as far as I remember right now ;)
Battery_level is the battery percent.

**Comment by michapr** [comment]
ok, will check it tomorrow again ;)
Anyway the temperature and voltage is strange (different), right?

**Comment by MTrab** [comment]
I'll have to verify later to give you the exact answer.
But haven't seen any issues with the battery states in any of my tests/installations

**Comment by MTrab** [comment]
Also - due to the high user requirement for data, the huge amount of attributes does make Home Assistant puke over updating attributes at times, but that is a UI issue, as a refresh (F5) will make it show the right values

**Comment by michapr** [comment]
after reloading the App (restart HA):
![grafik](https://user-images.githubusercontent.com/11854556/233466244-9d2f3c23-eccf-4996-85b3-7dde8c075f6c.png)

So... something is strange... voltage is ok now and percent 100
(was not changed before reloading)

**Comment by MTrab** [comment]
Again - look above  ;)

**Comment by michapr** [comment]
will check tomorrow - thanks!

**Comment by MTrab** [comment]
If this is what you refers to, then it's UI nothing else:

Before F5
![image](https://user-images.githubusercontent.com/14296463/233617746-a51c7967-fa98-48de-8f65-5cb893d33ffe.png)

After F5
![image](https://user-images.githubusercontent.com/14296463/233617812-fe41ceba-b063-446f-880a-b2b35d74e135.png)

**Comment by michapr** [comment]
no chance today for checking... the Landroid integration does not connect to cloud (does not refresh any state) today.
No problems with DeskApp or Android App...
(if I remember this is a known issue...)

**Comment by MTrab** [comment]
There is an issue, yes - fixed by restarting Home Assistant.

**Comment by luzik** [comment]
My landroid beta4 is not refreshing at all, I have to restart HA to get it refresh. When checking entity stats I've got both "last change" and "last refresh" 2 days ago. Is it related to that issue?

**Comment by MTrab** [comment]
Tried F5?
If that doesn't change anything, then no it's not related to this

**Comment by michapr** [comment]
You are right - battery values (and temperature etc.) will be refreshed after F5

Thanks!
