### ISSUE TITLE
Setzone not working

### ISSUE THREAD

**Issue by craig600** [MTrab/landroid_cloud#350]
### Describe the issue

The setzone service comes up with an error that the requested zone is not defined. The next zone to be mowed displays correctly on the Lovelace card. 

### What version of Home Assistant Core has the issue?

2023.1.4

### What version of the Landroid Cloud integration do you have installed

v3.0.0b5

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

Landroid M (WR149e)

[config_entry-landroid_cloud-fb29754ffa0039d06087e41de6b6c4a6.json.txt](https://github.com/MTrab/landroid_cloud/files/11303414/config_entry-landroid_cloud-fb29754ffa0039d06087e41de6b6c4a6.json.txt)

### Relevant log entries

```txt
This error originated from a custom integration.

Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/landroid_cloud/device_base.py:716 
Integration: Landroid Cloud (documentation, issues) 
First occurred: 8:48:01 PM (2 occurrences) 
Last logged: 8:49:26 PM

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: Cannot request this zone as it is not defined.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/landroid_cloud/services.py", line 146, in async_call_landroid_service
    await api.services[service][ATTR_SERVICE](service_data)
  File "/config/custom_components/landroid_cloud/device_base.py", line 716, in async_set_zone
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 682, in setzone
    raise RequestException("Cannot request this zone as it is not defined.")
pyworxcloud.exceptions.RequestException: Cannot request this zone as it is not defined.
```

**Comment by maartendamen** [comment]
Can you share diagnostics by clicking download diagnostics on the integration and share that?
I assume you are trying to set a zone that does exist? The bug report doesn't tell :-)

**Comment by Nebukadnezar2** [comment]
Hey, i have the Same issue. Is it possible to set the zones in ha?

I set them in the Worx App and you Can See the distances(startpoints)as Attributes
But iam Not able Go set them

**Comment by MTrab** [comment]
This function haven't been adapted to v3 yet, that's why ;)

**Comment by craig600** [comment]
Thanks, not being adapted would definitely explain it! I have added the diagnostics just incase it is of any use.

**Comment by MTrab** [comment]
@craig600 or @Nebukadnezar2 would one of you be comftable with sharing your account info on landroid_cloud@trab.dk to ease debugging?

As I can see the code checks out, and currently I have no access to a mower which uses zones, so I cannot debug this properly.

**Comment by Nebukadnezar2** [comment]
Sure!

You have already a Email

**Comment by gost4711** [comment]
I put my Landroid into operation today. Unfortunately I had to find out that nothing works anymore. The most important feature for me is set Zone. Without this feature, I can't use all my automation. I would be happy if there is a solution quickly.
Thank you

**Comment by MTrab** [comment]
The solution will come as soon as I have had the spare time to investigate and fix the issue.
