### ISSUE TITLE
[Question] How to get Landroid Cloud version?

### ISSUE THREAD

**Issue by mdzhigarov** [MTrab/landroid_cloud#355]
### Describe the issue

I'm trying to integrate my worx landroid wr141e into hassio. 
When I try adding the Landroid Cloud integration via HACS I get a list of supported version starting from v2.3.0+.

I am not sure which one to add. How do I know the version of Landroid Cloud I am using?
The app version on my android phone is 2.2.2 if this has anything to do with it.

### What version of Home Assistant Core has the issue?

2023.4.2

### What version of the Landroid Cloud integration do you have installed

.

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

wr141e

### Diagnostics information (NOT log entries!)

.

### Relevant log entries

```txt
.
```

**Comment by MTrab** [comment]
You can see in HACS which version you have installed.

**Comment by Phoenix-DH** [comment]
I think the question was more related to how to get the beta right?
If yes, HASCS, integration, update and then toggle the beta switch.
