### ISSUE TITLE
Feature for Multizone configuration

### ISSUE THREAD

**Issue by jukindle** [MTrab/landroid_cloud#36]
Hi! It would be really nice to have the possibility to update the multizone scheduling (the probabilities which can be set). Since there is no possibility to command the robot directly to a specific zone, my plan is to adjust the probability distribution of the zones to 100% for a specific zone before I start the robot.

I would have loved to implement it myself and do a pull request, but I was unable to figure out where the actual update request is done in decompiled smali code.

**Comment by MTrab** [comment]
Noted for future enhancement

**Comment by vistalba** [comment]
@jukindle 

May you could use NodeRed for this:

Start Landroid -> Wait 3 Seconds (or how long it takes to leave homebase) -> Pause Landroid -> Landroid Home -> Wait N Seconds (how long does it take if the Landroid is following the wire until the point you want to start mowing?) -> Pause Landroid -> Start Landroid (should begin mowing from this point)

**Comment by MTrab** [comment]
Remember - too many concurrent commands within 10 minutes will get you banned!

**Comment by jukindle** [comment]
@vistalba nice idea! However, if your robot sometimes gets stuck on its path and needs to free itself, it gets biased. As far as I know, the multizone feature uses actual wheel odometry (which is quite good) to measure distance instead of time. I'll try it anyway :) thanks!
