### ISSUE TITLE
Mower is unavailable all the time

### ISSUE THREAD

**Issue by pszafer** [MTrab/landroid_cloud#363]
### Describe the issue

Hi,

This spring season my mower is all the time unavailable.
I installed the latest beta, but no effect.
It is visible in app.
I tried to remove mower and add it again, I tried to remove integration and install it againg.
Should I enable some debug logs? Would it help?

### What version of Home Assistant Core has the issue?

2023.5.2

### What was the last working version of Home Assistant Core?

2022.10

### What version of the Landroid Cloud integration do you have installed

3.0.0b5

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

Landroid M1000 (WG796E.1)

### Diagnostics information (NOT log entries!)

[config_entry-landroid_cloud-51dd06d4f011ef4731616d1896d581b6.json (1).txt](https://github.com/MTrab/landroid_cloud/files/11429268/config_entry-landroid_cloud-51dd06d4f011ef4731616d1896d581b6.json.1.txt)

### Relevant log entries

```txt
None. I'd update issue if I can find anything relevant to my issue in the logs.
```

**Comment by MTrab** [comment]
I see nothing wrong in the provided diagnostics.
Would you mind sharing access to you account, for further debugging, at landroid_cloud (at) trab.dk ?

**Comment by pszafer** [comment]
Ok, as you can see it shows as `"online": false,` so returning wrong status

**Comment by MTrab** [comment]
Oh yeah - missed that line.
That one is as reported by the API and not calculated

**Comment by MTrab** [comment]
Is your mower online in the app?

**Comment by Cosmicbase** [comment]
The same with me.  Mower is online and mowing.  The app is also online.
Mower is not available in Homeassistant.

**Comment by inspgadgetNL** [comment]
I have it too. Can't start the integration

**Comment by Kemden** [comment]
Same Here

**Comment by matejek** [comment]
I am failing with installation and konfiguration

error:
ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Worx - my@email for landroid_cloud
File "/config/custom_components/landroid_cloud/__init__.py", line 64, in async_setup_entry
File "/config/custom_components/landroid_cloud/__init__.py", line 208, in _async_setup

**Comment by MTrab** [comment]
Check you email and password - the error for that currently looks like the one you are seeing

**Comment by matejek** [comment]
@MTrab : thanks for swift reply - I am suing the same credentials as for "https://id.worx.com/" - where they do work

**Comment by MTrab** [comment]
Strange - at least I'm pretty sure it's not the same as this issue, as in this issue the account have been added

**Comment by SchallertDK** [comment]
![image](https://github.com/MTrab/landroid_cloud/assets/103250760/f55d0640-cc50-4ddf-9c18-db6609aa3c81)

![image](https://github.com/MTrab/landroid_cloud/assets/103250760/ed0b2934-b4ba-4b5d-919f-a68477fb5b62)

**Comment by matejek** [comment]
@MTrab and @SchallertDK - as it seems to be another issue, I am going to raise a new one

**Comment by pszafer** [comment]
@MTrab did you get credentials via email?

**Comment by MTrab** [comment]
@pszafer yes I did - sorry for the long delay in response. Been very busy lately.

**Comment by MTrab** [comment]
@pszafer the mail you have sent contains a link to a Vaultwarden, that isn't valid anymore.

**Comment by pszafer** [comment]
@MTrab link updated via email

**Comment by MTrab** [comment]
@pszafer just checked directly in the API (not thru the integration) and the API reports `"online": false`
So that's the reason for the device being unavailable.

**Comment by MTrab** [comment]
App says offline as well, with latest update 14.05.2023 20.13.33

**Comment by pszafer** [comment]
I'm on holiday this week so it's true, I turned it off for this time.

**Comment by MTrab** [comment]
Okay - others that want to share credentials for bug-finding regarding this issue?

landroid_cloud (at) trab.dk

Am planning on releasing a non-beta version during the next few days, and would be nice to have a chance to do some troubleshooting on this in advance and perhaps even have a fix ready.

**Comment by MTrab** [comment]
Yes please

**Comment by shaman79** [comment]
OK, sent.

**Comment by dominikgar** [comment]
@MTrab I need to admit, that I did also observed issue described in the ticket but after the latest upgrade, it seems status is constantly updated.
My model is Landroid L1000 (WR147E.1)

**Comment by MTrab** [comment]
Any updates on this since latest release?

**Comment by pszafer** [comment]
It's working now! Thanks!
