### ISSUE TITLE
[FR]: Automation - Zone - Current is not working

### ISSUE THREAD

**Issue by maijo366** [MTrab/landroid_cloud#364]
### Describe the feature you wish to make a request for

Hello, how can i crate an automation for zone. 
This is shows in developer tools - state of mower
zone:
  current: 0
  index: 4
  indicies:
    - 0
    - 1
    - 2
    - 3
    - 0
    - 1
    - 3
    - 1
    - 3
    - 3
  starting_point:
    - 3
    - 40
    - 42
    - 43 
    
    I crate this - see yaml code, but ist not working.

automation:
alias: Mähzone 1 - EIN
description: ""
trigger:
- platform: state
    entity_id:
      - vacuum.mower
    to: "current: 0"  (i also tried this) to: 0
    id: Mähzone 1
    attribute: zone
condition: []
action:
 - conditions:
          - condition: trigger
            id: Mähzone 1
        sequence:
          - service: switch.turn_on
            data: {}
            target:
              entity_id:
                - switch.mahzonen_8ch
                - switch.tasmota_f4cfa26e9f35_switch_relay_4
 
Thanks for helping.

**Comment by MTrab** [comment]
As you can see here - you cannot set zone currently: https://github.com/MTrab/landroid_cloud/issues/350

**Comment by MTrab** [comment]
Also not a feature or an issue. For automation helt, please go to Home Assistant community
