### ISSUE TITLE
Connecting to Cloud fails

### ISSUE THREAD

**Issue by matejek** [MTrab/landroid_cloud#365]
### Describe the issue

I am failing with installation and konfiguration

error:
ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Worx - my@email for landroid_cloud
File "/config/custom_components/landroid_cloud/init.py", line 64, in async_setup_entry
File "/config/custom_components/landroid_cloud/init.py", line 208, in _async_setup

Installation of Landroid integration works.
Configuration fails with "Error while configuring"
Error messages see above.
I am using credentials which are working at https://id.worx.com

### What version of Home Assistant Core has the issue?

core-2023.5.2

### What version of the Landroid Cloud integration do you have installed

v2.3.4

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

Landroid Vision WR206E

### Diagnostics information (NOT log entries!)

None

### Relevant log entries

```txt
ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Worx - my@email for landroid_cloud
File "/config/custom_components/landroid_cloud/init.py", line 64, in async_setup_entry
File "/config/custom_components/landroid_cloud/init.py", line 208, in _async_setup
```

**Comment by GadgetUK** [comment]
Known issue. You need to run the latest beta version which resolved this.

https://github.com/MTrab/landroid_cloud/releases

**Comment by matejek** [comment]
@GadgetUK : awesome! that works now! MANY THANKS!

PS: had to kind of manually wget the zip - as I couldn't find a way to configure loading beta

**Comment by SchallertDK** [comment]
Oh damn. I dont how to do this 😅 i'm not that technically good

**Comment by matejek** [comment]
@SchallertDK 
this is how I did it - worked for me - but there might be a better way (I am not aware of)

* opening add-on "advanced ssh&web terminal"    (to be installed before :-) )
* cd /root/config/custome_comments/landroid_cloud
* rm all files and directories
* wget https://github.com/MTrab/landroid_cloud/releases/download/v3.0.0b5/landroid_cloud.zip
* unzip landroid_cloud.zip
* restart Home Automation

**Comment by GadgetUK** [comment]
If you're using HACS on HASSOS then there's an option to "show beta versions" when you select "redownload"

**Comment by matejek** [comment]
:-) cool     I didnt find the "redownload"     but did now - noted!

**Comment by SchallertDK** [comment]
Thanks a lot for your guide :) 
Now it's alive again in HA :)
