### ISSUE TITLE
[FR]: support of new Worx Landroid Vision WR206E

### ISSUE THREAD

**Issue by matejek** [MTrab/landroid_cloud#366]
### Describe the feature you wish to make a request for

I have 2 Landroids, landroid_cloud recognized my Landroid M1000 (WG796E.1) but didn't recognize my new Landroid Vision WR206E (Landroid Vision M600)

Is this an issue or a feature request?

**Comment by matejek** [comment]
I just found the "Vision" in the diagnostics information..... still not added as a device, though

**Comment by ZIOOIZ8** [comment]
I join this feature request as an owner of the same type WR206E (Landroid Vision M600), currently the Vision series is not properly recognized or integrated.

**Comment by MTrab** [comment]
> I just found the "Vision" in the diagnostics information..... still not added as a device, though

Please attach the diagnostics file to this issue (drag'n'drop the file, DO NOT COPY/PASTE!)

**Comment by ZIOOIZ8** [comment]
Hi Ms. Trab, I can also provide the data, not sure exactly what is needed. I guess the diagnostic data from the eriteration. Can I delete the for me sensitive data from the json out, or is that not so good? Here you can see what the integration creates for entities in the HA:
![grafik](https://github.com/MTrab/landroid_cloud/assets/87153886/ade653f6-f209-424e-917f-6105084c5304)

**Comment by MTrab** [comment]
All sensitive data are already redacted from the diagnostics

**Comment by ZIOOIZ8** [comment]
[config_entry-landroid_cloud-c92dcd413aa22b75dc9fa8fa685f10f7.json.txt](https://github.com/MTrab/landroid_cloud/files/11480958/config_entry-landroid_cloud-c92dcd413aa22b75dc9fa8fa685f10f7.json.txt)

Here is the data, I hope it helps ;).

**Comment by brot123** [comment]
I also have a Landroid Vision M600 the first thing I noticed is that in the app the MAC address is not transmitted, this is also reported in the HA logfile as an error. Can you enter the Mac address manually? 
Then you could see what happens afterwards. 
Around the 20th of May comes a major update, maybe we look then again what works or not.

**Comment by MTrab** [comment]
PayPal is malene@trab.dk - otherwise just use buymeacoffee

Also - Vision isn't in the API docs yet, seems like the data is in another format.

**Comment by merti29** [comment]
that was what i needed, buymeacoffee does not work for me ;) Thx malene

**Comment by RobinBeismann** [comment]
I just received my Landroid M800 Vision too, looking forward to the support of it. Let me know if you need any more information from the robot.
Thanks for the effort you spent into this. 👍

**Comment by MTrab** [comment]
I will - hopefully - start looking into Vision support next week.

**Comment by MTrab** [comment]
Any of you Vision guys using zones?
If so, please share credentials to landroid_cloud (at) trab.dk referencing issue 366 in the subject.

I need to figure out the new style of response, as Positec haven't shared this with me yet - and there are HUGE differences, so this might take some time :/

**Comment by cutzenfriend** [comment]
Sorry no zones hier. Just one default.

**Comment by WimObiwan** [comment]
About the multi-zones, maybe this helps:
- I have a new model of Kress Mission RTK (KR173E), which seems to have an overhauled message format, _possibly_ the same you are seeing with the Vision.  Especially the "scheduling" part ("sc") of the config seems changed heavily.
- I have 2 zones

I will send my credentials as instructed.

**Comment by ZIOOIZ8** [comment]
![grafik](https://github.com/MTrab/landroid_cloud/assets/87153886/c388698c-f000-4bf8-814e-5cdbccf93ed5)
Since the last but one version, I always get this error: I can no longer log into the Worx Cloud. What am I doing wrong?

**Comment by MTrab** [comment]
Well - if your mower is a Vision, then you do nothing wrong - they simply aren't supported yet as the present data from the API in another way

**Comment by ZIOOIZ8** [comment]
OK, thanks for the info. Yes, I have a Vision type WR206E (Landroid Vision M600) as described above. If I can help in any way, let me know.

**Comment by SebiWolze** [comment]
Got the WR208E (Vision M800) and would love to add him to my Homeassistant, if you need help (or a Coffee) lmk!
Thanks!

**Comment by brynyneuadd** [comment]
Yes!!! Have the new WR216E (Vision L1600) and I can't have this being the only smart device in the house that DOESN'T integrate with home assistant! Let me know if I can help!

**Comment by SebiWolze** [comment]
any updates?

**Comment by MTrab** [comment]
Not at all - haven't had time to look more into this.
Also, as far as I remember I need someone with a Vision using zones, as the mapping is strange

**Comment by cutzenfriend** [comment]
I Have one. I don't use multiple zones just one but I think this is the default. You at least have to have one zone.

What can I do to help?

**Comment by cutzenfriend** [comment]
@MTrab how can I help?

**Comment by danielblnc** [comment]
I have a Vision L 1300 with two zones

**Comment by MTrab** [comment]
Haven't had much time to look more into this, but might get alot of time for a period soon.
Do not expect full support until next mowing season.

@danielblnc would be nice to get access to the account for the development during the next months.
Could you share the credentials to landroid_cloud (at) trab.dk mentioning issue 366 in the subject?

**Comment by galamarco** [comment]
I join the request to also support the Landroid Vision. I have a couple of them and it would be really useful to manage them from the Home Assistant.

**Comment by MTrab** [comment]
Finally initial Vision support will be available - at first in a beta version released shortly.
Not all functions and attributes are fully working yet - ie. zone information and setting is not working.
Other issues might be rising as well.
If finding issues with Vision support, please create separate issues for that (makes it easier to track what is missing)

**Comment by heimwege** [comment]
Thanks a lot for this integration. Looks promising 😸 
![image](https://github.com/MTrab/landroid_cloud/assets/73878785/a53ff45f-af88-4177-b314-a74ea8e1e08d)

**Comment by MTrab** [comment]
If any of you are using zones, please let me know if you are willing to share credentials - that way I might be able to speed up the support for that as well.

**Comment by benjamin-salchow** [comment]
Thank you for this great work :-). I've installed and tested beta v3.1.0b4 with my Vision M.
 
Sorry, I also don't have a working zone here. During my tests I saw that receiving the Party-mode Status works fine and is very fast on fetching changes from the cloud API. 

Only the service:
```
landroid_cloud.partymode
```
isn't able to change the state (enable or disable) with the following error message:

```
Error handling message: Failed to call service 'partymode'. Service is not supported by this device. (unknown_error) 
```
This would be really a cool service for an automation. E.g. to change to party mode, if the door to the garden is open and kids are playing outside.

@MTrab what do you think about having a Switch which represents and changes that Party-Mode state?

**Comment by MTrab** [comment]
@benjamin-salchow `If finding issues with Vision support, please create separate issues for that (makes it easier to track what is missing)`

Regarding the switch question: Will happen in a future release - Positec just took me by surprise with a new style API, so that feature got moved further in the future.

**Comment by Tillersens** [comment]
Thank You so much for adding Vision!

And just in case You have not noticed yet...
https://www.home-assistant.io/blog/2023/09/06/release-20239/#lawn-mower

Thanks again, great job!!!

**Comment by MTrab** [comment]
Will be closing this FR, as the support has been introduced.
As mentioned in an earlier post, please create new issues for missing functions or bugs.
