### ISSUE TITLE
[FR]: attribute mowing_zone

### ISSUE THREAD

**Issue by gost4711** [MTrab/landroid_cloud#370]
### Describe the feature you wish to make a request for

I don't know if it's a bug or if this attribute doesn't exist.
I would appreciate this attribute.

**Comment by MTrab** [comment]
Isn't what you are looking for the zone: current??

**Comment by MTrab** [comment]
It is updated by the mower, so if you set it manually it'll be updated next time the mower reports zones back

**Comment by MTrab** [comment]
Theoretically yes you can. Would advise against it to not get you banned.

It will be updated whenever the robot reports new states, this differs depending on the actual state of the mower

**Comment by gost4711** [comment]
OK thanks
