### ISSUE TITLE
landroid_cloud.edgecut => service not supp. (worx wr105si)

### ISSUE THREAD

**Issue by gibman** [MTrab/landroid_cloud#375]
### Describe the issue

I have the old 2017 model wr105si which should support Edge Cut.
Atleast the official android app has Edge Cut as an option so I suppose it's supported.

When calling...
landroid_cloud.edgecut
I get the error "service not supp".

Otherwise the integration works fine. Starting, pausing, docking etc. All working correctly.

regards
gibman

### What version of Home Assistant Core has the issue?

2023.3.6

### What was the last working version of Home Assistant Core?

2023.3.6

### What version of the Landroid Cloud integration do you have installed

v3.0.0b5

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

Worx wr105si

### Diagnostics information (NOT log entries!)

none

### Relevant log entries

```txt
none
```

**Comment by MTrab** [comment]
Pretty sure that model doesn't support edge cut on demand.
Can you call the edge cut routine from the app? (NOT scheduling)

**Comment by gibman** [comment]
It seems like you are right.
The cut2edge feature is only part of the schedule.
Bizarre API choice on their part.

So what are the work arounds here ?
Should I add any immediate cut2edge sessions as a schedule - if this is even possible ?

Ideally I wanted to build my own appdaemon logic for handling my mower. But it looks to me like I have to use the builtin scheduler if I want to have my edges cut.

**Comment by MTrab** [comment]
There is no workaround - these models simply doesn't support this feature

**Comment by gibman** [comment]
There was a work around :)

simply calling the schedule xxxday_boundary set to true
Just start it 1-2min into the "future" for the actual day.

something like

service: landroid_cloud.schedule
data:
  type: primary
  tuesday_boundary: true
  tuesday_start: "19:39:00"
  tuesday_end: "20:00:00"
target:
  entity_id: vacuum.grasshopper

**Comment by maoterodapena** [comment]
Sorry to comment on a closed issue, but there is a better workaround (at least for my model wr104si, who has no edge_cutting).

You can send three consecutive raw commands: 4 (zonning) 2 (pause) and 3 (edge cut). I use the Landroid Cloud: send_raw service, with json: {"cmd": 4}, then wait 5 seconds, send again  {"cmd": 2}, wait another 5 seconds, and last: {"cmd": 3}

It would be nice to integrate such sequence when calling edge cutting if it is not supported.

**Comment by MTrab** [comment]
This only works on very few models, and will not be implemented
