### ISSUE TITLE
[FR] Start EDGE Cut directly

### ISSUE THREAD

**Issue by vistalba** [MTrab/landroid_cloud#38]
As also possible here (https://www.roboter-forum.com/index.php?thread/22795-entwicklungsprojekt-worx-landroid-kress-mission-desktop-app/) may this would be a nice enhancement too.

As I know this is just a simple:

- Send: Start
- wait N seconds (default = 3)
- Send: Pause
- Send: Home

**Comment by MTrab** [comment]
I have just today closed issue #34 as this is not possible from within the app.

I'll test what you have sent thou - perhaps that'll do the trick :)
It's definetely a great feature to have.

**Comment by MTrab** [comment]
Unfortunately it wasn't that easy.

Start
Wait 3 secs
Pause
Home

This just starts the Landroid

**Comment by MTrab** [comment]
My German is VERY bad, but I can read something about this proceduere no longer is working.

If you find a confirmed way of doing edge cut, please do write and I'll reopen and revisit this FR.

**Comment by vistalba** [comment]
As I can read there... this seems to be a bug in the 3.0x Firmware and 2019 models that should be resolved in a newer release.

**Comment by MTrab** [comment]
I have version 3.52, althou it's on an older (2018) S500 - and it's not working on this one.

**Comment by vistalba** [comment]
Will report back if I become another update and it works ;) On the other hand.. I can simply to this by myself in nodered.

**Comment by MTrab** [comment]
Correct (that's the way I tested yesterday ;) )
