### ISSUE TITLE
In Error if you have 2 landroid

### ISSUE THREAD

**Issue by Disciplus86** [MTrab/landroid_cloud#380]
### Describe the issue

in the version 3.0.0 and 3.0.1.
we have a error with landroid cloud with my account.
We have 2 landroid in the account, i have remove one. now it's OK. 

### What version of Home Assistant Core has the issue?

2023.5.4

### What was the last working version of Home Assistant Core?

2023.5.4

### What version of the Landroid Cloud integration do you have installed

3.0.1

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

WG798E

### Diagnostics information (NOT log entries!)

sorry we don't have log now...

### Relevant log entries

```txt
sorry we don't have log now...
```

**Comment by MTrab** [comment]
You are not giving me anything to work on
I need AT LEAST log entries for the error

**Comment by Disciplus86** [comment]
i know but , now i have remove a old WG798E (she was KO).
I can't reproduce the problem, i'm really sorry.
