### ISSUE TITLE
Crash with Home Assistant 0.110.4

### ISSUE THREAD

**Issue by iRobert-John** [MTrab/landroid_cloud#39]
Hi, 

My complete system crashes if I use Landroid_cloud in my configuration.yaml. Does not restart and need to delete the lines in the config file. The integration is installed but in HACS it still shows that I can install it as well.

**Comment by MTrab** [comment]
Log file?

**Comment by iRobert-John** [comment]
2020-06-01 20:32:12 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for landroid_cloud which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.


This is the only thing coming up in the log related to Landroid.

**Comment by MTrab** [comment]
That is unusable in bug finding, as all custom_components post that warning - perfectly normal.

If that's all, then I have no clue right now - perhaps enable debug logging for landroid_cloud:

```
logger:
  default: info
  logs:
    homeassistant.components.landroid_cloud: debug
```

Also - please share your landroid_cloud config.

**Comment by MTrab** [comment]
Guess you got this fixed - closing the issue.
