### ISSUE TITLE
not work setzone

### ISSUE THREAD

**Issue by ilgio** [MTrab/landroid_cloud#394]
### Describe the issue

the setzone not work..
there is some problem with the integration maybe.. watch the video and you will see that when I select the zones, only some times the current changes, while the index always changes
[video](https://youtu.be/T3YC2K1wbAk)

### What version of Home Assistant Core has the issue?

2023.6.1

### What version of the Landroid Cloud integration do you have installed

3.0.4

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

M700

### Diagnostics information (NOT log entries!)

[config_entry-landroid_cloud-817c717c7aa888161695616e92d3e9a5.json.txt](https://github.com/MTrab/landroid_cloud/files/11733555/config_entry-landroid_cloud-817c717c7aa888161695616e92d3e9a5.json.txt)

### Relevant log entries

```txt
nessuno
```

**Comment by ilgio** [comment]
here's using direct service

[service](https://youtu.be/1NqjZwJrsVo)

**Comment by MTrab** [comment]
That indeed looks a bit strange - although it CAN be an issue for the API, sending commands that quick after each.

**Comment by ilgio** [comment]
I also tried to do it slowly waiting 30 seconds between one request and another... the behavior is always the same

**Comment by ilgio** [comment]
I deleted the integration in HACS,
I rebooted, reinstalled and re-entered my login and password.. now it works
bohh
