### ISSUE TITLE
Resetting the blade working time has no effect in HomeAssistant

### ISSUE THREAD

**Issue by muschelman** [MTrab/landroid_cloud#399]
### Describe the issue

If I reset the blade working time in the Worx app, it is not reset in the HomeAssistant integration. Only when I restart the integration will the reset also be visible in HomeAssistant.

![grafik](https://github.com/MTrab/landroid_cloud/assets/47613434/ec6480c6-a4a8-4692-8f9d-a61a64050241)

![grafik](https://github.com/MTrab/landroid_cloud/assets/47613434/80b316a2-c273-4983-9e91-36574015e673)

![grafik](https://github.com/MTrab/landroid_cloud/assets/47613434/0cdeb9fc-b0d6-4b0b-86bf-efcc5158c71e)

### What version of Home Assistant Core has the issue?

2023.6.2

### What was the last working version of Home Assistant Core?

-

### What version of the Landroid Cloud integration do you have installed

3.0.5

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

Landroid M500

### Diagnostics information (NOT log entries!)

[config_entry-landroid_cloud-3ef5f447c2a59dbdff1aafab69a13e31.json.txt](https://github.com/MTrab/landroid_cloud/files/11896007/config_entry-landroid_cloud-3ef5f447c2a59dbdff1aafab69a13e31.json.txt)

### Relevant log entries

```txt
None
```

**Comment by Phoenix-DH** [comment]
I had to step in again also.
I had also opened an issue few weeks ago but I think it was solved.
But today I reseted the blades again.

Again with the same issue, no change in HA.
I have created an own sensor to track it, and also this one did not changed.

I cannot find any log entries.

**Comment by pbertra** [comment]
Same problem for me

**Comment by MTrab** [comment]
Should be fixed in v4 (currently in beta state)
