### ISSUE TITLE
integration freezes

### ISSUE THREAD

**Issue by anowicki8422** [MTrab/landroid_cloud#402]
### Describe the issue

I often have to restart the integration to see the current state.  without restarting it will not refresh the status of the mower

### What version of Home Assistant Core has the issue?

Lipcowy

### What version of the Landroid Cloud integration do you have installed

Aktualną 

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

L1000

### Diagnostics information (NOT log entries!)

.

### Relevant log entries

```txt
Brak
```

**Comment by MTrab** [comment]
Same as #385
