### ISSUE TITLE
Failed to login into the cloud (Fehler bei der Authentifizierung)

### ISSUE THREAD

**Issue by tryerror12** [MTrab/landroid_cloud#404]
### Describe the issue

After deleting my WR105 and adding the new WR167e i can not login into the HA Landroid cloud.
I also changed my PW already but dosent help.
Loging in my Worx acc. is working without an Issue.

Anybody an idea?

### What version of Home Assistant Core has the issue?

core-2023.7.2

### What was the last working version of Home Assistant Core?

core-2023.7.2

### What version of the Landroid Cloud integration do you have installed

3.0.5

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

Worx WR167E

### Diagnostics information (NOT log entries!)

----                                                                                      

### Relevant log entries

```txt
Failed to logging
```

### Additional information

---

**Comment by tryerror12** [comment]
A dissconnected the mower from the add and also reinstalled the Cloud integration several times. 
Nothing helps.

Anybody an idea? 
Before i moved to a different Mower model everthing worked fine.
Is there other things i need to delete for an new installation of the Worx cloud?

**Comment by MTrab** [comment]
This ain't a Vision model, right?!

**Comment by tryerror12** [comment]
No it is the Wr167e also called m700plus

Do you have any idea?

Malene Trab ***@***.***> schrieb am Mi., 26. Juli 2023, 16:09:

**Comment by MTrab** [comment]
Well, without relevant log entries, my ruling will be you entering wrong email og password

**Comment by tryerror12** [comment]
The Email and PW are right.
I changed the pw several times and log in on the worx homepage works
without issue.

Upper and lower letters in the email should not be an issue?

Which log you mean exactly?
I will provide it immediately

Thanks for your support!

Malene Trab ***@***.***> schrieb am Do., 27. Juli 2023, 08:27:

**Comment by MTrab** [comment]
You should have some relevant entries in the log-file (home-assistant.log)

**Comment by tryerror12** [comment]
I tryed to login and check after the log file.
No entries of landroid, worx or cloud.....

Malene Trab ***@***.***> schrieb am Do., 27. Juli 2023, 08:45:

**Comment by MTrab** [comment]
That's very strange then - no clue as to what it could be.

If you like, I can try check in my dev environment, but that would require you to share your credentials to landroid_cloud (at) trab.dk (please refer to issue 404 in the subject)

**Comment by tryerror12** [comment]
Thanks for the offer.

Could you please let me know how to remove remove everthing which is
related to the landroid integration?

I would like to try an fresh Installation

Thanks

Malene Trab ***@***.***> schrieb am Fr., 28. Juli 2023, 12:08:

**Comment by MTrab** [comment]
Select uninstall from HACS

**Comment by tryerror12** [comment]
Ive send you the login data

Malene Trab ***@***.***> schrieb am Fr., 28. Juli 2023, 12:24:

**Comment by tryerror12** [comment]
@MTrab did you had already the chance to check it?

**Comment by MTrab** [comment]
Sorry, no - but just did. No issues what-so-ever on the current release.

**Comment by tryerror12** [comment]
Strange.
I just tryed again and still wound work.

Did you wrote the Email with all small letters?
Any idea what could help?
Cache?

**Comment by MTrab** [comment]
Copy paste from your email - sorry I cannot help, but this issue is something in your end it seems.

**Comment by MTrab** [comment]
Closed as it cannot be reproduced at my end.
