### ISSUE TITLE
Service landroid_cloud.setzone selects wrong zone

### ISSUE THREAD

**Issue by redfusion83** [MTrab/landroid_cloud#407]
### Describe the issue

The service does not select the correct zone. Here's an example of what the zone attribute looks like after setting the zone to 2 using the service:
`{ "current": 0, "index": 4, "indicies": [ 2, 3, 0, 2, 0, 2, 0, 0, 0, 1 ], "starting_point": [ 4, 40, 142, 173 ] }`
Active zone is now 0. The active zone should be the 4th element in the list of indicies, but the selected one is the 5th, probably because the index counts from 0 to 4.

Another try, using the service to select zone 1:
`{ "current": 2, "index": 4, "indicies": [ 0, 0, 0, 1, 2, 3, 0, 2, 0, 2 ], "starting_point": [ 4, 40, 142, 173 ] }`
Again, the 4th element in the list is correct, but the 5th one is selected.

### What version of Home Assistant Core has the issue?

2023.7.3

### What was the last working version of Home Assistant Core?

2023.8.1

### What version of the Landroid Cloud integration do you have installed

3.0.5

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

Landroid L1000

### Diagnostics information (NOT log entries!)

None

### Relevant log entries

```txt
None
```

**Comment by Schopenhauer178** [comment]
Hallo, i have the same issue. The zone selection does not work...

**Comment by MTrab** [comment]
Just trying to get the big picture of the issues.

Is this still an issue?

**Comment by hitzi69** [comment]
Ja, leider noch immer

**Comment by MTrab** [comment]
Would need some credentials shared to landroid_cloud (at) trab.dk to debug this.

**Comment by hitzi69** [comment]
Unfortunately I don't know what to do. I don't know enough about it.

**Comment by MTrab** [comment]
Send your credentials to landroic_cloud (at) trab.dk as asked - then I'll do the debugging.

**Comment by hitzi69** [comment]
So my login details from the Landroid Cloud? And where can I send them? E-mail? Sorry, I don't know much about it.

**Comment by MTrab** [comment]
As written - landroid_cloud (at) trab.dk

**Comment by hitzi69** [comment]
I'm sorry. I have to pass. I don't know where to send it. I can't do anything with the landroid_cloud (at) trab.dk. That's not an email address. Maybe someone else can do it.

**Comment by MTrab** [comment]
Just replace the (at) with a @
Just not writing it in full, to prevent spam.

**Comment by MTrab** [comment]
But it's okay of you pass. Just can't fix it without access to a device with the issue.

**Comment by hitzi69** [comment]
I sent it.  Hope that's ok

**Comment by MTrab** [comment]
> I sent it. Hope that's ok

Your zone data looks WAY off and not like anything generated by either Landroid_Cloud integration or the Landroid app

**Comment by MTrab** [comment]
Anyone else with this issue care to share credentials? Perhaps @redfusion83 as it seems like your data is valid and with the issue.
Otherwise I'll have to close this as I have NO valid data to debug on.

**Comment by redfusion83** [comment]
Hi @MTrab , before sending this mail I checked this issue again. And guess what - it seems to work now. The zone is selected correctly. Maybe an update fixed it.

Anyway, thanks for this great integration and your efforts. Seems like this issue can be closed now!
