### ISSUE TITLE
Register services with correct schema

### ISSUE THREAD

**Issue by AlexanderAlder** [MTrab/landroid_cloud#41]
Hey,
I'm having problems trying to script with templates against the landroid_cloud services.
See my forum post for more details:
https://community.home-assistant.io/t/pass-the-template-value-as-a-python-integer/200932

Issue/suggested solution was:
The problem is in the landroid_cloud.start service. It needs to use a schema that converts the id input to an int. When registering the start service it does not specify a schema.

**Comment by MTrab** [comment]
Which version are you using?
Exactly this shold be solved in the latest version.

**Comment by AlexanderAlder** [comment]
Landroid Cloud 
Installed: v1.6.1
Last updated: 8 days ago

**Comment by AlexanderAlder** [comment]
So in __init__.py I notice that 
```
    async def handle_start(call):
    async def handle_pause(call):
```
get the parameter 'call', 'call' contains a call.data["id"], call.data["id"] contains the correct id number.
But the type of this call.data["id"] is a python sting class instead of an integer
So the line `if attrs["id"] == ID:` never happens

**Comment by MTrab** [comment]
Arh - sorry, can see I missed making the change to start, pause and home calls.

Will make the changes to these services in next release.
