### ISSUE TITLE
Can not Login to the account (Cloud Integration)

### ISSUE THREAD

**Issue by maijo366** [MTrab/landroid_cloud#417]
### Describe the issue

I deleted the integration and install it new. Version 3.05
But now i can not login to the integration. Always show: Error in the Authantication.
On the webapp on landroid i can login and see my mower.

What can i do??

Please help.

### What version of Home Assistant Core has the issue?

8.3

### What was the last working version of Home Assistant Core?

8.3

### What version of the Landroid Cloud integration do you have installed

3.05

### What type of installation are you running?

Home Assistant Supervised

### Which make and model is the mower used for this integration?

Worx Landroid WR147E.1

### Diagnostics information (NOT log entries!)

--

### Relevant log entries

```txt
--
```

**Comment by MTrab** [comment]
Please check you username and password - every other issue like this have come down to typos.

**Comment by maijo366** [comment]
I check this but i have alwas the same issue. I can login at the webapp Landroid. Whats happend? What can i do?

**Comment by MTrab** [comment]
The best I can do is to offer you to send the credentials to landroid_cloud (at) trab.dk and then I can test in my developer environment.

**Comment by ilgio** [comment]
I have same problem
<img width="1493" alt="Screenshot 2023-08-30 alle 18 45 50" src="https://github.com/MTrab/landroid_cloud/assets/26309528/539780f2-fa6e-4a85-9efb-3e9e0285d0f7">
<img width="922" alt="Screenshot 2023-08-30 alle 18 40 35" src="https://github.com/MTrab/landroid_cloud/assets/26309528/87cc4926-7abf-4fc4-a3f3-2f0389ecbb65">

**Comment by maijo366** [comment]
Now i can login to my account. 
I reinstalled homeassistant. So there must be an error in the overall installation. I couldn't solve it even by restoring the backup.
It's working again now. perfect.
@mtrab - thanks for helping (answering) ;-)

**Comment by polomueller** [comment]
> Since about 2 hours the same issue again. ![Screenshot 2023-08-30 212924](https://user-images.githubusercontent.com/96180786/264452527-30c9a10c-9215-47de-8fbd-5c6997a389f8.jpg)

Same here...3 hours ago everything was fine...

**Comment by Porzeczek** [comment]
Here is log of this error, it looks like something has changed in api with 'firmware_version'.
When i comment  line 119 in api.py everything is working fine. (But don't be me, dont change anything in files until you know what you doing)

```
Ten błąd pochodzi z niestandardowej integracji.

Logger: homeassistant.config_entries
Source: custom_components/landroid_cloud/__init__.py:206
Integration: Landroid Cloud (documentation, issues)
First occurred: 22:54:30 (1 occurrences)
Last logged: 22:54:30

Error setting up entry Worx - xxxxxxxxxxxxxxxxx@gmail.com for landroid_cloud
Traceback (most recent call last):
  File "/home/hass/homeassistant/lib/python3.11/site-packages/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hass/homeassistant/.homeassistant/custom_components/landroid_cloud/__init__.py", line 63, in async_setup_entry
    result = await _async_setup(hass, entry)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hass/homeassistant/.homeassistant/custom_components/landroid_cloud/__init__.py", line 206, in _async_setup
    await hass.async_add_executor_job(cloud.connect)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hass/homeassistant/lib/python3.11/site-packages/pyworxcloud/__init__.py", line 259, in connect
    self._fetch()
  File "/home/hass/homeassistant/lib/python3.11/site-packages/pyworxcloud/__init__.py", line 611, in _fetch
    self._mowers = self._api.get_mowers()
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hass/homeassistant/lib/python3.11/site-packages/pyworxcloud/api.py", line 119, in get_mowers
    mower["firmware_version"] = '{:.2f}'.format(mower["firmware_version"])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Unknown format code 'f' for object of type 'str'
```

**Comment by MTrab** [comment]
Related to this issue: https://github.com/MTrab/pyworxcloud/issues/172

**Comment by tomu1907** [comment]
Same for me. Occurred after I have restarted Home Assistant

**Comment by sebster6** [comment]
Perfect, working again after updating. Thanks for the quick fix!

**Comment by cm86** [comment]
Hello,
yes same here. Is working after updating to the new version.

Nice Work. 
Thanks.

**Comment by Fiiti** [comment]
I am using 3.06 on  Home Assistant 2023.9.1 Supervisor 2023.09.0 Operating System 10.5 Frontend 20230908.0 - latest 

I cannot Login. It is the very first time i tried to use this Integrtation.
I wonder, what sebster6 and cm86 mean? Which Update from what to what?

As a result, I have the same problem as the first users had written. :(

**Comment by MTrab** [comment]
Do not expect any fixes from a closed issue
