### ISSUE TITLE
[FR]: Add support for Home Assistant Lawn Mower entity component.

### ISSUE THREAD

**Issue by rosscullen** [MTrab/landroid_cloud#422]
### Describe the feature you wish to make a request for

Hi @MTrab, you may be aware that the upcoming beta of Home Assistant will look to introduce a Lawn Mower entity component.

More details at [https://rc.home-assistant.io/blog/2023/08/30/release-20239/](https://rc.home-assistant.io/blog/2023/08/30/release-20239/#lawn-mower)

I haven't tried the beta yet but it looks like its in line with your latest version rewrite (i.e. similar to vaccum). Just thought I would let you know as you will probably get more queries about it in the coming days.
Take care,
R

**Comment by MTrab** [comment]
Yup. Have been following the development on the sideline.
