### ISSUE TITLE
Cannot Login to Worx Landroid Cloud

### ISSUE THREAD

**Issue by Fiiti** [MTrab/landroid_cloud#430]
## Describe the issue
I cannot log in when adding the integration. The error "Error during authentication" appears.
Of course, I have checked the input credentials several times. Online it works with all Worx and Landroid login screens, as in mobile.

It is the very first time i tried to use this Integrtation. I never had injstalled any other Versions on Landroid Cloud bevor.
So I had never logged in with the Landroid integration.

I have checked twice to see if Pihole has locked the connection. No entry found about this on Pihole.
In the normal Home Assistant loggings I have not found any information.  Maybe because the integration has never been installed?
How to enable a debug mode for this I don't know unfortunately.

### What version of Home Assistant Core has the issue?

Home Assistant 2023.9.1 Supervisor 2023.09.0 Operating System 10.5 Frontend 20230908.0 - latest

### What version of the Landroid Cloud integration do you have installed

3.06

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

Worx Landroid WR141E - FW 3.32.0+1 (latest)

### Diagnostics information (NOT log entries!)

Because the integration has never been installed - I get the error with the login - I obviously don't have the possibility to activate the debug mode as described in the link.

### Relevant log entries

```txt
In the normal Home Assistant loggings I have not found any information, maybe because the integration has never been installed?
```

**Comment by MTrab** [comment]
To enable debug log, see here: https://github.com/MTrab/landroid_cloud/blob/19719692647cf4a33f4b55fc7d76e9cd678b791e/config/configuration.yaml#L3-L7

Perhaps you could share your credentials to landroid_cloud (at) trab.dk - then I'll test in my dev environment.
Without more information I cannot help.

**Comment by Fiiti** [comment]
Thank you.
You should receive a mail.

**Comment by Fiiti** [comment]
Now it gets weird: I changed my password online and it suddenly works now.
I changed my email at Worx 1 month ago. Maybe something got mixed up at Worx or something was hanging during synchronization.?

Thank you very much for your help!

With kind regards

**Comment by maijo366** [comment]
No login possible!
Can i send my credentials to test?
I change my password. But it doesn't work.
