### ISSUE TITLE
Worx account is locked

### ISSUE THREAD

**Issue by distanzcheck** [MTrab/landroid_cloud#443]
### Describe the issue

Unfortunately, access to the Worx server is blocked after 2-3 hours of using this extension. The access will be unlocked after 24 hours. In case of multiple repetition of the constant querying of the extension, the account will be locked longer.

### What version of Home Assistant Core has the issue?

Home Assistant 2023.9.2

### What version of the Landroid Cloud integration do you have installed

3.1.0b4

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

Worx Vision M600 un Worx Landroid M700

### Diagnostics information (NOT log entries!)

.

### Relevant log entries

```txt
.
```

**Comment by MTrab** [comment]
Please provide the requested information!

Also, what do you do prior to being banned?

**Comment by xnisayx** [comment]
I think I have the same issue. It says "Error during set up". The Landroid App works fine.

I'm currently not at home so I can't collect logs for you.

**Comment by distanzcheck** [comment]
I just installed your extension and then this Landroid Card (HACS) to it. Connected my Vision and then,
without that I have clicked on the card what, I was yesterday after retesting after 15 minutes banned from the Worx account. (For 24 hours) That was last week when setting up in Home Assistanz the same.

**Comment by MTrab** [comment]
What if you are not using the Landroid Card?
Not sure if @Barma-lej  has introduced some service calls that triggers a ban.

**Comment by distanzcheck** [comment]
I could test this again tomorrow

**Comment by distanzcheck** [comment]
This app from the robot forum does not result in a lock.
https://www.roboter-forum.com/threads/entwicklungsprojekt-worx-landroid-kress-mission-desktop-app.22795/page-124#post-868704

**Comment by MTrab** [comment]
Think that's pretty irrelevant if you ask me.
This integration doesn't result in a lock either - I have 3 robots running for all year now without being banned. But I'm also NOT using the Landroid Card, which is why I'm suspecting that.

**Comment by distanzcheck** [comment]
I will test it tomorrow without the Landroid card and then let you know.

**Comment by distanzcheck** [comment]
As promised, I tested it again directly last night until now and lo and behold, as you thought, it's not your integration but the Landroid card. I will contact the provider of the Landdroid card times, maybe this knows nothing about it.

Another question: With my Vision M600 and my M700 (2019) is only displayed whether this is in the charging station or not. Is that sokorrekt or have I done something wrong? Greetings Dirk

Translated with www.DeepL.com/Translator (free version)

**Comment by maijo366** [comment]
Hello, 
maybe my account is locked. How can i test it?
No login possible!
Can i send my credentials to test?
I change my password. But it doesn't work.

This is the issue:
![grafik](https://github.com/MTrab/landroid_cloud/assets/96180786/50b29672-ce01-4656-8fd6-3ad0d2c347dd)

The App and weblogin is possible.

Please help.
Thanks.

**Comment by maijo366** [comment]
I can login at the app and weblogin, but no login possible at the HA-Landroid Cloud?
100% no wrongly username and password.

**Comment by MTrab** [comment]
I have to ask you to create an issue for this, as the issue you have added this into has nothing to do with your issue.

I'll remove your comments shortly.

**Comment by MTrab** [comment]
@distanzcheck everything still okay, without the landroid card?

**Comment by MTrab** [comment]
Please create a seperate issue for that and provide credentials at landroid_cloud (at) trab.dk - haven't heard of that issue, as all others is showing the current action.
