### ISSUE TITLE
Error in authentication!

### ISSUE THREAD

**Issue by busa-projects** [MTrab/landroid_cloud#45]
Hi

I tried to install Landroid_cloud, but on every restart it says "Error in authentication!". I tried with different passwords, which work on "My Landroid" Page. But no Luck with the app. Any possibility for more detailed Logging or any idea what's the Problem?

Thx busa

**Comment by MTrab** [comment]
Can you please show your configuration?
You need to use the same credentials as in the Landroid app (email/password)

**Comment by busa-projects** [comment]
Here is how my configuration.yaml looks like:

landroid_cloud:
  - email: MyUser@myDomain.com
    password: myAppPassword

Also tried setting a simpler Password in the App and used that for login. No success! Copy Paste the Credentials from the Config File to the Mylandroid Page works without issues.

**Comment by busa-projects** [comment]
I Copy Pasted your Config example into my configuration.yaml. So it looks like

```
landroid_cloud:
  - email: myUser@mydomain.com
    password: myAppPassword
```

I also changed the App password to a simpler one and tried with that - no success. I Copy/Pasted the credentials from the configuration.yaml into MyLandroid page and could login without any Problems. So Credentials must be ok.

**Comment by MTrab** [comment]
Unfortunately the servers only return true or false on login - so not much opportunity to tell which is wrong.
But something obviously are wrong with your credentials.

Do you use any special chars in the password or email?
I have never seen this kind of problem in my tests before.

**Comment by busa-projects** [comment]
Ok, found the Problem: a "," in the PW did make cause the Problems. No it works. Thx!
