### ISSUE TITLE
Animation not working

### ISSUE THREAD

**Issue by TvoDebug** [MTrab/landroid_cloud#450]
### Describe the issue

For some time now (guess 2023.9) the animation is not working properly animore

### What version of Home Assistant Core has the issue?

2023.10

### What was the last working version of Home Assistant Core?

2023.8?

### What version of the Landroid Cloud integration do you have installed

latest

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

WR184E

### Diagnostics information (NOT log entries!)

[

### Relevant log entries

```txt
-
```

**Comment by MTrab** [comment]
There is no animation in this integration as this integration does not have any UI cards other than the standard Vacuum card (which doesn't have animations)
