### ISSUE TITLE
New sensors in v4.0.0b2

### ISSUE THREAD

**Issue by sshalyminov** [MTrab/landroid_cloud#467]
### Describe the issue

1. sensor.landroid_rainsensor_triggered should be binary_sensor
2. sensor.landroid_online should be binary_sensor
3. sensor.landroid_last_update is always unknow and never updated

And question: when sensor.landroid_online will become off? My Landroid was turned off automatically because of I forgot to turn power source on :) but sensor remains "True" for next hour until I found issue and turned power on.

### What version of Home Assistant Core has the issue?

core-2023.11.2

### What version of the Landroid Cloud integration do you have installed

4.0.0b2

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

Worx Landroid L1500 (WR153E)

### Diagnostics information (NOT log entries!)

none

### Relevant log entries

```txt
none
```

**Comment by MTrab** [comment]
1 + 2 will be moved, thanks for the heads up.

3?! Hmmm - should represent a timestamp of the last update received by the API - strange if yours doesn't report this value.

As for the online sensor - when the API returns the mower as being offline, then it'll change.

**Comment by sshalyminov** [comment]
Found next error in log:

2023-11-13 20:54:01.237 ERROR (MainThread) [homeassistant.util.logging] Exception in handle_update when dispatching 'landroid_cloud_update_l': ()
Traceback (most recent call last):
  File "/config/custom_components/landroid_cloud/device_base.py", line 1019, in handle_update
    new_val = self.entity_description.value_fn(self.device)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/landroid_cloud/sensor.py", line 263, in <lambda>
    value_fn=lambda landroid: datetime.fromisoformat(landroid.updated),
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: fromisoformat: argument must be str

**Comment by sshalyminov** [comment]
And I see correct date/time in MQTT message: "tm":"20:54:00","dt":"13/11/2023"
and in JSON decoded: 'tm': '20:54:00', 'dt': '13/11/2023'

Both from log messages

**Comment by MTrab** [comment]
Yeah - that explains the missing update sensor. Will look into that as well
