### ISSUE TITLE
Starting the Mower no longer works from HA

### ISSUE THREAD

**Issue by JohnnyCarcinogen** [MTrab/landroid_cloud#471]
### Describe the issue

When clicking on start, I just get a spinning circle. I did update to the new version, and replaced the vacuum entity with the new lawn_mower entity. It's shows the mowers status, but I can't control it.

### What version of Home Assistant Core has the issue?

core-2023.11.2

### What was the last working version of Home Assistant Core?

core-2023.10.?

### What version of the Landroid Cloud integration do you have installed

4.0.0b3

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

Worx Landroid WR155

### Diagnostics information (NOT log entries!)

*

### Relevant log entries

```txt
*
```

**Comment by MTrab** [comment]
Any log entries?
If not, I might need your credentials to see if I can replicate. The ones I have for test works like expected.
