### ISSUE TITLE
Information is missing

### ISSUE THREAD

**Issue by Cosmicbase** [MTrab/landroid_cloud#472]
### Describe the issue

All information is incorrect, see also picture.
For example: WLAN, Timestamp, PartyMode,

Edgecut, mowing and the battery informations are seems right.
I don't know if the errors are due to the card.
The cloud data seems to be correct.

### What version of Home Assistant Core has the issue?

2023.11.2

### What version of the Landroid Cloud integration do you have installed

v4.0.0b3

### What type of installation are you running?

Home Assistant Supervised

### Which make and model is the mower used for this integration?

WR141E

### Diagnostics information (NOT log entries!)

![IMG_0193](https://github.com/MTrab/landroid_cloud/assets/31271212/be823bb2-5311-448c-b77a-a903bf5b7089)

### Relevant log entries

```txt
None
```

**Comment by MTrab** [comment]
I do not recognize the picture, from where does that originate?

**Comment by Cosmicbase** [comment]
If you click on the WiFi symbol at the top left of the Landroid card, this window will pop up with the information.

**Comment by MTrab** [comment]
I do not use og code the landroid card.
Does the device have the information present in the integration? If so, this is not an landroid_cloud issue.

**Comment by Cosmicbase** [comment]
Yes the information are present in the integration

**Comment by MTrab** [comment]
Then it's just because the landroid card isn't compatible with the latest beta version.
