### ISSUE TITLE
Can't add the integration

### ISSUE THREAD

**Issue by Dennisreneholm** [MTrab/landroid_cloud#477]
### Describe the issue

After i've installed the hacs integration, i restart HA, and go to add integration
After i choose Landroid Cloud, 10-15 seconds go by, and then i get the error
![image](https://github.com/MTrab/landroid_cloud/assets/5224930/98efdfcf-9154-4b44-8c83-efd9ef921c95)

### What version of Home Assistant Core has the issue?

core-2023.8.1

### What was the last working version of Home Assistant Core?

N/A

### What version of the Landroid Cloud integration do you have installed

Tried both v4.0.0b3 and b4

### What type of installation are you running?

Home Assistant Container

### Which make and model is the mower used for this integration?

WR115MI

### Diagnostics information (NOT log entries!)

none, can't add the integration yet.

### Relevant log entries

```txt
none, can't add the integration yet.
```

**Comment by MTrab** [comment]
Guess this is local to you. Just tried on a fresh installation of Home Assistant, and it works just as intended and does not cast the error you see.

Have you perhaps tried rebooting?

**Comment by Dennisreneholm** [comment]
I've tried restarting the container yes.

I had the older non beta version before. 3.1.XXX, i removed that before i installed the new one.
I have no idea what this error means.

**Comment by MTrab** [comment]
Without log entries I cannot help either.
Perhaps enable debugging and see if that gives any clues.

<ins>__Add this to your configuration.yaml file__</ins>
```
logger:
  default: warning
  logs:
    custom_components.landroid_cloud: debug
```

**Comment by Dennisreneholm** [comment]
`2023-11-29 14:28:38.844 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration landroid_cloud: No module named 'homeassistant.components.lawn_mower'
2023-11-29 14:28:46.235 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration landroid_cloud: No module named 'homeassistant.components.lawn_mower'
2023-11-29 14:28:58.565 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration landroid_cloud: No module named 'homeassistant.components.lawn_mower'`

**Comment by Dennisreneholm** [comment]
arh, i think i see the error now. i'm not running 2023.9
where it was introduced, hang on!

**Comment by MTrab** [comment]
Oh - so you didn't install from HACS?! Shouldn't be able to install this from HACS on versions lower than 2023.10

But yeah, that would explain your issues adding the beta versions.

**Comment by Dennisreneholm** [comment]
I did install it from hacs, and i had no issues doing so.

**Comment by MTrab** [comment]
Oh - just saw I haven't changed the HACS requirement - will fix for next beta release
