### ISSUE TITLE
Documentation improvements for Multiple Landroids?

### ISSUE THREAD

**Issue by koskila** [MTrab/landroid_cloud#48]
As it stands now, I understood there's support for multiple Landroids. However, while the entities for different landroids are created, it doesn't look to me like fetching sensor status or giving commands to multiple Landroids is either supported or documented.

**Comment by MTrab** [comment]
Sensor data are automatically collected from all available landroids from the given account.

Issuing commands is documented in the service menu in Home Assistant:

![image](https://user-images.githubusercontent.com/14296463/88919561-99175c00-d26b-11ea-82f8-6544c4e20959.png)

**Comment by koskila** [comment]
Ah - I got confused by how the services and entities are surfaced on the UI, but this actually does make sense. Thanks for the quick response.
