### ISSUE TITLE
add support for Landxcape

### ISSUE THREAD

**Issue by hsk-dk** [MTrab/landroid_cloud#49]
would it be possible to add support for Landexcape?

**Comment by MTrab** [comment]
Does Landxcape use same app as Landroids?
I don't have access to a Landxcape device, so I have no possibility to check if it's possible.

**Comment by hsk-dk** [comment]
it is a seperate app, but if i look at: https://github.com/iobroker-community-adapters/ioBroker.worx/blob/master/lib/api.js
it might just be a different end point for Landxcape..

**Comment by MTrab** [comment]
Looks like it might be doable - Think I'll give it a try. Nothing promised.

**Comment by Plaethe** [comment]
The landxcape support would be great!

**Comment by Plaethe** [comment]
Btw is there a way to support you with the analysis or to speed up development?

**Comment by MTrab** [comment]
I'll have a look at it soon, when the grass season starts.

**Comment by Plaethe** [comment]
So I tried the original Plug-In with my Landxcape credentials. As expected: doesn't work ..

**Comment by MTrab** [comment]
Indeed it won't work. Perhaps, if time is in my favor, I'll give it a go in this week.

**Comment by Plaethe** [comment]
JFYI: there is already a implementation existing which allows me to configure the landxcape as well as to retrieve some basic status information (i.e. working mode, battery, runtime, etc). => https://www.roboter-forum.com/index.php?thread/22795-entwicklungsprojekt-worx-landroid-kress-mission-desktop-app/&pageNo=1 (unfortunately in German). AFAIK is this no local network solution and runs also with the api.landxcape-services.com/api/v2/ .

**Comment by Plaethe** [comment]
> Indeed it won't work. Perhaps, if time is in my favor, I'll give it a go in this week.

Did you have any chance to get a closer clook?

**Comment by Lerbaek** [comment]
Looking at the API used by a number of other Landxcape clients on Github, the only difference does indeed seem to be the server (plus path and key).
https://github.com/iobroker-community-adapters/ioBroker.worx/blob/master/lib/api.js#L28

I've looked through your code, but has been unable to determine where the Worx server is defined, but I definitely second that this would be an excellent addition to an already great integration!

**Comment by MTrab** [comment]
I'll see if I can prioritize this request in the near future - have been occupied by new job and an extension of my drivers license ;)

A BIG help would be if I can lend some account informations (username + password) during the development, as I don't have a Landxcape model myself.

**Comment by Lerbaek** [comment]
Absolutely can do! I'll PM you.

**Comment by micy3us** [comment]
pyworxcloud added support for landxcape a couple of weeks ago so should be doable now =)

https://github.com/MTrab/pyworxcloud/commit/e08200f6395ea102ee2c4c3bf50a1b533571f619#diff-cff78c617e43f5425cade12c44527f7589099112a351bef358adde9842fae6cd

**Comment by MTrab** [comment]
Just a little update on this.

Initial testing looks promising, just need to adapt the landroid_cloud component to give the Landxcape option when added.
Unfortunately I'll be off for summer holidays for the next 2 weeks, so do not expect anything more until I'm back home :)

**Comment by Plaethe** [comment]
Awesome, looking forward to your results after your holidays!

**Comment by Lerbaek** [comment]
Looking forward to trying this out! What's the ETA of a (beta?) release of v1.7.2?

**Comment by MTrab** [comment]
Should be available when your HACS refreshes ;)

**Comment by Lerbaek** [comment]
Confirmed available and working, thanks a lot, duly appreciated!
