### ISSUE TITLE
[FR]: Migrate services to entitities 

### ISSUE THREAD

**Issue by Barma-lej** [MTrab/landroid_cloud#492]
### Describe the feature you wish to make a request for

Hi Malene.
It's no better to move services to entities?
For example:
torque, timeextension, raindelay, zone -> input_number

**Comment by MTrab** [comment]
That's on the roadmap, yes - just as ie. PartyMode has been moved

**Comment by seyit35** [comment]
Hello, first of all, great integration, one question: I need an automation for roller shutter control. When the Worx starts moving, the roller shutter opens, waits 3 minutes, then closes. When it then goes back to the charging station, the roller shutter opens, waits until it is docked, then the roller shutter closes again. So the entities for starting and returning to the charging station are missing.
