### ISSUE TITLE
Can't find timeextension

### ISSUE THREAD

**Issue by Barma-lej** [MTrab/landroid_cloud#493]
### Describe the issue

Hi, Malene.
I can't find current value of time_estension. Can you please add it to attributes of mower.___

### What version of Home Assistant Core has the issue?

-

### What was the last working version of Home Assistant Core?

-

### What version of the Landroid Cloud integration do you have installed

latest

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

m500

### Diagnostics information (NOT log entries!)

-

### Relevant log entries

```txt
-----------
```

**Comment by MTrab** [comment]
Which time extension do you refer to?

**Comment by Barma-lej** [comment]
timeextension - Set time extension. Extension in % ranging from -100 to 100

**Comment by Barma-lej** [comment]
![image](https://github.com/MTrab/landroid_cloud/assets/34010886/98d998c6-6e16-4421-8f77-c3efac1b17e4)

**Comment by Barma-lej** [comment]
![image](https://github.com/MTrab/landroid_cloud/assets/34010886/e646c09c-0120-49e8-a71d-34331fd97f29)

**Comment by MTrab** [comment]
Will see what I can do - it's not available on newer version mowers, only the ones with the old API.

Also - should be a sensor and not an attribute
