### ISSUE TITLE
Serial and Mac address not visible/available

### ISSUE THREAD

**Issue by InvertedMinor** [MTrab/landroid_cloud#50]
After the update to 1.6.3 the new features as announced are not visible.

![Screenshot 2020-08-06 at 21 11 09](https://user-images.githubusercontent.com/37710269/89572464-6a7c2100-d829-11ea-95ea-c9fde1d4aed7.png)

A restart did not help, any suggestions?

**Comment by MTrab** [comment]
Hmmm - strange. Will look into why it's not showing.

**Comment by MTrab** [comment]
Doh - minor error. Will push a new release shortly.
