### ISSUE TITLE
Wrong translation in de.json

### ISSUE THREAD

**Issue by Cosmicbase** [MTrab/landroid_cloud#502]
### Describe the issue

"entity": {
        "lawn_mower": {
            "landroid_cloud": {
                "state": {
                    "edgecut": "Kantenschnitt",
                    "escaped_digital_fence": "Außerhalb der Begrenzung",
                    "initializing": "Initialisierung",
                    "mowing": "Mähen",
                    "offline": "Offline",
                    "rain_delay": "Regenverzögerung",
                    "returning": "Rückkerh zur Ausgangsposition",   
                    "searching_zone": "Begrenzung suchen",
                    "starting": "Startet",
                    "zoning": "Suche Mähbereich"****

### What version of Home Assistant Core has the issue?

2024.1.5

### What was the last working version of Home Assistant Core?

2024.1.5

### What version of the Landroid Cloud integration do you have installed

v4.0.0

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

Landroid M500 (WR141E) Firmware: 3.32.0+1

### Diagnostics information (NOT log entries!)

[config_entry-landroid_cloud-5347425cf0463f06f31bed7b9f902102.json (1).txt](https://github.com/MTrab/landroid_cloud/files/14063456/config_entry-landroid_cloud-5347425cf0463f06f31bed7b9f902102.json.1.txt)

### Relevant log entries

```txt
None
```

### Additional information

The correct translation or spelling would be "returning": ""Rückkehr zur Ausgangsposition"",

**Comment by MTrab** [comment]
Translations are maintained by users, using this link: https://app.lokalise.com/public/38508561643d2bcfb05550.72266746/
