### ISSUE TITLE
Wrong last_update date

### ISSUE THREAD

**Issue by OhSoGood** [MTrab/landroid_cloud#51]
Hi,

Using the latest landroid_cloud version (the one of August 6th, 2020), I get a wrong last_update value within sensor.landroid_mower_status. My HomeAssistant seems to correctly report the date and hour today, but sensor.landroid_mower_status.last_update reports 00:47:39 19/05/2019 (I'm in Europe/Paris CEST timezone, using French date format if that matters).

What could be wrong?

**Comment by MTrab** [comment]
The date are as reported by the Worx API - the integration doesn't alter the data.

**Comment by OhSoGood** [comment]
Indeed, you're right, I checked the json data received over internet, it actually contains the wrong data. Any idea how this is possible?

**Comment by MTrab** [comment]
No idea

**Comment by OhSoGood** [comment]
Indeed, you're right, I checked the json data received over internet, it actually contains the wrong data. Any idea how this is possible?

**Comment by OhSoGood** [comment]
I'll try to escalate if that can interest other users. Else we may close the ticket, as you prefer.

**Comment by OhSoGood** [comment]
Ok, subject closed. I rebooted twice the mower, and the date and time are correct now.
