### ISSUE TITLE
Service landroid_cloud.partymode missing

### ISSUE THREAD

**Issue by floschibo** [MTrab/landroid_cloud#513]
### Describe the feature you wish to make a request for

Thank you for this wonderful integration!

Today I updated the Spook integration and it now says me, there is a service (landroid_cloud.partymode) used that does not exist. I don't know how long this service is not available, but will it come back? Or is there another possibility to set the party mode? Maybe I missed it.

Thanks

**Comment by MTrab** [comment]
As mentioned in the release notes this service is gone and is replaced by an entity

**Comment by floschibo** [comment]
Entity was deactivated and I wasn't able to find it. Thanks for the hint.
