### ISSUE TITLE
service landroid_cloud.partymode unavailable

### ISSUE THREAD

**Issue by Chacsam** [MTrab/landroid_cloud#522]
### Describe the issue

After I rainy winter I resolved to put out my Landroid M
It came back all fine in Home Assistant with the exception of the "landroid_cloud.partymode" service.
I have a switch on my dashboard that did work fine last year, but claims service isn't available.

It doesn't seem to be in the list of services either (even if I scroll down)

![image](https://github.com/MTrab/landroid_cloud/assets/28670803/317df478-3f94-42cb-aad6-33da2c3f555a)

### What version of Home Assistant Core has the issue?

core-2024.3.0

### What was the last working version of Home Assistant Core?

core-2023.10.something

### What version of the Landroid Cloud integration do you have installed

4.0.2

### What type of installation are you running?

Home Assistant Container

### Which make and model is the mower used for this integration?

Landroid M500 (WR165E)

### Diagnostics information (NOT log entries!)

    "landroid_cloud": {
      "version": "4.0.2",
      "requirements": [
        "pyworxcloud==4.1.7"
      ]
    },

### Relevant log entries

```txt
none
```

**Comment by MTrab** [comment]
As mentioned in breaking changes, it's now an entity and no longer a service
