### ISSUE TITLE
Setup component fejl efter 0.117.1

### ISSUE THREAD

**Issue by MrGravgaard** [MTrab/landroid_cloud#53]
Jeg får en fejl på min landroid_cloud efter opgradering til 0.117.1:

Logger: homeassistant.setup
Source: custom_components/landroid_cloud/__init__.py:264
First occurred: 10.40.43 (1 occurrences)
Last logged: 10.40.43

Error during setup of component landroid_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/landroid_cloud/__init__.py", line 126, in async_setup
    await api.async_force_update()
  File "/config/custom_components/landroid_cloud/__init__.py", line 264, in async_force_update
    await self._hass.async_add_executor_job(self._client.getStatus)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/pyworxcloud/__init__.py", line 152, in getStatus
    self._decodeData(status)
  File "/usr/local/lib/python3.8/site-packages/pyworxcloud/__init__.py", line 158, in _decodeData
    self.rssi = data['dat']['rsi']
KeyError: 'dat'

Det betyder at landroid_cloud ikke vil starte op. 
Jeg har opdateret til seneste version af landroid_cloud filerne. 

System Information:
arch | x86_64
-- | --
chassis | desktop
dev | false
docker | true
docker_version | 19.03.13
hassio | true
host_os | Ubuntu 16.04.7 LTS
installation_type | Home Assistant Supervised
os_name | Linux
os_version | 4.15.0-118-generic
python_version | 3.8.6
supervisor | 2020.10.1
timezone | Europe/Copenhagen
version | 0.117.1
virtualenv | false

**Comment by MTrab** [comment]
Det er med stor sandsynlighed fordi din Landroid er slukket.
Har desværre ikke længere selv have og Landroid, så skal lige have fundet ud af hvordan jeg får rettet den bug.

**Comment by CubieMedia** [comment]
Had the same problem in home assistant. Then tested with the landroid app and it also had problems (wrong serial number).

After restarting the landroid and also the charging station it works again!

Thank you for the feedback!

**Comment by mhaack** [comment]
I'm getting the same problem here as well, but in my case, I think it is related to the fact the mower is switched off for some days now. I checked the Landroid API, the device status call returns an empty JSON object, just `{}` for my mower.

**Comment by CubieMedia** [comment]
You stand correct! Worx changed something with their cloud and the data was missing until the mower logged in again.

Hope the data stays persistant for an offline mower over winter.

**Comment by GSzabados** [comment]
@MTrab, I've ran into the same issue as all the above. My lawnmower is turned off as well for the winter. Could be some exception added if the landroid cloud sends some unexpected reply, like an empty JSON as @mhaack saw it.

I will wake up tomorrow the mower from its winter sleep and see is it resolves the issue or not, but indeed I had to log in to the Landroid app and it couldn't get any information from the mower, just its name and serial number what is probably stored permanently in the account.

**Comment by GSzabados** [comment]
I turned on the lawn mower yesterday in my cellar, where I put it for winter. I had to log in the Landroid app again, and I saw the invalid serial number error message as well.

Since that, the Landroid app recognized the lawn mower again, but I stuck with the HA integration, as the lawn mower couldn't get a GPS fix for the Where is My Landroid module, and I can see the following error message:

  File "/usr/local/lib/python3.8/site-packages/pyworxcloud/__init__.py", line 208, in _decodeData
    self.gps_latitude = data['dat']['modules']['4G']['gps']['coo'][0]
KeyError: 'gps'

**Comment by JurajNyiri** [comment]
I have tried reinstalling the component, restarting, replaced setup.py, restarted and now it worked.

**Comment by CubieMedia** [comment]
After my device is turned off again for a longer time and restarted (after update) i have the same error again.
The problem seems to be that worx removes values in their cloud after some time when the device has not been online.

I will open an issue in the pyworxcloud module where the error occures in the _decodeData Method.

**Comment by MTrab** [comment]
Great work - will review the changes one of the next days and release an update ASAP

**Comment by MTrab** [comment]
Fixed in version 1.6.5
