### ISSUE TITLE
Sensor for partymode cannot be exposed to Homekit

### ISSUE THREAD

**Issue by Phoenix-DH** [MTrab/landroid_cloud#532]
### Describe the issue

I want to include the switch.james_party_mode to my homekit bridge.
But unfortunatelly I cannot choose it in my homekit bridge.

Is there a possibility that this is blocked or is it an issue elsewhere?

In the meanwhile I updated to v4! Great work! Working pretty well until now. Thanks for that.

### What version of Home Assistant Core has the issue?

2024.3.1

### What was the last working version of Home Assistant Core?

-

### What version of the Landroid Cloud integration do you have installed

4.0.3

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

Landroid M500

### Diagnostics information (NOT log entries!)

-

### Relevant log entries

```txt
-
```

### Additional information

-

**Comment by MTrab** [comment]
Have no idea what homekit does or is or how it works.
This integration is for Home Assistant.

**Comment by Phoenix-DH** [comment]
That is clear. I have that integration running in my home assistant and want to expose the switch to Apple Home.
Then I can imagine that there is no block.

**Comment by MTrab** [comment]
Guess this is a Home Assistant question rather than a question for this integration.
The integration only creates sensors - what then happen to them is in the Home Assistant core code.
