### ISSUE TITLE
[FR]: Add entity for worktime in minutes

### ISSUE THREAD

**Issue by sithmein** [MTrab/landroid_cloud#536]
### Describe the feature you wish to make a request for

Currently `worktime_total` is the work time in hours. It's derived from the work time in minutes which is provided by pyworxcloud. The work time in HA should be provided in minutes instead (or at least additionally) since you can always derive the hours from the minutes but not vice-versa due to rounding.

**Comment by MTrab** [comment]
Rather than adding a new sensor, showing the same info as already available, wouldn't it be better to convert all the hour sensors to minutes?

**Comment by sithmein** [comment]
I agree that it would be better to have the current sensors report minutes. Personally I don't mind the breaking change since I only started using the integration recently. Not sure about the other users.

**Comment by Menama83** [comment]
Hello all, to begin thank you @MTrab for this great integration.
Like @sithmein, I'm interested to have this information to know exactly how many time the robot worked and to manage it precisely each day.
Maybe I'm wrong but the others sensors are less important in minutes.
However, To have a synthesis like using landroid card, it's interesting in hours. Is it possible to keep in hours and adding an attribute in minutes?

**Comment by KHV8** [comment]
Not sure what you try to obtain. If you look in the Landroid app, it is in hours, no decimals.

If you need a "daily total" or "last 7 days total", then use a simple sensor in HA, providing hours with a lot of decimals


sensor
 - platform: history_stats
    name: Roberto runtime 7d
    entity_id: lawn_mower.roberto
    state: "mowing"
    type: time
    end: "{{ now() }}"
    duration:
      days: 7

  - platform: history_stats
    name: Roberto runtime today
    entity_id: lawn_mower.roberto
    state: "mowing"
    type: time
    end: "{{ now() }}"
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"

**Comment by Menama83** [comment]
I want to know the worktime of the day in live.
I keep the worktime of the day before that I compare with the current. Then, I manage the worktime of the day depending of the temperature. In hours, it's not enough precise.
I hope I'm clear.

**Comment by sithmein** [comment]
The mower reports all timespans in minutes. The integration currently rounds them to hours. There are use cases for having it in minutes precision [1].
From my point of view there are three possibilities:

1. Change the existing entities from hours to minutes. This is a breaking change as @MTrab already pointed out.
2. Introduce additional entities for minutes. Creates some redundancy.
3. Add an attribute for minutes to the existing entity. Less redundant but will require additional template entities in some cases (e.g. for creating stats based on the attribute).


[1] I want to maintain a constant mowing time per week. If it rains on one day the mower should do more on the next day.

**Comment by MTrab** [comment]
As it looks right now, I'll be most into adding minutes as an attribute, and if some users need it as a sensor, it's pretty trivial to make a template sensor for that

But haven't fully decided yet

**Comment by KHV8** [comment]
> I want to know the worktime of the day in live. I keep the worktime of the day before that I compare with the current. Then, I manage the worktime of the day depending of the temperature. In hours, it's not enough precise. I hope I'm clear.

It is live and super precise, with multible decimals. Just done by HA, making it super flexible if you whant others timeperiods, like since 12.00 or alike.

**Comment by Menama83** [comment]
@KHV8 , can you explain how do you obtain the value of worktime with decimals? Thank you

**Comment by KHV8** [comment]
> but I have this message in logs

Your sensor is the same as mine, except for one thing, the start. I use.
start: "{{ now().replace(hour=0, minute=0, second=0) }}"

My full sensor looks like this, I do a "today" and a 7day.
`
sensor:
  - platform: history_stats
    name: Mila Luftrenser runtime today
    entity_id: switch.mila_luftrenser
    state: "on"
    type: time
    end: "{{ now() }}"
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"

  - platform: history_stats
    name: Peterplys luftrenser runtime today
    entity_id: fan.peterplys_luftrenser
    state: "on"
    type: time
    end: "{{ now() }}"
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
`

One question, how do you make it look nice. When I paste it looks like this, even I choose the "code" when pasting

**Comment by Menama83** [comment]
Yes, I have a file template_sensors.yaml with some sensors. So I don't understand my problem.

For your problem, Paste your text, then selct the text and click on code button.

**Comment by Menama83** [comment]
Blades Total On Time in minutes should be interesting too

**Comment by KHV8** [comment]
> Yes, I have a file template_sensors.yaml with some sensors

The history stats are a sensor and not a template. Hence, should not go in the sensor part of the configuration and not templates. If it is all in configuration.yaml, it should look like this

```
sensor:
  - platform: history_stats
    name: Roberto runtime 7d
    entity_id: lawn_mower.roberto
    state: "mowing"
    type: time
    end: "{{ now() }}"
    duration:
      days: 7

  - platform: history_stats
    name: Roberto runtime today
    entity_id: lawn_mower.roberto
    state: "mowing"
    type: time
    end: "{{ now() }}"
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
```

If you have a sensor.yaml file, then the sensor: should not be there

**Comment by KHV8** [comment]
> Blades Total On Time in minutes should be interesting too

This can only come from the integration.
