### ISSUE TITLE
[FR]: Localized error messages

### ISSUE THREAD

**Issue by fra87** [MTrab/landroid_cloud#539]
### Describe the feature you wish to make a request for

The Error Sensor (the one showing the possible error message, i.e. `sensor.xxx_error`) is not localized; I'd like it to be actually translated.

If you can implement it the usual way through Lokalise I can add the Italian translation for it

### Describe alternatives you've considered

I already added a template sensor with a bunch of `if ... else` to manually translate the strings, but having direct support for translated strings is much better, portable and future proof

**Comment by MTrab** [comment]
Great idea, I'll look into this for a future release

**Comment by MTrab** [comment]
Translations can now be done in Lokalise (see the link in ReadMe)

**Comment by fra87** [comment]
Great :) I translated the new keys (except HBI, since I don't know what it is)

Great work as usual
