### ISSUE TITLE
Error on thursday_start

### ISSUE THREAD

**Issue by NIcozozo57** [MTrab/landroid_cloud#540]
### Describe the issue

in translation json files fr.json, fr_FR.json and en.json for thursday_start
 "thursday_start": {
                    "description": "Starting time for thursdays",
                    "name": "Wednesday, Start"
should be : Thursday ....

### What version of Home Assistant Core has the issue?

2024.3.3

### What version of the Landroid Cloud integration do you have installed

4.0.3

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

Landroid  WR167E

### Diagnostics information (NOT log entries!)

in translation json files fr.json, fr_FR.json and en.json for thursday_start
 "thursday_start": {
                    "description": "Starting time for thursdays",
                    "name": "Wednesday, Start"
should be : Thursday ....

### Relevant log entries

```txt
not needed
```

### Additional information

in translation json files fr.json, fr_FR.json and en.json for thursday_start
 "thursday_start": {
                    "description": "Starting time for thursdays",
                    "name": "Wednesday, Start"
should be : Thursday ....

**Comment by MTrab** [comment]
Confirmed - seems like I made an error in the texts.

**Comment by MTrab** [comment]
Translations can now be corrected in Lokalise, following the link in the readme
