### ISSUE TITLE
The robotic-mower Blades Current On Time sensor not updated

### ISSUE THREAD

**Issue by Menama83** [MTrab/landroid_cloud#541]
### Describe the issue

The robotic-mower Blades Current On Time sensor is not updated

### What version of Home Assistant Core has the issue?

core-2024.3.3

### What version of the Landroid Cloud integration do you have installed

v4.0.3

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

L800 WR148E

### Diagnostics information (NOT log entries!)

-

### Relevant log entries

```txt
-
```

### Additional information

-

**Comment by MTrab** [comment]
Please update to v4.0.4 and check if this fixes this issue

**Comment by Menama83** [comment]
I did it, it seems to work, thanks a lot
