### ISSUE TITLE
Can't create automation.

### ISSUE THREAD

**Issue by Suschibomber** [MTrab/landroid_cloud#555]
### Describe the issue

Hi I don't know if I'm stupid but I've been trying to create an automation for my M700 for a while but can't find the status under the automations to start the Robi or trigger an edge cut?

Could it be a bug and I need to set up the Landroid again somehow? I see all the values like battery, RSSI etc. but I don't see any entity with which I can get the M700 to start.

I can only turn the party mode on or off in automations.

At the same time I have another question:
I have built a garage with electric roller doors for my Landroid. These should logically open just before mowing so that it can drive out. Is it possible to get the time of the next planned start and then control the roller shutters?

### What version of Home Assistant Core has the issue?

2024.4.0

### What was the last working version of Home Assistant Core?

/

### What version of the Landroid Cloud integration do you have installed

Newest

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

M700

### Diagnostics information (NOT log entries!)

/

### Relevant log entries

```txt
/
```

**Comment by MTrab** [comment]
It's basic service calls for the lawn_mower platform, ie. lawn_mower.start
For the edgecut, it's called landroid_cloud.edgecut

**Comment by Suschibomber** [comment]
Sorry for my stupidity and thank you very much. And how can I drive to a specific zone? What is the service call for this?
