### ISSUE TITLE
Party Mode Switch not working

### ISSUE THREAD

**Issue by krkuhlmann** [MTrab/landroid_cloud#561]
### Describe the issue

Currently the Switch for Party Mode seems just to work one way. Using the Worx Landroid Android App to toggle the Party Mode just works fine and ist shown in Home Assistant immediately. 
But using the Switch in Home Assistant to turn Party Mode to ON just does nothing, even the Switch in Home Assistant gets directly back to it's old state, OFF. If Party Mode was enabled using Landroid App it can be switched OFF using Home Assistant, which is kind of strange.

### What version of Home Assistant Core has the issue?

2024.3.3

### What was the last working version of Home Assistant Core?

-

### What version of the Landroid Cloud integration do you have installed

4.0.5

### What type of installation are you running?

Home Assistant Container

### Which make and model is the mower used for this integration?

Worx Landroid L1000

### Diagnostics information (NOT log entries!)

-

### Relevant log entries

```txt
None
```

### Additional information

-

**Comment by MTrab** [comment]
Could you please try if it works in version 4.0.4?
I introduced a change in 4.0.5 that I didn't have any chance of testing

**Comment by MTrab** [comment]
Okay, I'll push a change soon, to revert the change then
