### ISSUE TITLE
Problem when re-installing

### ISSUE THREAD

**Issue by casperse** [MTrab/landroid_cloud#57]
Hi MTrab!

I really really love this integration, but because of some errors (Related to another plugin)
I had to remove it and re.-install it again?

But no matter what I do I cant get the "Landroid_cloud" back on my integration page?
I have tried this:
If upgrading from version lower than 1.4, please comment out the landroid_cloud section from configuration.yaml, restart Home Assistant, reinsert the landroid_cloud section and restart again.

I also looked and I only have these 3 sensors somehow kepth from the old installation:
![image](https://user-images.githubusercontent.com/2026859/110127855-65368300-7dc6-11eb-9c3e-9b82c965a285.png)

I have removed it from the "custom_components" folder 10 times
Something from the old installation is stopping it working when installing it again?

Do you have any suggestion to what I can try next?

**Comment by MTrab** [comment]
Turn on your landroid ;)

**Comment by casperse** [comment]
LOL its running cutting as we speak :-)
![image](https://user-images.githubusercontent.com/2026859/110133809-07f20000-7dcd-11eb-995c-ad0b35c503ef.png)
The integration is running the latest version in HAC
![image](https://user-images.githubusercontent.com/2026859/110133880-193b0c80-7dcd-11eb-8464-a27425afac22.png)
All files are in the folder: (I also tried to do it manually)
![image](https://user-images.githubusercontent.com/2026859/110133993-3a036200-7dcd-11eb-8a6f-6c9e5da88c9e.png)
The sensors that are getting data from the 3 sensors only:
![image](https://user-images.githubusercontent.com/2026859/110134337-8fd80a00-7dcd-11eb-8921-e662c0856c79.png)
For some reason I dont have any integration on my integration page:
![image](https://user-images.githubusercontent.com/2026859/110134567-d168b500-7dcd-11eb-8514-353024f165b0.png)
Anyway to install it manually here? Havent found it when going through the list of available plugins
I have forgotten to do something that I did the last time?

Again hope you can help me I have spend days trying to get it working again!
Setting up Z-wave and Zigbee was childplay comparing to this mystic problem (I am a NOOB)

**Comment by casperse** [comment]
And the account is not blocked.... (I have also tried to re-pair it again)
since it remembers these 3 sensors is there anyway to delete them and start all over?
Something is blocking this re-installation?
Thanks

**Comment by casperse** [comment]
Ok I found the 3 sensors they where leftovers from the UI YAML located in #  packages: !include_dir_named packages
I have removed all trace of the https://github.com/Barma-lej/halandroid
I have removed that dir and the YAML for the lovelace card and now the last 3 sensors are gone :-)

So only the HAC install but for some reason it doesn't create the sensors or the automations?
Anyway to force the local IP? for now I only have the documented:

  - email: !secret landroid_mail
    password: !secret landroid_pass

But it doesn't trigger any creation or detection of the Landroid?
(I have a fixed local  IP) and my app is working so the cloud is connected and working
I did find an error in the local IP adress for the UI but that isnt used in this integration only the cloud right?

**Comment by rosscullen** [comment]
@casperse you won't find Landroid_cloud in HA Integrations (as per your screenshot)... it will be in HACS -> Integrations. EG: http://[IP]:8123/hacs/integrations

Also what is the name of the mower in the Landroid App? This will need to match the name in

**Comment by casperse** [comment]
before when I had it working I had a worx square under integration showing a worx integration after installing the HAC integrations?
But that might have changed? anyway I have come to the conclusion that after installing the Landroid_cloid in HA it does create and download the files to the right folder... But it dosen create the sensors and automations? and I have no log files to indicate that anything is wrong

**Comment by casperse** [comment]
Ok - I will close this
I ended up taking a old snapshot that had the old integration working and copying all the files to my existing HA and it now works! Maybe some files was corrupt, or read/write pc format? - Honestly I have been trying so many things and spend a whole day on this! so maybe its the sum of them? LOL anyway thanks for helping (I am sure I had the integration icon last year)
