### ISSUE TITLE
Typo in number.[mower]_time_extention entity_id

### ISSUE THREAD

**Issue by Barma-lej** [MTrab/landroid_cloud#583]
### Describe the issue

There is a typo in number.[mower]_time_exten**t**ion entity_id
https://github.com/MTrab/landroid_cloud/blob/2bc2f357bb596968adcdd604836b3d95c0ba946a/custom_components/landroid_cloud/number.py#L19
https://github.com/MTrab/landroid_cloud/blob/2bc2f357bb596968adcdd604836b3d95c0ba946a/custom_components/landroid_cloud/number.py#L20

### What version of Home Assistant Core has the issue?

-

### What version of the Landroid Cloud integration do you have installed

latest

### What type of installation are you running?

Home Assistant Supervised

### Which make and model is the mower used for this integration?

m500

### Diagnostics information (NOT log entries!)

-

### Relevant log entries

```txt
-
```

**Comment by MTrab** [comment]
What typo? Seems good to me

**Comment by Barma-lej** [comment]
ExtenSion or ExtenTion?
