### ISSUE TITLE
set Zone not working

### ISSUE THREAD

**Issue by gost4711** [MTrab/landroid_cloud#590]
### Describe the issue

When I want to set a zone I get the following message. Setting Zone 1 works.
"Fehler beim Aufrufen des Diensts select/select_option. Cannot request this zone as it is not defined"
Two zones are defined.
In the log I see that an attempt is made to switch to zone 21. Or am I misunderstanding something?

### What version of Home Assistant Core has the issue?

2024.4.3

### What version of the Landroid Cloud integration do you have installed

5.0.2

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

Worx Landroid L1000 (WR147E.1)

### Diagnostics information (NOT log entries!)

Gartenfreund wechselte zu Startet
20:16:31 - Vor 32 Minuten
Gartenfreund Last Update wechselte zu 21. April 2024 um 20:16
20:16:31 - Vor 32 Minuten
Gartenfreund Last Update wechselte zu 21. April 2024 um 20:15
20:15:50 - Vor 33 Minuten
Gartenfreund Party Mode eingeschaltet ausgelöst durch Dienst Schalter: Einschalten
20:15:15 - Vor 33 Minuten - Goetz
Gartenfreund Last Update wechselte zu 21. April 2024 um 20:15
20:15:15 - Vor 33 Minuten
Gartenfreund Last Update wechselte zu 21. April 2024 um 20:14
20:14:00 - Vor 34 Minuten
Gartenfreund Party Mode ausgeschaltet
20:12:41 - Vor 35 Minuten
Gartenfreund Last Update wechselte zu 21. April 2024 um 20:12
20:12:41 - Vor 35 Minuten
Gartenfreund Party Mode eingeschaltet ausgelöst durch Dienst Schalter: Einschalten
20:12:30 - Vor 36 Minuten - Goetz
Gartenfreund Last Update wechselte zu 21. April 2024 um 20:12
20:12:30 - Vor 36 Minuten
Gartenfreund Current zone wechselte zu 1 ausgelöst durch Dienst Auswählen: Auswählen
20:11:16 - Vor 37 Minuten - Goetz
Gartenfreund Last Update wechselte zu 21. April 2024 um 20:11
20:11:16 - Vor 37 Minuten
Gartenfreund Party Mode ausgeschaltet
20:11:03 - Vor 37 Minuten
Gartenfreund Last Update wechselte zu 21. April 2024 um 20:11
20:11:03 - Vor 37 Minuten
Gartenfreund Last Update wechselte zu 21. April 2024 um 20:10
20:10:10 - Vor 38 Minuten
Gartenfreund Current zone wechselte zu 2
20:06:58 - Vor 41 Minuten
Gartenfreund Last Update wechselte zu 21. April 2024 um 20:06
20:06:58 - Vor 42 Minuten
Gartenfreund Current zone wechselte zu 1 ausgelöst durch Dienst Auswählen: Auswählen

### Relevant log entries

```txt
Logger: homeassistant.components.websocket_api.http.connection
Quelle: components/websocket_api/commands.py:239
Integration: Home Assistant WebSocket API (Dokumentation, Probleme)
Erstmals aufgetreten: 17:35:06 (14 Vorkommnisse)
Zuletzt protokolliert: 20:44:27

[140584942862784] Cannot request this zone as it is not defined.
[140585119899840] Cannot request this zone as it is not defined.
[140584802491712] Cannot request this zone as it is not defined.
[140584801688000] Cannot request this zone as it is not defined.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2543, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2580, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 971, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1043, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 195, in async_handle_select_option
    await self.async_select_option(option)
  File "/config/custom_components/landroid_cloud/device_base.py", line 890, in async_select_option
    self.entity_description.command_fn(self._api, str(int(option) - 1))
  File "/config/custom_components/landroid_cloud/select.py", line 23, in <lambda>
    command_fn=lambda api, value: api.cloud.setzone(
                                  ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyworxcloud/__init__.py", line 924, in setzone
    raise ZoneNotDefined("Cannot request this zone as it is not defined.")
pyworxcloud.exceptions.ZoneNotDefined: Cannot request this zone as it is not defined.
```

**Comment by MTrab** [comment]
Seems like a duplicate of #585
