### ISSUE TITLE
cannot set up

### ISSUE THREAD

**Issue by mihauu1983** [MTrab/landroid_cloud#596]
### Describe the issue

I get error: failed to set up

### What version of Home Assistant Core has the issue?

version | core-2024.4.4

### What version of the Landroid Cloud integration do you have installed

5.0.2

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

Landroid WR141E

### Diagnostics information (NOT log entries!)

none

### Relevant log entries

```txt
Logger: homeassistant.config_entries
Source: config_entries.py:551
First occurred: 10:55:33 AM (5 occurrences)
Last logged: 12:55:53 PM

Error setting up entry Worx -****@***.com for landroid_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 551, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/landroid_cloud/__init__.py", line 64, in async_setup_entry
    result = await _async_setup(hass, entry)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/landroid_cloud/__init__.py", line 219, in _async_setup
    await asyncio.gather(
  File "/config/custom_components/landroid_cloud/__init__.py", line 237, in async_init_device
    api = LandroidAPI(hass, name, entry)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/landroid_cloud/api.py", line 73, in __init__
    self.logger.log(LoggerType.API, "Device: %s", self.cloud.devices[device_name])
  File "/config/custom_components/landroid_cloud/utils/logger.py", line 90, in log
    else "("
         ^^^
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by MTrab** [comment]
Looks like the integration cannot retreive the device name from the API.

Can you please go to https://diagnostics.trab.dk/landroid_cloud and enter the details to email the diagnostics to me for further investigation?

**Comment by mihauu1983** [comment]
I solved this problem. I've given a name for my lawnmower in Landroid app and it immediately solved this issue.

**Comment by mihauu1983** [comment]
I solved this problem. I've given a name for my lawnmower in Landroid app and it immediately solved this issue.
