### ISSUE TITLE
Torque settings  fails: manual reboot  required

### ISSUE THREAD

**Issue by matteocostantini** [MTrab/landroid_cloud#597]
### Describe the issue

What s the meaning of this feature, im not find in app for my vision L. I want to test but i i touch this settings i. Must reboot my robot (connection lost)

### What version of Home Assistant Core has the issue?

2024.4.2

### What version of the Landroid Cloud integration do you have installed

5.0.2

### What type of installation are you running?

Home Assistant Supervised

### Which make and model is the mower used for this integration?

Vision l1600 

### Diagnostics information (NOT log entries!)

Connection lost

### Relevant log entries

```txt
…
```

**Comment by MTrab** [comment]
Should be working on Landroid Vision models.
As it indicates, it's intended to adjust the drive motor torque.

Cannot say why it makes the device go offline though - you haven't attached the diagnostics file, as requested so it's pretty hard to investigate further.

**Comment by matteocostantini** [comment]
I have 2 vision in my account m600 e l1600, from different routers/ locations.The have same behavior, wifi connection is persistent (i check from my fritz) but message queue is missed. "Landroid out of wifi range is the message. ("Landroid fuori copertura " in italiano)

**Comment by MTrab** [comment]
As a temporary fix, I'll disable the entity until I have a proper fix for this
