### ISSUE TITLE
Integration with Landroid failed to initialize

### ISSUE THREAD

**Issue by johnhughbowen** [MTrab/landroid_cloud#60]
Hi Ross

I installed Manually into HACS, as for me the integration cannot be found. Both HACSand the code are the latest versions as of yesterday

**The error I get is**

Logger: homeassistant.setup
Source: setup.py:163
First occurred: 9:13:36 (1 occurrences)
Last logged: 9:13:36

Setup failed for landroid_cloud: Integration failed to initialize.
******************************

Home Assistant version:  core-2021.4.4 - Home Assistant OS 5.13
Hardware: Intel NUC Frost Canyon - Intel i3-10110U 8GB Mem
Landroid model: WR142E
Is it working ok on landroid native app: Yes
Copy of your configuration.yaml
landroid_cloud:
  - email: myemail@gmail.com
    password: ****** (15 chars upper and lower case with ! chars)
Manual install or via HACS: Manual

Any help greatly appreciated

**Comment by johnhughbowen** [comment]
Thank-you, Thank-you

This time I also get

Logger: custom_components.landroid_cloud
Source: custom_components/landroid_cloud/__init__.py:113
Integration: landroid_cloud (documentation, issues)
First occurred: 15:56:41 (1 occurrences)
Last logged: 15:56:41

Error in authentication!

I reset my password and added it to the configuration and everything works.
Really appreciate your help

Kind Regards

John

*John Bowen | Managing Director - MediaConcepts Pte Ltd | T. +65 3138 3829
| M. +44 (0)7446760120 | ***@***.**** ***@***.***>

*Blk 2 Balestier Road, #04-661, Singapore 320002 This email message and any
accompanying attachments may contain information that is confidential and
is subject to legal privilege. If you are not the intended recipient, do
not read, use, disseminate, distribute or copy this message or attachments.
If you have received this message in error, please notify the sender
immediately and delete this message. Any views expressed in this message
are those of the individual sender, except where the sender expressly, and
with authority, states them to be the views of MediaConcepts. Before
opening any attachments, please check them for viruses and defects.*

**Comment by rosscullen** [comment]
@johnhughbowen no pressure but if you're feeling generous, buy @MTrab a coffee!
https://www.buymeacoffee.com/mtrab

**Comment by ludwigscholer88** [comment]
Protokolldetails (FEHLER)
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht
Logger: homeassistant.config_entries
Source: custom_components/landroid_cloud/__init__.py:208
Integration: Landroid Cloud ([documentation](https://github.com/MTrab/landroid_cloud/blob/master/README.md), [issues](https://github.com/MTrab/landroid_cloud/issues))
First occurred: 17:26:13 (2 occurrences)
Last logged: 17:30:33

Error setting up entry Worx - info@ludwigscholer.de for landroid_cloud

Any ideas?

**Comment by roofburner** [comment]
Please follow https://github.com/MTrab/landroid_cloud/issues/282
