### ISSUE TITLE
torque missing

### ISSUE THREAD

**Issue by robberburn** [MTrab/landroid_cloud#611]
### Describe the issue

since 5.04 the entity "torque" is missing

### What version of Home Assistant Core has the issue?

2024.5.2

### What was the last working version of Home Assistant Core?

2024.5.2

### What version of the Landroid Cloud integration do you have installed

5.03

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

M700

### Diagnostics information (NOT log entries!)

None

### Relevant log entries

```txt
None
```

**Comment by MTrab** [comment]
Correct: https://github.com/MTrab/landroid_cloud/releases/tag/v5.0.3
