### ISSUE TITLE
[FR]: number.robby_torque not accessible

### ISSUE THREAD

**Issue by Bailey0721** [MTrab/landroid_cloud#613]
### Describe the feature you wish to make a request for

number.robby_torque is no longer accessible, so there is currently no way to set the torque. A few days ago, this was still possible without any problems. Will this function come back, or will there be a new entity?

**Comment by MTrab** [comment]
Check release notes

**Comment by Bailey0721** [comment]
Can you help me? Where can I find the Relasenotes? Is a downgrade possible?

**Comment by MTrab** [comment]
https://github.com/MTrab/landroid_cloud/releases

Fowngradew are never advisable

**Comment by Bailey0721** [comment]
Thank you very much, I already knew this release note. I was hoping there would be a PDF with a complete RN. It's always tedious this way, as you have to search through everything individually. But thank you very much for the quick feedback !!!
