### ISSUE TITLE
INFO.md states the project is not maintained

### ISSUE THREAD

**Issue by Strixx76** [MTrab/landroid_cloud#618]
### Describe the issue

Badge in `INFO.md` says the project is not maintained since 2022.

### What version of Home Assistant Core has the issue?

2024.4.4

### What version of the Landroid Cloud integration do you have installed

v5.0.4

### What type of installation are you running?

Home Assistant Container

### Which make and model is the mower used for this integration?

Landroid M500

### Diagnostics information (NOT log entries!)

None

### Relevant log entries

```txt
None
```

**Comment by MTrab** [comment]
Removed as it isn't used
