### ISSUE TITLE
Sensor with the whole MQTT JSON

### ISSUE THREAD

**Issue by johngianni** [MTrab/landroid_cloud#623]
### Describe the feature you wish to make a request for

I was looking to create some advanced statistics in home assistant and I wanted to use some info stored in the Positech API MQTT JSON message, not managed by Landroid Cloud. So I had to implement a docker container to run a script using the pyworxcloud library that is sending the original MQTT to the MQTT server of HA and then use Node Red to manipulate it. I see that pyworxcloud has a variable (last_status) that is containing the whole json. Would it be possible to have it in a sensor managed by the Landroid Cloud Integration, so that I can simplify my logic, please?
Thank you.

**Comment by MTrab** [comment]
Sensors cannot have more than 256 chars, so that request would be pretty impossible to fulfil.
Rather make requests for whatever sensors you are missing.
