### ISSUE TITLE
pyworxcloud getStatus() ever 30 minutes

### ISSUE THREAD

**Issue by avanc** [MTrab/landroid_cloud#63]
First of all thanks for separating the Worx communication (pyworxcloud) from the Home Assistant component.
This make it feasible for me to create a plain MQTTbridge.

While I'm working on it, I wonder why this component does a getStatus() every 30 minutes. From my observations I get an update every 10 minutes from the Worx broker. What is the benefit for explicitly request updated data every 30 minutes?

**Comment by MTrab** [comment]
If you request too frequent updates you'll be banned from Worx and need to relink your device.
Perhaps 30 minutes is too defensive, it's just my experience that more frequent updates will result in a ban.

And a friend (who are working in Worx support department) said to me not request updates more frequent than every 30 minutes.

I'm working on getting push update up and running - that should result in a more up-to-date status, as Worx servers then push the update - but that's not in a planned release yet, as I struggle to make it reliable.

**Comment by avanc** [comment]
I wasn't specific: I get updates every 10 minutes although I _don't_ call getStatus() (only once on startup).

**Comment by MTrab** [comment]
Oh - I misunderstood.

The getStatus call every 30 minutes are merely to ensure that at least every 30 minutes the status will be forced to update.
