### ISSUE TITLE
Landroid Cloud entities not available

### ISSUE THREAD

**Issue by ThorPrez** [MTrab/landroid_cloud#638]
### Describe the issue

Just installed the integration, cloud connection is working, because both mowers were shown.
But I haven´t any entities und the mowers are shown as offline.

### What version of Home Assistant Core has the issue?

2024.5.5

### What version of the Landroid Cloud integration do you have installed

v5.0.5

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

Worx Landroid M500 (WR141E)

### Diagnostics information (NOT log entries!)

[home-assistant_landroid_cloud_2024-06-04T20-19-06.830Z.log](https://github.com/user-attachments/files/15570014/home-assistant_landroid_cloud_2024-06-04T20-19-06.830Z.log)

### Relevant log entries

```txt
none
```

### Additional information
Those services are shown:
![landroid_cloud_services](https://github.com/MTrab/landroid_cloud/assets/33800583/9df6c94a-8150-4ab1-8648-2781b21e23a4)
As you can see, entities not available:
![landroid_entities](https://github.com/MTrab/landroid_cloud/assets/33800583/8998e51a-2ca6-4138-8fec-cee925f195bc)

**Comment by MTrab** [comment]
Looking at the logs, everything should be fine, but you haven't attached debug info - could you please do that?

**Comment by RaunoVV** [comment]
Have had same issues, sometime reloading integration account entity helps but not always.

**Comment by ThorPrez** [comment]
Hi. Sorry for late response, was out of contry for a while.
Which debug info ? The logfile was generated with enabled debug info.

**Comment by ThorPrez** [comment]
Hi. Sorry for late response, was out of contry for a while.
Which debug info ? The logfile was generated with enabled debug info.
