### ISSUE TITLE
The custom integration 'landroid_cloud' does not have a valid version key (None) in the manifest file and was blocked

### ISSUE THREAD

**Issue by MrGravgaard** [MTrab/landroid_cloud#65]
In version 2021.6.1 I get this: 

2021-06-04 10:02:18 ERROR (SyncWorker_4) [homeassistant.loader] The custom integration 'landroid_cloud' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details

Which means that the integration does not start. 

But the version is there..:

{
  "domain": "landroid_cloud",
  "name": "Worx Landroid Cloud",
  "documentation": "https://github.com/MTrab/landroid_cloud/blob/master/README.md",
  "issue_tracker": "https://github.com/MTrab/landroid_cloud/issues",
  "requirements": ["pyworxcloud==1.2.22"],
  **"version": "1.6.6",**
  "codeowners": ["@MTrab"]
}

**Comment by doubledutch2** [comment]
Following - I have the same issue on my HA - 1.6.1

**Comment by MTrab** [comment]
No error reported on my prod and dev envs :(

**Comment by MrGravgaard** [comment]
I have actually downloaded the latest released from your github and reinstalled it. Didn't change anything. 
What do you need to investigate, Morten?

**Comment by MTrab** [comment]
Sorry - have no idea where to go from here.
Every test and check completes sucessfully.
