### ISSUE TITLE
[FR]: Statistiche non disponibili

### ISSUE THREAD

**Issue by ziopeppe94** [MTrab/landroid_cloud#650]
### Describe the feature you wish to make a request for

Dopo aggiornamento non si vedono le statistiche nella card

**Comment by MTrab** [comment]
Please write in english, I have no idea what you are writing

**Comment by ziopeppe94** [comment]
after updating to version 5.0.5, I cannot view the robot's stats on the card, for example the working time of the blades, the rain delay, the connection. they are enabled in the list of entities but I don't see them on the card, thanks for the reply

**Comment by MTrab** [comment]
Thisnis for the integration, not the card. If the entities show the data, then everything is fine

**Comment by ziopeppe94** [comment]
ok, but before I could see the entities on the card, do you have any idea how I can see them again?

**Comment by MTrab** [comment]
I have nothing to do with the card. Try contacting the creator of the card

**Comment by ziopeppe94** [comment]
thank you
