### ISSUE TITLE
Fully Kiosk Browser integration not displaying

### ISSUE THREAD

**Issue by JohnnyCarcinogen** [MTrab/landroid_cloud#666]
### Describe the issue

Recently the Landroid Card has disappeared from Fully Kiosk browser running on a Fire HD 10 panel. I've even tried adding the custom card back and it just shows a red "!". I don't know if this was caused by an update to the card/home assistant or fully kiosk.

### What version of Home Assistant Core has the issue?

core-2024.7.3

### What version of the Landroid Cloud integration do you have installed

v5.0.5

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

WR155

### Diagnostics information (NOT log entries!)

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.7.3",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.4",
    "docker": true,
    "arch": "x86_64",
    "timezone": "America/New_York",
    "os_name": "Linux",
    "os_version": "6.6.33-haos",
    "supervisor": "2024.06.2",
    "host_os": "Home Assistant OS 12.4",
    "docker_version": "26.1.4",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "weatheralerts": {
      "documentation": "https://github.com/custom-components/weatheralerts",
      "version": "0.1.5",
      "requirements": []
    },
    "switchbotremote": {
      "documentation": "https://github.com/KiraPC/ha-switchbot-remote#readme",
      "version": "1.0.0",
      "requirements": [
        "pyhumps"
      ]
    },
    "keymaster": {
      "documentation": "https://github.com/FutureTense/keymaster",
      "version": "v0.0.98",
      "requirements": []
    },
    "teamtracker": {
      "documentation": "https://github.com/vasqued2/ha-teamtracker",
      "version": "0.1",
      "requirements": [
        "arrow",
        "aiofiles"
      ]
    },
    "tplink_deco": {
      "documentation": "https://github.com/amosyuen/ha-tplink-deco",
      "version": "3.6.2",
      "requirements": [
        "pycryptodome>=3.12.0"
      ]
    },
    "mass": {
      "documentation": "https://music-assistant.io",
      "version": "2024.6.2",
      "requirements": [
        "music-assistant==2.0.6"
      ]
    },
    "govee": {
      "documentation": "https://github.com/LaggAt/hacs-govee/blob/master/README.md",
      "version": "2023.11.1",
      "requirements": [
        "govee-api-laggat==0.2.2",
        "dacite==1.8.0"
      ]
    },
    "mail_and_packages": {
      "documentation": "https://github.com/moralmunky/Home-Assistant-Mail-And-Packages",
      "version": "0.3.31",
      "requirements": [
        "beautifulsoup4",
        "Pillow>=9.0",
        "dateparser"
      ]
    },
    "jokes": {
      "documentation": "https://github.com/LaggAt/ha-jokes/blob/master/README.md",
      "version": "0.0.1",
      "requirements": []
    },
    "spotcast": {
      "documentation": "https://github.com/fondberg/spotcast",
      "version": "v3.6.30",
      "requirements": []
    },
    "tuya_openapi": {
      "documentation": "https://www.home-assistant.io/integrations/tuya",
      "version": "0.0.1",
      "requirements": [
        "tuya-iot-py-sdk==0.6.6"
      ]
    },
    "rpi_rf": {
      "documentation": "https://github.com/markvader/ha-rpi_rf",
      "version": "2022.9.0",
      "requirements": [
        "RPi.GPIO==0.7.1",
        "rpi-rf==0.9.7"
      ]
    },
    "landroid_cloud": {
      "documentation": "https://github.com/MTrab/landroid_cloud/blob/master/README.md",
      "version": "5.0.5",
      "requirements": [
        "pyworxcloud==4.1.14"
      ]
    },
    "switchbot": {
      "documentation": "https://www.home-assistant.io/integrations/switchbot",
      "version": "110275",
      "requirements": [
        "PySwitchbot==0.45.0"
      ]
    },
    "hacs": {
      "documentation": "https://hacs.xyz/docs/configuration/start",
      "version": "1.34.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "ble_monitor": {
      "documentation": "https://github.com/custom-components/ble_monitor",
      "version": "12.13.0",
      "requirements": [
        "pycryptodomex>=3.19.1",
        "janus>=1.0.0",
        "aioblescan>=0.2.14",
        "btsocket>=0.2.0",
        "pyric>=0.1.6.3"
      ]
    },
    "yahoofinance": {
      "documentation": "https://github.com/iprak/yahoofinance",
      "version": "1.2.10",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "landroid_cloud",
    "name": "Landroid Cloud",
    "after_dependencies": [
      "http"
    ],
    "codeowners": [
      "MTrab"
    ],
    "config_flow": true,
    "documentation": "https://github.com/MTrab/landroid_cloud/blob/master/README.md",
    "iot_class": "cloud_push",
    "issue_tracker": "https://github.com/MTrab/landroid_cloud/issues",
    "loggers": [
      "pyworxcloud"
    ],
    "requirements": [
      "pyworxcloud==4.1.14"
    ],
    "version": "5.0.5",
    "is_built_in": false
  },
  "setup_times": {
    "null": {
      "setup": 5.571398651227355e-05
    },
    "2bd3ecfeba1f99b8715d8d69980e5f97": {
      "wait_import_platforms": -5.730093741003657,
      "wait_base_component": -0.001322520023677498,
      "config_entry_setup": 9.106751182989683
    }
  },
  "data": {
    "entry": {
      "data": {
        "email": "**REDACTED**",
        "password": "**REDACTED**",
        "type": "Worx"
      },
      "disabled_by": null,
      "domain": "landroid_cloud",
      "entry_id": "2bd3ecfeba1f99b8715d8d69980e5f97",
      "minor_version": 1,
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "title": "**REDACTED**",
      "unique_id": "**REDACTED**",
      "version": 1
    },
    "cloud": {},
    "device_ids": {
      "Paranoid Landroid": null,
      "New 155": "e696a83a3c48bcee490553af4b21e40e"
    },
    "feature_bits": {},
    "type": "Worx",
    "devices": {
      "Paranoid Landroid": {
        "_api": {
          "__type": "<class 'pyworxcloud.api.LandroidCloudAPI'>",
          "repr": "<pyworxcloud.api.LandroidCloudAPI object at 0x7f267cdbec60>"
        },
        "mower": {
          "id": 390090,
          "uuid": "96c52e51-9c06-4002-8c6b-33acd285049e",
          "product_id": 55,
          "user_id": 376505,
          "serial_number": "2019308868030006772F",
          "mac_address": "98D863446CA0",
          "locked": true,
          "firmware_version": "3.26.0+1",
          "firmware_auto_upgrade": true,
          "sim": null,
          "test": false,
          "iot_registered": true,
          "mqtt_registered": true,
          "registered_at": "2020-10-03T00:00:00-04:00",
          "online": false,
          "protocol": 0,
          "pending_radio_link_validation": null,
          "capabilities": [
            "auto_lock",
            "border_cut",
            "digital_fence_settings",
            "follow_border",
            "lock",
            "mqtt",
            "multi_zone",
            "multi_zone_percentage",
            "one_time_scheduler",
            "ota_upgrade",
            "pairing_smartlink",
            "pause_over_border",
            "pause_over_wire",
            "rain_delay",
            "rain_delay_start",
            "safe_go_home",
            "scheduler_two_slots",
            "unrestricted_mowing_time"
          ],
          "capabilities_available": [
            "display_pairing_shortcut",
            "zone_keeper"
          ],
          "mqtt_endpoint": "iot.eu-west-1.worxlandroid.com",
          "mqtt_topics": {
            "command_in": "PRM100/98D863446CA0/commandIn",
            "command_out": "PRM100/98D863446CA0/commandOut"
          },
          "name": "Paranoid Landroid",
          "blade_height_shift": 0,
          "push_notifications": true,
          "push_notifications_level": "warning",
          "pin_code": null,
          "app_settings": null,
          "warranty_registered": true,
          "purchased_at": "2020-10-01T00:00:00-04:00",
          "warranty_expires_at": "2023-10-01T00:00:00-04:00",
          "setup_location": {
            "latitude": "**REDACTED**",
            "longitude": "**REDACTED**"
          },
          "city": {
            "id": 4621846,
            "country_id": 840,
            "name": "Farragut",
            "latitude": "**REDACTED**",
            "longitude": "**REDACTED**",
            "created_at": "2018-02-15T22:35:59-05:00",
            "updated_at": "2018-02-15T22:35:59-05:00"
          },
          "time_zone": "America/New_York",
          "lawn_size": 1218.5656738281,
          "lawn_perimeter": 119,
          "auto_schedule_settings": null,
          "auto_schedule": false,
          "improvement": true,
          "diagnostic": true,
          "distance_covered": 914706,
          "mower_work_time": 46376,
          "blade_work_time": 43337,
          "blade_work_time_reset": 0,
          "blade_work_time_reset_at": null,
          "battery_charge_cycles": 266,
          "battery_charge_cycles_reset": 0,
          "battery_charge_cycles_reset_at": null,
          "created_at": "2019-04-18T01:15:03-04:00",
          "updated_at": "2024-04-30T23:17:18-04:00",
          "last_status": null,
          "model": {
            "code": "WR150",
            "friendly_name": "Landroid L1500",
            "model_year": 2019,
            "cutting_width": 220
          }
        },
        "_tz": null,
        "id": 390090,
        "uuid": "96c52e51-9c06-4002-8c6b-33acd285049e",
        "product_id": 55,
        "serial_number": "2019308868030006772F",
        "mac_address": "98D863446CA0",
        "locked": true,
        "sim": null,
        "mqtt_registered": true,
        "registered_at": "2020-10-03T00:00:00-04:00",
        "online": false,
        "protocol": 0,
        "capabilities": {
          "__type": "<class 'pyworxcloud.utils.capability.Capability'>",
          "repr": "<pyworxcloud.utils.capability.Capability object at 0x7f267a159790>"
        },
        "capabilities_available": [
          "display_pairing_shortcut",
          "zone_keeper"
        ],
        "name": "Paranoid Landroid",
        "blade_height_shift": 0,
        "pin_code": null,
        "setup_location": {
          "latitude": "**REDACTED**",
          "longitude": "**REDACTED**"
        },
        "city": {
          "id": 4621846,
          "country_id": 840,
          "name": "Farragut",
          "latitude": "**REDACTED**",
          "longitude": "**REDACTED**",
          "created_at": "2018-02-15T22:35:59-05:00",
          "updated_at": "2018-02-15T22:35:59-05:00"
        },
        "time_zone": "America/New_York",
        "improvement": true,
        "diagnostic": true,
        "mower_work_time": 46376,
        "last_status": null,
        "model": "Landroid L1500 (WR150)",
        "battery": {
          "cycles": {
            "total": 0,
            "current": 0,
            "reset_at": null,
            "reset_time": null
          }
        },
        "blades": {
          "total_on": 43337,
          "reset_at": 0,
          "reset_time": null,
          "current_on": 43337
        },
        "chassis": {},
        "error": {
          "id": -1,
          "description": "unknown"
        },
        "orientation": {
          "pitch": 0,
          "roll": 0,
          "yaw": 0
        },
        "rainsensor": {
          "delay": 0
        },
        "status": {
          "id": -1,
          "description": "unknown"
        },
        "zone": {
          "current": 0,
          "index": 0,
          "indicies": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "starting_point": [
            0,
            0,
            0,
            0
          ]
        },
        "warranty": {
          "expires_at": "2023-10-01T00:00:00-04:00",
          "registered": true,
          "expired": true
        },
        "firmware": {
          "auto_upgrade": true,
          "version": "3.26.0+1"
        },
        "schedules": {
          "daily_progress": null,
          "next_schedule_start": null,
          "time_extension": 0,
          "active": true,
          "auto_schedule": {
            "settings": null,
            "enabled": false
          }
        },
        "in_topic": "PRM100/98D863446CA0/commandIn",
        "out_topic": "PRM100/98D863446CA0/commandOut",
        "_DeviceHandler__is_decoded": true
      },
      "New 155": {
        "_api": {
          "__type": "<class 'pyworxcloud.api.LandroidCloudAPI'>",
          "repr": "<pyworxcloud.api.LandroidCloudAPI object at 0x7f267cdbec60>"
        },
        "mower": {
          "id": 579855,
          "uuid": "96c5307c-8588-4002-a336-7b022b169950",
          "product_id": 68,
          "user_id": 376505,
          "serial_number": "2021309149030001875C",
          "mac_address": "E8DB840AA228",
          "locked": false,
          "firmware_version": "3.32.0+1",
          "firmware_auto_upgrade": true,
          "sim": {
            "id": 9329,
            "iccid": "8944538523018983141",
            "sim_status": "provisioned",
            "pending_activation": false,
            "contract_starts_at": "2021-12-08T00:00:00-05:00",
            "contract_ends_at": "2024-12-08T00:00:00-05:00",
            "created_at": "2021-12-08T16:59:21-05:00",
            "updated_at": "2024-07-22T06:01:06-04:00"
          },
          "test": false,
          "iot_registered": true,
          "mqtt_registered": true,
          "registered_at": "2021-12-08T00:00:00-05:00",
          "online": true,
          "protocol": 0,
          "pending_radio_link_validation": null,
          "capabilities": [
            "auto_lock",
            "bluetooth_control",
            "bluetooth_pairing",
            "border_cut",
            "digital_fence_settings",
            "follow_border",
            "lock",
            "mqtt",
            "multi_zone",
            "multi_zone_percentage",
            "one_time_scheduler",
            "ota_upgrade",
            "pairing_smartconfig",
            "pause_over_border",
            "pause_over_wire",
            "rain_delay",
            "rain_delay_start",
            "safe_go_home",
            "scheduler_two_slots",
            "unrestricted_mowing_time",
            "zone_keeper"
          ],
          "capabilities_available": [
            "display_pairing_shortcut"
          ],
          "mqtt_endpoint": "iot.eu-west-1.worxlandroid.com",
          "mqtt_topics": {
            "command_in": "PRM100/E8DB840AA228/commandIn",
            "command_out": "PRM100/E8DB840AA228/commandOut"
          },
          "name": "New 155",
          "blade_height_shift": 0,
          "push_notifications": true,
          "push_notifications_level": "warning",
          "pin_code": null,
          "app_settings": {
            "cellular_setup_completed": true
          },
          "warranty_registered": true,
          "purchased_at": "2023-03-01T00:00:00-05:00",
          "warranty_expires_at": "2026-03-01T00:00:00-05:00",
          "setup_location": {
            "latitude": "**REDACTED**",
            "longitude": "**REDACTED**"
          },
          "city": {
            "id": 4621846,
            "country_id": 840,
            "name": "Farragut",
            "latitude": "**REDACTED**",
            "longitude": "**REDACTED**",
            "created_at": "2018-02-15T22:35:59-05:00",
            "updated_at": "2018-02-15T22:35:59-05:00"
          },
          "time_zone": "America/New_York",
          "lawn_size": null,
          "lawn_perimeter": 168,
          "auto_schedule_settings": null,
          "auto_schedule": false,
          "improvement": true,
          "diagnostic": true,
          "distance_covered": 2332757,
          "mower_work_time": 109959,
          "blade_work_time": 102256,
          "blade_work_time_reset": 2798,
          "blade_work_time_reset_at": "2022-04-14T22:13:19-04:00",
          "battery_charge_cycles": 616,
          "battery_charge_cycles_reset": 0,
          "battery_charge_cycles_reset_at": null,
          "created_at": "2021-03-22T11:00:12-04:00",
          "updated_at": "2024-07-12T17:01:43-04:00",
          "last_status": {
            "timestamp": "2024-07-22T18:21:18-04:00",
            "payload": {
              "cfg": {
                "id": 0,
                "lg": "en",
                "tm": "18:21:18",
                "dt": "22/07/2024",
                "sc": {
                  "m": 1,
                  "distm": 0,
                  "ots": {
                    "bc": 0,
                    "wtm": 0
                  },
                  "p": 0,
                  "d": [
                    [
                      "16:00",
                      360,
                      0
                    ],
                    [
                      "10:00",
                      420,
                      1
                    ],
                    [
                      "17:00",
                      240,
                      0
                    ],
                    [
                      "10:00",
                      660,
                      0
                    ],
                    [
                      "17:00",
                      240,
                      1
                    ],
                    [
                      "10:00",
                      420,
                      0
                    ],
                    [
                      "10:00",
                      600,
                      0
                    ]
                  ],
                  "dd": [
                    [
                      "09:00",
                      0,
                      0
                    ],
                    [
                      "09:00",
                      0,
                      0
                    ],
                    [
                      "09:00",
                      0,
                      0
                    ],
                    [
                      "09:00",
                      0,
                      0
                    ],
                    [
                      "09:00",
                      0,
                      0
                    ],
                    [
                      "09:00",
                      0,
                      0
                    ],
                    [
                      "09:00",
                      0,
                      0
                    ]
                  ]
                },
                "cmd": 0,
                "mz": [
                  0,
                  0,
                  0,
                  0
                ],
                "mzv": [
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0
                ],
                "mzk": 0,
                "rd": 180,
                "sn": "2021309149030001875C",
                "al": {
                  "lvl": 0,
                  "t": 60
                },
                "tq": 0,
                "modules": {
                  "4G": {
                    "enabled": 1,
                    "geo": {
                      "coo": [
                        35.945805,
                        -84.131607
                      ],
                      "rad": 33
                    }
                  }
                }
              },
              "dat": {
                "mac": "E8DB840AA228",
                "fw": 3.32,
                "fwb": 1,
                "bt": {
                  "t": 40.8,
                  "v": 20.14,
                  "p": 100,
                  "nr": 619,
                  "c": 0,
                  "m": 0
                },
                "dmp": [
                  -2.7,
                  -0.1,
                  115.5
                ],
                "st": {
                  "b": 102657,
                  "d": 2341626,
                  "wt": 110373,
                  "bl": 169
                },
                "ls": 1,
                "le": 0,
                "lz": 0,
                "rsi": -49,
                "lk": 0,
                "act": 1,
                "tr": 0,
                "conn": "4G",
                "rain": {
                  "s": 0,
                  "cnt": 0
                },
                "time": {
                  "r": 0,
                  "l": 0
                },
                "modules": {
                  "4G": {
                    "mode": 1,
                    "stat": "ok",
                    "vers": 2.55,
                    "batt": {
                      "v": 4.11,
                      "l": 96,
                      "t": 37
                    },
                    "network": {
                      "status": "connected",
                      "ICCID": "8944538523018983141",
                      "IMSI": "204080748032298",
                      "mode": "Cat-M1",
                      "rssi": -49
                    },
                    "geo": {
                      "stat": "in"
                    },
                    "gps": {
                      "coo": [
                        35.945885,
                        -84.131633
                      ]
                    }
                  }
                }
              }
            }
          },
          "model": {
            "code": "WR155",
            "friendly_name": "Landroid L1000",
            "model_year": 2021,
            "cutting_width": 200
          }
        },
        "_tz": null,
        "id": 579855,
        "uuid": "96c5307c-8588-4002-a336-7b022b169950",
        "product_id": 68,
        "serial_number": "2021309149030001875C",
        "mac_address": "E8DB840AA228",
        "locked": false,
        "sim": {
          "id": 9329,
          "iccid": "8944538523018983141",
          "sim_status": "provisioned",
          "pending_activation": false,
          "contract_starts_at": "2021-12-08T00:00:00-05:00",
          "contract_ends_at": "2024-12-08T00:00:00-05:00",
          "created_at": "2021-12-08T16:59:21-05:00",
          "updated_at": "2024-07-22T06:01:06-04:00"
        },
        "mqtt_registered": true,
        "registered_at": "2021-12-08T00:00:00-05:00",
        "online": true,
        "protocol": 0,
        "capabilities": {
          "__type": "<class 'pyworxcloud.utils.capability.Capability'>",
          "repr": "<pyworxcloud.utils.capability.Capability object at 0x7f267cdbfb30>"
        },
        "capabilities_available": [
          "display_pairing_shortcut"
        ],
        "name": "New 155",
        "blade_height_shift": 0,
        "pin_code": null,
        "setup_location": {
          "latitude": "**REDACTED**",
          "longitude": "**REDACTED**"
        },
        "city": {
          "id": 4621846,
          "country_id": 840,
          "name": "Farragut",
          "latitude": "**REDACTED**",
          "longitude": "**REDACTED**",
          "created_at": "2018-02-15T22:35:59-05:00",
          "updated_at": "2018-02-15T22:35:59-05:00"
        },
        "time_zone": "America/New_York",
        "improvement": true,
        "diagnostic": true,
        "mower_work_time": 109959,
        "last_status": {
          "timestamp": "2024-07-22T18:21:18-04:00",
          "payload": {
            "cfg": {
              "id": 0,
              "lg": "en",
              "tm": "18:21:18",
              "dt": "22/07/2024",
              "sc": {
                "m": 1,
                "distm": 0,
                "ots": {
                  "bc": 0,
                  "wtm": 0
                },
                "p": 0,
                "d": [
                  [
                    "16:00",
                    360,
                    0
                  ],
                  [
                    "10:00",
                    420,
                    1
                  ],
                  [
                    "17:00",
                    240,
                    0
                  ],
                  [
                    "10:00",
                    660,
                    0
                  ],
                  [
                    "17:00",
                    240,
                    1
                  ],
                  [
                    "10:00",
                    420,
                    0
                  ],
                  [
                    "10:00",
                    600,
                    0
                  ]
                ],
                "dd": [
                  [
                    "09:00",
                    0,
                    0
                  ],
                  [
                    "09:00",
                    0,
                    0
                  ],
                  [
                    "09:00",
                    0,
                    0
                  ],
                  [
                    "09:00",
                    0,
                    0
                  ],
                  [
                    "09:00",
                    0,
                    0
                  ],
                  [
                    "09:00",
                    0,
                    0
                  ],
                  [
                    "09:00",
                    0,
                    0
                  ]
                ]
              },
              "cmd": 0,
              "mz": [
                0,
                0,
                0,
                0
              ],
              "mzv": [
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0
              ],
              "mzk": 0,
              "rd": 180,
              "sn": "2021309149030001875C",
              "al": {
                "lvl": 0,
                "t": 60
              },
              "tq": 0,
              "modules": {
                "4G": {
                  "enabled": 1,
                  "geo": {
                    "coo": [
                      35.945805,
                      -84.131607
                    ],
                    "rad": 33
                  }
                }
              }
            },
            "dat": {
              "mac": "E8DB840AA228",
              "fw": 3.32,
              "fwb": 1,
              "bt": {
                "t": 40.8,
                "v": 20.14,
                "p": 100,
                "nr": 619,
                "c": 0,
                "m": 0
              },
              "dmp": [
                -2.7,
                -0.1,
                115.5
              ],
              "st": {
                "b": 102657,
                "d": 2341626,
                "wt": 110373,
                "bl": 169
              },
              "ls": 1,
              "le": 0,
              "lz": 0,
              "rsi": -49,
              "lk": 0,
              "act": 1,
              "tr": 0,
              "conn": "4G",
              "rain": {
                "s": 0,
                "cnt": 0
              },
              "time": {
                "r": 0,
                "l": 0
              },
              "modules": {
                "4G": {
                  "mode": 1,
                  "stat": "ok",
                  "vers": 2.55,
                  "batt": {
                    "v": 4.11,
                    "l": 96,
                    "t": 37
                  },
                  "network": {
                    "status": "connected",
                    "ICCID": "8944538523018983141",
                    "IMSI": "204080748032298",
                    "mode": "Cat-M1",
                    "rssi": -49
                  },
                  "geo": {
                    "stat": "in"
                  },
                  "gps": {
                    "coo": [
                      35.945885,
                      -84.131633
                    ]
                  }
                }
              }
            }
          }
        },
        "model": "Landroid L1000 (WR155)",
        "battery": {
          "cycles": {
            "total": 619,
            "current": 0,
            "reset_at": null,
            "reset_time": null
          },
          "temperature": 40.8,
          "voltage": 20.14,
          "percent": 100,
          "charging": false
        },
        "blades": {
          "total_on": 102657,
          "reset_at": 2798,
          "reset_time": "2022-04-14T22:13:19-04:00",
          "current_on": 99859
        },
        "chassis": {},
        "error": {
          "id": 0,
          "description": "no error"
        },
        "orientation": {
          "pitch": -2.7,
          "roll": -0.1,
          "yaw": 115.5
        },
        "rainsensor": {
          "delay": 180,
          "triggered": false,
          "remaining": 0
        },
        "status": {
          "id": 1,
          "description": "home"
        },
        "zone": {
          "current": 0,
          "index": 0,
          "indicies": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "starting_point": [
            0,
            0,
            0,
            0
          ]
        },
        "warranty": {
          "expires_at": "2026-03-01T00:00:00-05:00",
          "registered": true,
          "expired": false
        },
        "firmware": {
          "auto_upgrade": true,
          "version": "3.32.0+1"
        },
        "schedules": {
          "daily_progress": 100,
          "next_schedule_start": "2024-07-23T17:00:00-04:00",
          "time_extension": 0,
          "active": true,
          "auto_schedule": {
            "settings": null,
            "enabled": false
          },
          "primary": {
            "monday": {
              "start": "10:00",
              "end": "17:00",
              "duration": 420,
              "boundary": true
            },
            "tuesday": {
              "start": "17:00",
              "end": "21:00",
              "duration": 240,
              "boundary": false
            },
            "wednesday": {
              "start": "10:00",
              "end": "21:00",
              "duration": 660,
              "boundary": false
            },
            "thursday": {
              "start": "17:00",
              "end": "21:00",
              "duration": 240,
              "boundary": true
            },
            "friday": {
              "start": "10:00",
              "end": "17:00",
              "duration": 420,
              "boundary": false
            },
            "saturday": {
              "start": "10:00",
              "end": "20:00",
              "duration": 600,
              "boundary": false
            },
            "sunday": {
              "start": "16:00",
              "end": "22:00",
              "duration": 360,
              "boundary": false
            }
          },
          "secondary": {
            "monday": {
              "start": "09:00",
              "end": "09:00",
              "duration": 0,
              "boundary": false
            },
            "tuesday": {
              "start": "09:00",
              "end": "09:00",
              "duration": 0,
              "boundary": false
            },
            "wednesday": {
              "start": "09:00",
              "end": "09:00",
              "duration": 0,
              "boundary": false
            },
            "thursday": {
              "start": "09:00",
              "end": "09:00",
              "duration": 0,
              "boundary": false
            },
            "friday": {
              "start": "09:00",
              "end": "09:00",
              "duration": 0,
              "boundary": false
            },
            "saturday": {
              "start": "09:00",
              "end": "09:00",
              "duration": 0,
              "boundary": false
            },
            "sunday": {
              "start": "09:00",
              "end": "09:00",
              "duration": 0,
              "boundary": false
            }
          }
        },
        "in_topic": "PRM100/E8DB840AA228/commandIn",
        "out_topic": "PRM100/E8DB840AA228/commandOut",
        "_DeviceHandler__is_decoded": true,
        "_DeviceHandler__raw_data": "{\"cfg\":{\"id\":0,\"lg\":\"en\",\"tm\":\"18:21:18\",\"dt\":\"22/07/2024\",\"sc\":{\"m\":1,\"distm\":0,\"ots\":{\"bc\":0,\"wtm\":0},\"p\":0,\"d\":[[\"16:00\",360,0],[\"10:00\",420,1],[\"17:00\",240,0],[\"10:00\",660,0],[\"17:00\",240,1],[\"10:00\",420,0],[\"10:00\",600,0]],\"dd\":[[\"09:00\",0,0],[\"09:00\",0,0],[\"09:00\",0,0],[\"09:00\",0,0],[\"09:00\",0,0],[\"09:00\",0,0],[\"09:00\",0,0]]},\"cmd\":0,\"mz\":[0,0,0,0],\"mzv\":[0,0,0,0,0,0,0,0,0,0],\"mzk\":0,\"rd\":180,\"sn\":\"2021309149030001875C\",\"al\":{\"lvl\":0,\"t\":60},\"tq\":0,\"modules\":{\"4G\":{\"enabled\":1,\"geo\":{\"coo\":[35.945805,-84.131607],\"rad\":33}}}},\"dat\":{\"mac\":\"E8DB840AA228\",\"fw\":3.32,\"fwb\":1,\"bt\":{\"t\":40.8,\"v\":20.14,\"p\":100,\"nr\":619,\"c\":0,\"m\":0},\"dmp\":[-2.7,-0.1,115.5],\"st\":{\"b\":102657,\"d\":2341626,\"wt\":110373,\"bl\":169},\"ls\":1,\"le\":0,\"lz\":0,\"rsi\":-49,\"lk\":0,\"act\":1,\"tr\":0,\"conn\":\"4G\",\"rain\":{\"s\":0,\"cnt\":0},\"time\":{\"r\":0,\"l\":0},\"modules\":{\"4G\":{\"mode\":1,\"stat\":\"ok\",\"vers\":2.55,\"batt\":{\"v\":4.11,\"l\":96,\"t\":37},\"network\":{\"status\":\"connected\",\"ICCID\":\"8944538523018983141\",\"IMSI\":\"204080748032298\",\"mode\":\"Cat-M1\",\"rssi\":-49},\"geo\":{\"stat\":\"in\"},\"gps\":{\"coo\":[35.945885,-84.131633]}}}}}",
        "rssi": -49,
        "statistics": {
          "worktime_blades_on": 102657,
          "distance": 2341626,
          "worktime_total": 110373
        },
        "gps": {
          "latitude": "**REDACTED**",
          "longitude": "**REDACTED**"
        },
        "updated": "2024-07-22T18:21:18-04:00",
        "torque": 0,
        "partymode_enabled": false,
        "_DeviceHandler__json_data": {
          "cfg": {
            "id": 0,
            "lg": "en",
            "tm": "18:21:18",
            "dt": "22/07/2024",
            "sc": {
              "m": 1,
              "distm": 0,
              "ots": {
                "bc": 0,
                "wtm": 0
              },
              "p": 0,
              "d": [
                [
                  "16:00",
                  360,
                  0
                ],
                [
                  "10:00",
                  420,
                  1
                ],
                [
                  "17:00",
                  240,
                  0
                ],
                [
                  "10:00",
                  660,
                  0
                ],
                [
                  "17:00",
                  240,
                  1
                ],
                [
                  "10:00",
                  420,
                  0
                ],
                [
                  "10:00",
                  600,
                  0
                ]
              ],
              "dd": [
                [
                  "09:00",
                  0,
                  0
                ],
                [
                  "09:00",
                  0,
                  0
                ],
                [
                  "09:00",
                  0,
                  0
                ],
                [
                  "09:00",
                  0,
                  0
                ],
                [
                  "09:00",
                  0,
                  0
                ],
                [
                  "09:00",
                  0,
                  0
                ],
                [
                  "09:00",
                  0,
                  0
                ]
              ]
            },
            "cmd": 0,
            "mz": [
              0,
              0,
              0,
              0
            ],
            "mzv": [
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0
            ],
            "mzk": 0,
            "rd": 180,
            "sn": "2021309149030001875C",
            "al": {
              "lvl": 0,
              "t": 60
            },
            "tq": 0,
            "modules": {
              "4G": {
                "enabled": 1,
                "geo": {
                  "coo": [
                    35.945805,
                    -84.131607
                  ],
                  "rad": 33
                }
              }
            }
          },
          "dat": {
            "mac": "E8DB840AA228",
            "fw": 3.32,
            "fwb": 1,
            "bt": {
              "t": 40.8,
              "v": 20.14,
              "p": 100,
              "nr": 619,
              "c": 0,
              "m": 0
            },
            "dmp": [
              -2.7,
              -0.1,
              115.5
            ],
            "st": {
              "b": 102657,
              "d": 2341626,
              "wt": 110373,
              "bl": 169
            },
            "ls": 1,
            "le": 0,
            "lz": 0,
            "rsi": -49,
            "lk": 0,
            "act": 1,
            "tr": 0,
            "conn": "4G",
            "rain": {
              "s": 0,
              "cnt": 0
            },
            "time": {
              "r": 0,
              "l": 0
            },
            "modules": {
              "4G": {
                "mode": 1,
                "stat": "ok",
                "vers": 2.55,
                "batt": {
                  "v": 4.11,
                  "l": 96,
                  "t": 37
                },
                "network": {
                  "status": "connected",
                  "ICCID": "8944538523018983141",
                  "IMSI": "204080748032298",
                  "mode": "Cat-M1",
                  "rssi": -49
                },
                "geo": {
                  "stat": "in"
                },
                "gps": {
                  "coo": [
                    35.945885,
                    -84.131633
                  ]
                }
              }
            }
          }
        }
      }
    }
  }
}

### Relevant log entries

```txt
Only log entries pertain to an older device that was stolen, and not online.
```

**Comment by MTrab** [comment]
This is the Landroid Cloud integration, not the card
