### ISSUE TITLE
Adjusting Torque

### ISSUE THREAD

**Issue by liveleeiow** [MTrab/landroid_cloud#672]
### Describe the issue

Hi, apologies, this isn't an issue as such.

I found this intergration and card via a redit post.

It's installed and working, thank you.

My Larndroid is a WORX WR165E, running firmware 3.32.0+1

On home assistant, I do not appear to have the options for adjusting torque.  Is this a model specific feature or do I have to enable a mode so I can acess these adjustments?

Thank you so much.

### What version of Home Assistant Core has the issue?

core-2024.7.1

### What version of the Landroid Cloud integration do you have installed

5.05

### What type of installation are you running?

Home Assistant Container

### Which make and model is the mower used for this integration?

WR165E / M500 Plus

### Diagnostics information (NOT log entries!)

n/a

### Relevant log entries

```txt
n/a
```

**Comment by MTrab** [comment]
#620
