### ISSUE TITLE
HACS 2.0.0 update broke my Landroid cloud

### ISSUE THREAD

**Issue by IvanRaide** [MTrab/landroid_cloud#682]
### Describe the issue

Once I did the HACS 2.0.0 update that came out yesterday, after the reboot my landroid showed unavailable for all the entities.  Since I run HA in a VM, and had snapshot I reverted back and the landdroid was working again.

### What version of Home Assistant Core has the issue?

2024.8.2

### What was the last working version of Home Assistant Core?

2024.8.2

### What version of the Landroid Cloud integration do you have installed

5.0.6

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

Landroid M500 (WR165)

### Diagnostics information (NOT log entries!)

I really dont have any, I reverted immediately

### Relevant log entries

```txt
I really dont have any, I reverted immediately
```

**Comment by MTrab** [comment]
This has absolutely nothing to do with the HACS upgrade, as there is no relation between this integration and HACS, other than HACS being a delivery method for the integration
