### ISSUE TITLE
Any possibility to induce Rain Delay status ?

### ISSUE THREAD

**Issue by simistef** [MTrab/landroid_cloud#70]
Hi there,

Thinking of creating an automation in which to induce the action to lawnmower to go home and set to rain delay.

For example i am having an external rain sensor, and if it's raining during the time the lawnmower is docked (1 time before it will start mowing) to induce the rain delay.

This way my lawnmower would not get outside in the rain and spend 10 minutes to get wet and go home.

Any way i can do this ?

Thanks!

**Comment by MTrab** [comment]
Only by issuing a home command and then disable the schedule.
Unfortunately it's not possible force a rain delay state, as this is controlled by the water/rain sensor on the mower.

**Comment by simistef** [comment]
Thanks. How can i disable the schedule via Landroid cloud ?

**Comment by MTrab** [comment]
As of now, not possible. Might be in the next release as I'm currently testing a new config option I found.
