### ISSUE TITLE
just a question about blades entities

### ISSUE THREAD

**Issue by gralfj** [MTrab/landroid_cloud#700]
### Describe the issue

just trying to make some cards for this device, I just came up with this question, because, my first intention is to be notified when X time has passed since last blade manual cleaning.

for that I created an automation with

trigger

`{% set COT = states('sensor.dolly_blades_total_on_time') | float %} {% set COT2 = states('input_number.cot2') | float %} {% set result = COT - COT2 %} {{ result >= 1440 and result < 1441 }}
`

and then some actions

as I am waiting for he magic to happen I wondered to create a graph card, a custom mini graph card. I want it to show daily working time, so a utility helper was needed.

well, let`s get to the point

as I stared to the mini graph and see weird times appearing and don`t understand at all their meaning, I dive deep into the integration entities and found that

there are 2 entities

- sensor.dolly_blades_current_on_time
- sensor.dolly_blades_total_on_time

showing exact same output, and don´t know what does mean.

what they are for and why my graph is showing weird data?

could you please give some help?

this is a [capture](https://youtu.be/A0J22xLk_Qw) of the nonsense data

### What version of Home Assistant Core has the issue?

2024.9.3

### What was the last working version of Home Assistant Core?

1

### What version of the Landroid Cloud integration do you have installed

5.0.6

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

Landroid M500 (WR165E)

### Diagnostics information (NOT log entries!)

[config_entry-landroid_cloud-01J8S6Z55B6R6VYA1TRPWV2ZXY.json](https://github.com/user-attachments/files/17179288/config_entry-landroid_cloud-01J8S6Z55B6R6VYA1TRPWV2ZXY.json)

### Relevant log entries

```txt
none
```

### Additional information

none

**Comment by MTrab** [comment]
Total on is what it says - total blades on time for the device
Current on is blades on time since last reset in the app

**Comment by gralfj** [comment]
No way! Just that simple?  Didn't know that was respetable. Thanks for your time, and thank you for your integration
