### ISSUE TITLE
Example for pyworxcloud

### ISSUE THREAD

**Issue by henfri** [MTrab/landroid_cloud#71]
Hello,

thanks for sharing your work. 
Sorry for abusing landroid_cloud issue tracker for pyworxcloud, but I saw no other way to contact you; Issues seem not active at pyworxcloud.
I would like to use pyworxcloud, but I am lacking some documentation....
I tried to understand landroid_cloud, but I am not faimiliar with hass. Would you be so kind and add a short example.py to pyworxcloud?

- Establish connection
- Show battery status
- Start mowing
- Pause mowing
- Return to Base

That would really be helpful for me. From there, I think I can take it.

Best regards,
Hendrik

**Comment by MTrab** [comment]
Enabled Issue tracker on the repo and added a basic example

**Comment by henfri** [comment]
Thanks!

**Comment by henfri** [comment]
Just one feedback regarding the example.py:
Worx! :-)

I just had to enter my credentials and that was it. Great!
