### ISSUE TITLE
Possibility to modify schedule and/or operation time percentage

### ISSUE THREAD

**Issue by TorbenArentoft** [MTrab/landroid_cloud#8]
Does the API allow for setting the schedule?
In the App there is an option to adjust the weekly operational time +/- 100%. This function and/or the ability to set the mowing schedule could be very helpful in a smart home setup, so for instance you could disable mowing completely in certain conditions, say a period of no rain, where the grass doesn't grow anyway ;-)

**Comment by MTrab** [comment]
This is actually on my to-do schedule as the next enhancement, when I have fully sorted out supporting multiple mowers (which I'm just about to wrap up and release)
