### ISSUE TITLE
Stuck on Mowing forever

### ISSUE THREAD

**Issue by retroneo** [MTrab/landroid_cloud#82]
I don't use the charging station and instead swap fully charged batteries while it is mowing. When I am finished mowing I power the mower off, remove the battery and take the mower away.

In Home Assistant, the status stays as "Mowing" even though i couldn't possibly be. It would be great if the integration changed the status away from "Mowing" if it obviously isn't mowing any more. It would really help me out.

This could be achieved by it looking at the battery level staying the same while mowing for more than 30 minutes or the like.

Here's what the attributes look like 14 hours after I stopped mowing (Current time 17:26) - maybe there are several ways this could be detected and the status changed:

id: 4xxxx
blade_time: 6466
work_time: 6868
distance: 109936
status_id: 7
last_update: 03:14:22 26/10/2021
rssi: -84
yaw: 25.2
roll: 0.8
pitch: 4.6
raindelay: 180
timeextension: 0
firmware_version: 3.2
serial: 20193xxxx
mac: 98Fxxxx
schedule_enabled: true
friendly_name: WR139E status

**Comment by MTrab** [comment]
Just used a few days to perform some tests. On my S500, even after 48 hours on Mowing, nothing happens.

Did the test by starting the mowing routine and then turning the power off on the robot.

So either this is a feature of the newer models (as well as party mode and so on), or you do something to trigger the offline status.
