### ISSUE TITLE
Invalid config for [template]: Issue with my Landroid 455E

### ISSUE THREAD

**Issue by djiwhy** [MTrab/landroid_cloud#84]
Hi everybody,

I need you ... I'm having an issue when I restart HA.

I have this issue reported in logs :

Invalid config for [template]: expected dictionary for dictionary value @ data['sensors']. Got [OrderedDict([('name', 'Landroid IP'), ('unique_id', 'landroid_ip'), ('state', None), ('icon', 'mdi:ip-network')]), OrderedDict([('name', 'Landroid SN'), ('unique_id', 'landroid_sn'), ('state', '201930198601008203B0'), ('icon', 'mdi:numeric')]), OrderedDict([('name', 'Landroid MAC'), ('unique_id', 'landroid_mac'), ('state', '98:D8:63:46:1C:36'), ('icon', 'mdi:barcode')]), OrderedDict([('name', 'Landroid Bladetime'), ('unique_id', 'landroid_bladetime'), ('state', "{{ state_attr('sensor.landroi.... (See /config/packages/landroid.yaml, line 66). 

With this issue, i cannot see any blade time, id, s/n, tilt, pan and many other informations. But I can see batery level, landroid version, state (idle, mowing, ...) and errors.

I precise that I've the original landroid.yaml file. I haven't change anything in this file.
Landroid repo installed with HACS, on HA core-2021.10.6 on a Docker container on my DS918+ Synology NAS running Python 3.9.7

Do someone have an idea ?

Sorry for the poor english i'm using cause I'm French =)

**Comment by MTrab** [comment]
This is not related to the integration, but the barma-laj package.

**Comment by djiwhy** [comment]
Sorry for this mistake.
I will post on his Git.

Thanks 😊
