### ISSUE TITLE
Integration won't start if a mower is offline

### ISSUE THREAD

**Issue by daninden** [MTrab/landroid_cloud#86]
I have 3 mowers, of which 1 is currently offline.
This causes the integration to fail to start.

I locally updated the code which caused it to fail (it's in __init__.py).

```
            _LOGGER.debug("Partymode available: %s", client[dev].partymode)
            if not partymode and client[dev].partymode:
                partymode = True
            if not ots and client[dev].ots_enabled:
                ots = True

```

to

```
            try:
                _LOGGER.debug("Partymode available: %s", client[dev].partymode)
                if not partymode and client[dev].partymode:
                    partymode = True
                if not ots and client[dev].ots_enabled:
                    ots = True
            except Exception as err:
                _LOGGER.warning(err)
```

It fails with an error saying the attribute partymode is not available (WARNING (MainThread) [custom_components.landroid_cloud] 'WorxCloud' object has no attribute 'partymode').

I suspect this is due to not being able to retrieve the state of the mower.

**Comment by MTrab** [comment]
Fixed in v1.8.1
