### ISSUE TITLE
Error during setup of component landroid_cloud

### ISSUE THREAD

**Issue by shawwellpete** [MTrab/landroid_cloud#91]
After a reboot of home assistant landroid_cloud fails to start

I have tried removing it from HACS and reinstalling

I think it may be down to recent HACS update 1.19.3

Using version 1.8.0 of landroid_cloud

Home Assistant 2021.12.9

Running HA supervised on Debian 11

Logs 

This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/landroid_cloud/__init__.py:154
Integration: landroid_cloud (documentation, issues)
First occurred: 1:12:40 PM (1 occurrences)
Last logged: 1:12:40 PM

Error during setup of component landroid_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/config/custom_components/landroid_cloud/__init__.py", line 154, in async_setup
    _LOGGER.debug("Partymode available: %s", client[dev].partymode)
AttributeError: 'WorxCloud' object has no attribute 'partymode'

**Comment by MTrab** [comment]
Wild guess - your landroid is powered off or otherwise offline?

**Comment by shawwellpete** [comment]
Hi, thanks for taking the time to help and also for a great integration.

Yes it's powered off, but has been for  few weeks as it's Winter. It's only recently stopped showing the previous known settings.

I'll turn it on and see how it goes!

**Comment by MTrab** [comment]
Same as #86

**Comment by MTrab** [comment]
Fixed in v1.8.1
