### ISSUE TITLE
Unable to update landroid_cloud

### ISSUE THREAD

**Issue by coolhansen** [MTrab/landroid_cloud#93]
## Describe the bug
I'm not able to update the landroid_cloud version. After download and install I cannot restart HA

## Debug log

Source: util/package.py:99
First occurred: 5. März 2022, 22:35:57 (9 occurrences)
Last logged: 22:18:19

Unable to install package pyworxcloud==1.4.11: ERROR: Cannot install pyworxcloud==1.4.11 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by MTrab** [comment]
Uninstall landroid_cloud, remove the config entry in configuration.yaml, restart HA and then install the latest version.
You are running an outdated version of the plugin, this issue was fixed in the latest release (released ahead of HA release 2022.3)
