### ISSUE TITLE
pip version error

### ISSUE THREAD

**Issue by dmelliott20** [MTrab/landroid_cloud#97]
Plug-in does not load, Received the following error after upgrading to the latest version.

Logger: homeassistant.util.package
Source: util/package.py:99 
First occurred: 6:42:16 AM (6 occurrences) 
Last logged: 6:44:38 AM

Unable to install package pyworxcloud==1.4.11: ERROR: Cannot install pyworxcloud==1.4.11 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts WARNING: You are using pip version 22.0.3; however, version 22.0.4 is available. You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.

**Comment by dmelliott20** [comment]
In addition a check config of homeassistant returns

Integration error: landroid_cloud - Requirements for landroid_cloud not found: ['pyworxcloud==1.4.11'].

**Comment by dmelliott20** [comment]
Forced a reboot and the issue fixed itself

**Comment by MTrab** [comment]
Or just upgrade to latest release, which is using the correct dependency

**Comment by dmelliott20** [comment]
I was on the latest HA and Landroid cloud release.

Sent from my iPhone

On 26 Mar 2022, at 07:05, Morten Trab ***@***.***> wrote:

﻿

Or just upgrade to latest release, which is using the correct dependency

**Comment by MTrab** [comment]
No - if that's true, something is off in your installation.

https://github.com/MTrab/landroid_cloud/blob/master/custom_components/landroid_cloud/manifest.json

The current dependency is 1.4.13

**Comment by dmelliott20** [comment]
﻿Yep I know that but it happened.

Sent from my iPhone

On 26 Mar 2022, at 10:27, Morten Trab ***@***.***> wrote:

﻿

No - if that's true, something is off in your installation.

https://github.com/MTrab/landroid_cloud/blob/master/custom_components/landroid_cloud/manifest.json

The current dependency is 1.4.13
